let cloud = null;

try {
  cloud = require("wx-server-sdk");
  cloud.init({
    env: cloud.DYNAMIC_CURRENT_ENV,
  });
} catch (err) {
  cloud = null;
}

exports.main = async (event = {}) => {
  try {
    const payload = normalizeEventPayload(event);
    const data = generateRoadStaticTuneBaseline(payload);
    return {
      success: true,
      data,
    };
  } catch (err) {
    return {
      success: false,
      errorCode: "VALIDATION_ERROR",
      message: err && err.message ? err.message : "Failed to calculate tune.",
    };
  }
};

exports._internal = {
  generateRoadStaticTuneBaseline,
};

function normalizeEventPayload(event) {
  if (event && event.payload && typeof event.payload === "object") {
    return event.payload;
  }
  if (event && event.data && typeof event.data === "object") {
    return event.data;
  }
  const payload = { ...event };
  delete payload.type;
  return payload;
}

function generateRoadStaticTuneBaseline(rawInput) {
  const input = normalizeRoadStaticBaselineInput(rawInput || {});
  const carClass = classFromPI(input.pi);
  const useCase = input.useCase;
  const versionName = input.versionName || baselineDefaultVersionName(useCase);

  const draft = normalizeTuneProfilePower({
    carName: input.carName,
    carOrdinal: input.carOrdinal,
    carCategory: input.carCategory,
    carClass,
    pi: input.pi,
    drivetrain: input.drivetrain,
    useCase,
    versionName,
    weightKG: input.weightKG,
    frontWeightPct: input.frontWeightPct,
    powerKW: input.powerKW,
    torqueNM: input.torqueNM,
    redlineRPM: input.redlineRPM,
    notes: `Generated by ${useCase} Static Baseline.`,
  });

  const result = {
    profileDraft: draft,
    confidence: "high",
    generatedFields: [],
    tierRecommendations: [],
    skippedFields: [],
    warnings: [
      "当前结果是快速调校基线，不代表一次即可达到完美调校。请结合具体赛道表现、车辆反馈和个人驾驶习惯，在实测后继续逐项微调。",
    ],
    nextTestPlan: [
      baselineNextTestPlanIntro(useCase),
      "首次测试优先观察胎温、轮胎滑移平衡、刹车稳定性和车身是否触底。",
      "齿轮调校建议在后续结合动力输出和实测速度表现继续修正，不要只依赖AI估算。",
    ],
  };

  const add = (fieldKey, group, value, reason) => {
    setProfileField(result.profileDraft, fieldKey, value);
    result.generatedFields.push({
      fieldKey,
      group,
      value: result.profileDraft[fieldKey],
      unit: tunePlanFieldUnit(fieldKey),
      reason,
      defaultSelected: true,
    });
  };

  const addMeta = (fieldKey, group, value, unit, reason) => {
    if (value === null || value === undefined) return;
    result.generatedFields.push({
      fieldKey,
      group,
      value,
      unit,
      reason,
      defaultSelected: true,
    });
  };

  const skip = (fieldKey, group, reason, message) => {
    result.skippedFields.push({
      fieldKey,
      group,
      reason,
      message,
    });
  };

  const addTier = (fieldKey, group, tier, applicable, reason) => {
    result.tierRecommendations.push({
      fieldKey,
      group,
      tier,
      reason,
      applicable: Boolean(applicable),
    });
    if (!applicable) {
      skip(
        fieldKey,
        group,
        "not_confirmed_adjustable",
        "Confirm this tuning item is unlocked before using the tier recommendation."
      );
    }
  };

  addMeta("weightKG", "power", result.profileDraft.weightKG, "kg", "Required baseline input.");
  addMeta("frontWeightPct", "power", result.profileDraft.frontWeightPct, "%", "Required baseline input.");
  addMeta("powerKW", "power", result.profileDraft.powerKW, "kW", "Optional profile context.");
  addMeta("torqueNM", "power", result.profileDraft.torqueNM, "Nm", "Optional profile context.");
  addMeta("redlineRPM", "power", result.profileDraft.redlineRPM, "rpm", "Static gearing input and power-band context.");

  const tire = baselineTirePressures(useCase, input.drivetrain, input.tireCompound, input.weightKG);
  add("frontTirePressure", "tire", tire.front, baselineReason(useCase, "cold-pressure baseline in BAR from tire compound, vehicle weight, and drivetrain split."));
  add("rearTirePressure", "tire", tire.rear, baselineReason(useCase, "cold-pressure baseline in BAR from tire compound, vehicle weight, and drivetrain split."));

  const alignment = baselineAlignment(useCase, carClass, input.drivetrain, input.frontWeightPct, input.balanceBias);
  add("frontCamber", "alignment", alignment.frontCamber, baselineReason(useCase, "alignment baseline from PI class, front weight distribution, drivetrain, and balance bias."));
  add("rearCamber", "alignment", alignment.rearCamber, baselineReason(useCase, "alignment baseline from PI class, front weight distribution, drivetrain, and balance bias."));
  add("frontToe", "alignment", alignment.frontToe, baselineReason(useCase, "toe baseline; only strong balance bias moves Road away from neutral, while Drift uses fixed steering response."));
  add("rearToe", "alignment", alignment.rearToe, baselineReason(useCase, "toe baseline; only strong balance bias moves Road away from neutral, while Drift uses fixed steering response."));
  add("caster", "alignment", alignment.caster, baselineReason(useCase, "caster baseline from PI class, front weight distribution, and drivetrain."));

  const springFactor = springFactorForBaseline(useCase, carClass);
  const springs = baselineSprings(useCase, input.weightKG, input.frontWeightPct, springFactor, input.drivetrain);
  add("frontSpring", "springs", springs.front, "FH6 kgf/mm menu value calculated from vehicle weight, axle weight distribution, and PI spring factor.");
  add("rearSpring", "springs", springs.rear, "FH6 kgf/mm menu value calculated from vehicle weight, axle weight distribution, and PI spring factor.");

  const arb = baselineARB(useCase, input.frontWeightPct, carClass, input.drivetrain);
  add("frontArb", "antiroll", arb.front, baselineReason(useCase, "lateral load-transfer baseline."));
  add("rearArb", "antiroll", arb.rear, baselineReason(useCase, "lateral load-transfer baseline."));

  const damping = baselineDamping(useCase, input.weightKG, input.frontWeightPct, carClass, springFactor, springs.front, springs.rear, input.drivetrain);
  add("frontRebound", "damping", damping.frontRebound, baselineReason(useCase, "damping slider baseline from front axle weight, PI/use-case minimum bump, spring-factor multiplier, and bump/rebound ratio."));
  add("rearRebound", "damping", damping.rearRebound, "Road damping slider baseline offset from front rebound by front/rear spring display difference.");
  add("frontBump", "damping", damping.frontBump, baselineReason(useCase, "bump slider baseline from front axle weight, PI/use-case minimum bump, and spring-factor multiplier."));
  add("rearBump", "damping", damping.rearBump, "Road bump slider baseline offset from front bump by front/rear spring display difference.");

  const rideTier = baselineRideHeightTier(useCase);
  const aeroTier = baselineAeroTier(useCase);
  addTier("frontRideHeight", "springs", rideTier.tier, input.frontRideHeightAdjustable, rideTier.reason);
  addTier("rearRideHeight", "springs", rideTier.tier, input.rearRideHeightAdjustable, rideTier.reason);
  addTier("frontAero", "aero", aeroTier.tier, input.frontAeroAdjustable, aeroTier.reason);
  addTier("rearAero", "aero", aeroTier.tier, input.rearAeroAdjustable, aeroTier.reason);

  add("brakeBalance", "brake", baselineBrakeBalance(useCase, input.drivetrain, input.frontWeightPct, input.frontTireWidthMm, input.rearTireWidthMm), baselineReason(useCase, "brake-balance baseline by use case, drivetrain, front weight, and optional tire width split."));
  add("brakePressure", "brake", 100, "Neutral brake-pressure starting point.");
  appendDifferentialBaseline(
    result,
    useCase,
    carClass,
    input.drivetrain,
    input.weightKG,
    input.frontWeightPct,
    input.balanceBias,
    input.powerKW,
    input.torqueNM,
    add,
    skip
  );

  const gearing = baselineGearing(input);
  if (gearing.fields.length > 0) {
    gearing.fields.forEach((field) => add(field.key, "gearing", field.value, field.reason));
    for (let gear = input.gearCount + 1; gear <= 10; gear += 1) {
      skip(`gear${gear}`, "gearing", "locked_or_unavailable", "Gear is above the selected gear count and is treated as not unlocked.");
    }
  } else {
    skip("finalDrive", "gearing", gearing.reason, gearing.message);
    for (let gear = 1; gear <= 10; gear += 1) {
      skip(`gear${gear}`, "gearing", gearing.reason, gearing.message);
    }
  }

  appendDriftTargetSpeedWarning(result, input);
  applyRoadBaselineBiases(result, input);
  result.generatedFields.sort((a, b) => {
    if (a.group === b.group) return a.fieldKey.localeCompare(b.fieldKey);
    return a.group.localeCompare(b.group);
  });
  result.profileDraft = normalizeTuneProfilePower(result.profileDraft);
  return result;
}

function normalizeRoadStaticBaselineInput(raw) {
  const useCase = normalizeStaticBaselineUseCase(raw.useCase);
  const input = {
    carName: stringValue(raw.carName),
    versionName: stringValue(raw.versionName),
    useCase,
    carOrdinal: optionalInteger(raw.carOrdinal),
    carCategory: optionalInteger(raw.carCategory),
    pi: requiredInteger(raw.pi, "PI"),
    drivetrain: stringValue(raw.drivetrain).toUpperCase(),
    tireCompound: normalizeTireCompoundForUseCase(raw.tireCompound, useCase),
    weightKG: requiredInteger(raw.weightKG, "weight kg"),
    frontWeightPct: requiredInteger(raw.frontWeightPct, "front weight percentage"),
    powerKW: optionalNumber(raw.powerKW),
    torqueNM: optionalNumber(raw.torqueNM),
    redlineRPM: optionalInteger(raw.redlineRPM),
    gearCount: optionalInteger(raw.gearCount),
    tireDiameterCm: optionalNumber(raw.tireDiameterCm),
    frontTireDiameterCm: optionalNumber(raw.frontTireDiameterCm),
    rearTireDiameterCm: optionalNumber(raw.rearTireDiameterCm),
    frontTireWidthMm: optionalInteger(raw.frontTireWidthMm),
    rearTireWidthMm: optionalInteger(raw.rearTireWidthMm),
    targetTopSpeedKmh: optionalInteger(raw.targetTopSpeedKmh),
    frontRideHeightMinCm: optionalNumber(raw.frontRideHeightMinCm),
    frontRideHeightMaxCm: optionalNumber(raw.frontRideHeightMaxCm),
    rearRideHeightMinCm: optionalNumber(raw.rearRideHeightMinCm),
    rearRideHeightMaxCm: optionalNumber(raw.rearRideHeightMaxCm),
    frontAeroMinKgf: optionalNumber(raw.frontAeroMinKgf),
    frontAeroMaxKgf: optionalNumber(raw.frontAeroMaxKgf),
    rearAeroMinKgf: optionalNumber(raw.rearAeroMinKgf),
    rearAeroMaxKgf: optionalNumber(raw.rearAeroMaxKgf),
    frontRideHeightAdjustable: Boolean(raw.frontRideHeightAdjustable),
    rearRideHeightAdjustable: Boolean(raw.rearRideHeightAdjustable),
    frontAeroAdjustable: Boolean(raw.frontAeroAdjustable),
    rearAeroAdjustable: Boolean(raw.rearAeroAdjustable),
    balanceBias: normalizeBaselineBias(optionalNumber(raw.balanceBias)),
    stiffnessBias: normalizeBaselineBias(optionalNumber(raw.stiffnessBias)),
    speedBias: normalizeBaselineBias(optionalNumber(raw.speedBias)),
    tractionBias: normalizeBaselineBias(optionalNumber(raw.tractionBias)),
    shiftBias: normalizeBaselineBias(optionalNumber(raw.shiftBias)),
    trackFeedbackScene: normalizeTrackFeedbackScene(raw.trackFeedbackScene),
    trackFeedbackSymptom: normalizeTrackFeedbackSymptom(raw.trackFeedbackScene, raw.trackFeedbackSymptom),
    correctionStrengthBias: normalizeBaselineBias(optionalNumber(raw.correctionStrengthBias)),
    driftFeedbackSymptom: normalizeDriftFeedbackSymptom(raw.driftFeedbackSymptom),
    driftCorrectionStrengthBias: normalizeBaselineBias(optionalNumber(raw.driftCorrectionStrengthBias)),
    offroadFeedbackSymptom: normalizeOffroadFeedbackSymptom(raw.offroadFeedbackSymptom),
    offroadCorrectionStrengthBias: normalizeBaselineBias(optionalNumber(raw.offroadCorrectionStrengthBias)),
  };

  if (!supportedUseCases().includes(input.useCase)) {
    throw new Error("use case must be Road, Rally, Offroad, Drag, or Drift");
  }
  if (!supportedTireCompounds().includes(input.tireCompound)) {
    throw new Error(`tire compound must be one of: ${supportedTireCompounds().join(", ")}`);
  }
  if (input.pi < 100 || input.pi > 999) {
    throw new Error("PI must be between 100 and 999");
  }
  if (!isWholeNumber(input.weightKG) || input.weightKG < 300 || input.weightKG > 3000) {
    throw new Error("weight kg must be an integer between 300 and 3000");
  }
  if (!isWholeNumber(input.frontWeightPct) || input.frontWeightPct < 1 || input.frontWeightPct > 99) {
    throw new Error("front weight percentage must be an integer between 1 and 99");
  }
  if (input.redlineRPM !== null && (!isWholeNumber(input.redlineRPM) || input.redlineRPM < 1000 || input.redlineRPM > 20000)) {
    throw new Error("redline RPM must be an integer between 1000 and 20000");
  }
  if (input.gearCount !== null && (input.gearCount < 2 || input.gearCount > 10)) {
    throw new Error("gear count must be between 2 and 10");
  }
  if (input.tireDiameterCm !== null && (input.tireDiameterCm < 40 || input.tireDiameterCm > 120)) {
    throw new Error("tire diameter must be between 40 cm and 120 cm");
  }
  if (input.frontTireDiameterCm !== null && (input.frontTireDiameterCm < 40 || input.frontTireDiameterCm > 120)) {
    throw new Error("front tire diameter must be between 40 cm and 120 cm");
  }
  if (input.rearTireDiameterCm !== null && (input.rearTireDiameterCm < 40 || input.rearTireDiameterCm > 120)) {
    throw new Error("rear tire diameter must be between 40 cm and 120 cm");
  }
  validateOptionalTireWidth(input.frontTireWidthMm, "front tire width");
  validateOptionalTireWidth(input.rearTireWidthMm, "rear tire width");
  if (input.targetTopSpeedKmh !== null) {
    if (input.useCase === "Drift") {
      if (!isWholeNumber(input.targetTopSpeedKmh) || input.targetTopSpeedKmh < 20 || input.targetTopSpeedKmh > 260) {
        throw new Error("target drift speed must be an integer between 20 and 260 km/h");
      }
    } else if (!isWholeNumber(input.targetTopSpeedKmh) || input.targetTopSpeedKmh <= 0 || input.targetTopSpeedKmh > 600) {
      throw new Error("target top speed must be an integer between 1 and 600");
    }
  }
  validateBaselineBias(input.balanceBias, "balance bias");
  validateBaselineBias(input.stiffnessBias, "stiffness bias");
  validateBaselineBias(input.speedBias, "speed bias");
  validateBaselineBias(input.tractionBias, "traction bias");
  validateBaselineBias(input.shiftBias, "shift bias");
  validateBaselineBias(input.correctionStrengthBias, "correction strength bias");
  validateBaselineBias(input.driftCorrectionStrengthBias, "drift correction strength bias");
  validateBaselineBias(input.offroadCorrectionStrengthBias, "offroad correction strength bias");
  if (!["FWD", "RWD", "AWD"].includes(input.drivetrain)) {
    throw new Error("drivetrain must be FWD, RWD, or AWD");
  }
  if (!supportsTrackFeedbackUseCase(input.useCase)) {
    input.trackFeedbackScene = "";
    input.trackFeedbackSymptom = "";
  }
  if (!equalsIgnoreCase(input.useCase, "Drift")) {
    input.driftFeedbackSymptom = "";
  }
  if (!equalsIgnoreCase(input.useCase, "Offroad")) {
    input.offroadFeedbackSymptom = "";
  }
  return input;
}

function normalizeStaticBaselineUseCase(value) {
  const normalized = stringValue(value).toLowerCase();
  if (normalized === "" || normalized === "road" || normalized === "公路") return "Road";
  if (normalized === "drift" || normalized === "漂移") return "Drift";
  if (normalized === "rally" || normalized === "拉力") return "Rally";
  if (normalized === "offroad" || normalized === "off-road" || normalized === "越野") return "Offroad";
  if (normalized === "drag" || normalized === "直线" || normalized === "直线加速") return "Drag";
  return stringValue(value);
}

function supportedUseCases() {
  return ["Road", "Rally", "Offroad", "Drag", "Drift"];
}

function baselineDefaultVersionName(useCase) {
  switch (stringValue(useCase)) {
    case "Drift":
      return "Drift Baseline";
    case "Rally":
      return "Rally Baseline";
    case "Offroad":
      return "Offroad Baseline";
    case "Drag":
      return "Drag Baseline";
    default:
      return "Road Baseline";
  }
}

function baselineNextTestPlanIntro(useCase) {
  if (equalsIgnoreCase(useCase, "Drift")) {
    return "先用当前基线完成一次可控漂移测试，再调整多个系统。";
  }
  if (equalsIgnoreCase(useCase, "Rally")) {
    return "先用当前基线完成一次混合路面拉力测试，重点观察落地稳定性和连续弯响应。";
  }
  if (equalsIgnoreCase(useCase, "Offroad")) {
    return "先用当前基线完成一次越野颠簸路段测试，重点观察悬挂行程和抓地连续性。";
  }
  if (equalsIgnoreCase(useCase, "Drag")) {
    return "先用当前基线完成一次直线起步和全油门测试，重点观察起步打滑和换挡后转速。";
  }
  return "先用当前基线完成一次干净的公路测试，再调整多个系统。";
}

function baselineReason(useCase, text) {
  return `${stringValue(useCase) || "Road"} ${text}`.trim();
}

function normalizeBaselineBias(value) {
  return value === null || value === undefined || value === 0 ? 100 : value;
}

function validateBaselineBias(value, name) {
  if (!isWholeNumber(value) || value < 50 || value > 150) {
    throw new Error(`${name} must be an integer between 50 and 150`);
  }
}

function validateOptionalTireWidth(value, name) {
  if (value === null || value === undefined) return;
  if (!isWholeNumber(value) || value < 100 || value > 455) {
    throw new Error(`${name} must be an integer between 100 and 455 mm`);
  }
}

function normalizeTrackFeedbackScene(value) {
  const normalized = stringValue(value);
  if (["lowSpeedCorner", "highSpeedCorner"].includes(normalized)) return normalized;
  return "";
}

function normalizeTrackFeedbackSymptom(scene, value) {
  const normalizedScene = normalizeTrackFeedbackScene(scene);
  if (!normalizedScene) return "";
  const normalizedSymptom = stringValue(value);
  return supportedTrackFeedbackSymptoms(normalizedScene).includes(normalizedSymptom) ? normalizedSymptom : "";
}

function supportedTrackFeedbackSymptoms(scene) {
  switch (normalizeTrackFeedbackScene(scene)) {
    case "lowSpeedCorner":
      return ["entryUndersteer", "midUndersteer", "exitWheelspin", "brakingInstability"];
    case "highSpeedCorner":
      return ["highSpeedEntryInstability", "midUndersteer", "highSpeedOversteer", "bodyBounce"];
    default:
      return [];
  }
}

function normalizeDriftFeedbackSymptom(value) {
  const normalized = stringValue(value);
  return supportedDriftFeedbackSymptoms().includes(normalized) ? normalized : "";
}

function supportedDriftFeedbackSymptoms() {
  return [
    "initiationDifficult",
    "initiationTooSensitive",
    "angleTooSmall",
    "angleTooLarge",
    "rearWheelspin",
    "rearGripTooStrong",
  ];
}

function normalizeOffroadFeedbackSymptom(value) {
  const normalized = stringValue(value);
  return supportedOffroadFeedbackSymptoms().includes(normalized) ? normalized : "";
}

function supportedOffroadFeedbackSymptoms() {
  return [
    "bumpKick",
    "bottomingOut",
    "landingUnstable",
    "lazyTurnIn",
    "exitWheelspin",
    "highSpeedFloat",
  ];
}

function supportsTrackFeedbackUseCase(useCase) {
  return equalsIgnoreCase(useCase, "Road") || equalsIgnoreCase(useCase, "Rally");
}

function classFromPI(pi) {
  if (pi <= 400) return "D";
  if (pi <= 500) return "C";
  if (pi <= 600) return "B";
  if (pi <= 700) return "A";
  if (pi <= 800) return "S1";
  if (pi <= 900) return "S2";
  if (pi <= 998) return "R";
  return "X";
}

function baselineTirePressures(useCase, drivetrain, tireCompound, weightKG) {
  if (equalsIgnoreCase(useCase, "Drift")) {
    return baselineDriftTirePressures(weightKG);
  }
  if (equalsIgnoreCase(useCase, "Drag")) {
    return baselineDragTirePressures(drivetrain, weightKG);
  }
  if (equalsIgnoreCase(useCase, "Rally") || equalsIgnoreCase(useCase, "Offroad")) {
    return baselineLooseSurfaceTirePressures(useCase, drivetrain, tireCompound, weightKG);
  }
  const base = tireCompoundBasePressureBar(tireCompound);
  const weightAdj = tirePressureWeightAddBar(weightKG);
  const split = tirePressureSplitBar(drivetrain);
  const pressureClamp = tirePressureClampBar(useCase);
  return {
    front: clamp(roundTunePlanStep(base + weightAdj + split.front, 0.01), pressureClamp.min, pressureClamp.max),
    rear: clamp(roundTunePlanStep(base + weightAdj + split.rear, 0.01), pressureClamp.min, pressureClamp.max),
  };
}

function baselineDriftTirePressures(weightKG) {
  const front = clamp(roundTunePlanStep(2.10 + tirePressureWeightAddBar(weightKG), 0.01), 2.10, 2.60);
  const rear = clamp(roundTunePlanStep(front + 0.40, 0.01), 2.50, 3.00);
  return { front, rear };
}

function baselineLooseSurfaceTirePressures(useCase, drivetrain, tireCompound, weightKG) {
  const base = tireCompoundBasePressureBar(tireCompound);
  const weightAdj = tirePressureWeightAddBar(weightKG) * 0.7;
  const split = tirePressureSplitBar(drivetrain);
  const pressureClamp = tirePressureClampBar(useCase);
  const looseDrop = equalsIgnoreCase(useCase, "Offroad") ? -0.06 : -0.02;
  return {
    front: clamp(roundTunePlanStep(base + weightAdj + split.front * 0.5 + looseDrop, 0.01), pressureClamp.min, pressureClamp.max),
    rear: clamp(roundTunePlanStep(base + weightAdj + split.rear * 0.5 + looseDrop, 0.01), pressureClamp.min, pressureClamp.max),
  };
}

function baselineDragTirePressures(drivetrain, weightKG) {
  const weightAdj = tirePressureWeightAddBar(weightKG) * 0.5;
  switch (stringValue(drivetrain).toUpperCase()) {
    case "FWD":
      return {
        front: clamp(roundTunePlanStep(1.78 + weightAdj, 0.01), 1.50, 2.35),
        rear: clamp(roundTunePlanStep(2.28 + weightAdj, 0.01), 1.80, 2.55),
      };
    case "AWD":
      return {
        front: clamp(roundTunePlanStep(1.88 + weightAdj, 0.01), 1.55, 2.45),
        rear: clamp(roundTunePlanStep(1.82 + weightAdj, 0.01), 1.50, 2.40),
      };
    default:
      return {
        front: clamp(roundTunePlanStep(2.30 + weightAdj, 0.01), 1.85, 2.55),
        rear: clamp(roundTunePlanStep(1.62 + weightAdj, 0.01), 1.45, 2.20),
      };
  }
}

function normalizeTireCompound(value) {
  const compound = stringValue(value).toLowerCase();
  return compound || "sport";
}

function normalizeTireCompoundForUseCase(value, useCase) {
  const compound = stringValue(value).toLowerCase();
  if (!compound) {
    if (equalsIgnoreCase(useCase, "Drift")) return "drift";
    if (equalsIgnoreCase(useCase, "Rally")) return "rally";
    if (equalsIgnoreCase(useCase, "Offroad")) return "offroad";
    if (equalsIgnoreCase(useCase, "Drag")) return "drag";
    return "sport";
  }
  return normalizeTireCompound(compound);
}

function supportedTireCompounds() {
  return ["stock", "street", "sport", "semi", "slick", "rally", "offroad", "drift", "drag", "snow"];
}

function tireCompoundBasePressureBar(tireCompound) {
  switch (normalizeTireCompound(tireCompound)) {
    case "stock":
    case "street":
      return 2.14;
    case "semi":
      return 2.21;
    case "slick":
      return 2.24;
    case "rally":
      return 2.03;
    case "offroad":
    case "snow":
      return 2.00;
    case "drift":
      return 1.52;
    case "drag":
      return 1.72;
    default:
      return 2.17;
  }
}

function tirePressureWeightAddBar(weightKG) {
  if (weightKG < 900) return -0.07;
  if (weightKG < 1200) return -0.03;
  if (weightKG < 1500) return 0;
  if (weightKG < 1700) return 0.03;
  if (weightKG < 1900) return 0.07;
  return 0.10;
}

function tirePressureSplitBar(drivetrain) {
  switch (stringValue(drivetrain).toUpperCase()) {
    case "FWD":
      return { front: 0.07, rear: -0.03 };
    case "RWD":
      return { front: 0.03, rear: -0.03 };
    default:
      return { front: 0, rear: -0.03 };
  }
}

function tirePressureClampBar(useCase) {
  if (equalsIgnoreCase(useCase, "Drift")) return { min: 2.10, max: 3.60 };
  if (equalsIgnoreCase(useCase, "Rally")) return { min: 1.78, max: 2.28 };
  if (equalsIgnoreCase(useCase, "Offroad")) return { min: 1.65, max: 2.18 };
  if (equalsIgnoreCase(useCase, "Drag")) return { min: 1.45, max: 2.55 };
  return { min: 1.93, max: 2.41 };
}

function baselineSprings(useCase, weightKG, frontWeightPct, springFactor, drivetrain) {
  const kgToLb = 2.2046226218;
  const lbInPerForzaMetricDisplayUnit = 5.59974;
  const weightLb = weightKG * kgToLb;
  const frontShare = frontWeightPct / 100;
  const rearShare = 1 - frontShare;
  const support = supportRatiosForUseCase(useCase, frontWeightPct, drivetrain);
  const calc = (axleShare) => clamp(roundTunePlanStep((weightLb * axleShare * springFactor) / lbInPerForzaMetricDisplayUnit, 0.1), 0, 999);
  return {
    front: clamp(roundTunePlanStep(calc(frontShare) * support.front, 0.1), 0, 999),
    rear: clamp(roundTunePlanStep(calc(rearShare) * support.rear, 0.1), 0, 999),
  };
}

function roadSpringFactorForClass(carClass) {
  switch (stringValue(carClass).toUpperCase()) {
    case "D":
      return 0.30;
    case "C":
      return 0.34;
    case "B":
      return 0.38;
    case "A":
      return 0.44;
    case "S1":
      return 0.50;
    case "S2":
      return 0.56;
    case "R":
      return 0.60;
    case "X":
      return 0.64;
    default:
      return 0.38;
  }
}

function driftSpringFactorForClass(carClass) {
  switch (stringValue(carClass).toUpperCase()) {
    case "D":
      return 0.26;
    case "C":
      return 0.28;
    case "B":
      return 0.30;
    case "A":
      return 0.32;
    case "S1":
      return 0.35;
    case "S2":
      return 0.38;
    case "R":
      return 0.42;
    case "X":
      return 0.45;
    default:
      return 0.30;
  }
}

function springFactorForBaseline(useCase, carClass) {
  if (equalsIgnoreCase(useCase, "Drift")) return driftSpringFactorForClass(carClass);
  if (equalsIgnoreCase(useCase, "Rally")) return rallySpringFactorForClass(carClass);
  if (equalsIgnoreCase(useCase, "Offroad")) return offroadSpringFactorForClass(carClass);
  if (equalsIgnoreCase(useCase, "Drag")) return dragSpringFactorForClass(carClass);
  return roadSpringFactorForClass(carClass);
}

function rallySpringFactorForClass(carClass) {
  switch (stringValue(carClass).toUpperCase()) {
    case "D":
      return 0.28;
    case "C":
      return 0.30;
    case "B":
      return 0.32;
    case "A":
      return 0.34;
    case "S1":
      return 0.38;
    case "S2":
      return 0.42;
    case "R":
      return 0.46;
    case "X":
      return 0.50;
    default:
      return 0.32;
  }
}

function offroadSpringFactorForClass(carClass) {
  switch (stringValue(carClass).toUpperCase()) {
    case "D":
      return 0.24;
    case "C":
      return 0.26;
    case "B":
      return 0.28;
    case "A":
      return 0.30;
    case "S1":
      return 0.33;
    case "S2":
      return 0.36;
    case "R":
      return 0.40;
    case "X":
      return 0.44;
    default:
      return 0.28;
  }
}

function dragSpringFactorForClass(carClass) {
  switch (stringValue(carClass).toUpperCase()) {
    case "D":
      return 0.26;
    case "C":
      return 0.28;
    case "B":
      return 0.30;
    case "A":
      return 0.34;
    case "S1":
      return 0.38;
    case "S2":
      return 0.42;
    case "R":
      return 0.46;
    case "X":
      return 0.50;
    default:
      return 0.30;
  }
}

function baselineAlignment(useCase, carClass, drivetrain, frontWeightPct, balanceBias) {
  if (equalsIgnoreCase(useCase, "Drift")) {
    if (stringValue(drivetrain).toUpperCase() === "AWD") {
      return {
        frontCamber: -4.2,
        rearCamber: -0.4,
        frontToe: 0.8,
        rearToe: 0.0,
        caster: 7.0,
      };
    }
    return {
      frontCamber: -4.5,
      rearCamber: -0.5,
      frontToe: 1.0,
      rearToe: 0.0,
      caster: 7.0,
    };
  }
  if (equalsIgnoreCase(useCase, "Rally") || equalsIgnoreCase(useCase, "Offroad")) {
    return looseSurfaceAlignment(useCase, carClass, drivetrain, frontWeightPct, balanceBias);
  }
  if (equalsIgnoreCase(useCase, "Drag")) {
    return dragAlignment(drivetrain);
  }

  const base = roadAlignmentBaseByClass(carClass);
  let frontCamber = base.frontCamber;
  let rearCamber = base.rearCamber;
  let caster = base.caster;
  const frontWeightBias = roadFrontHeavyBalanceFactor(frontWeightPct);
  frontCamber -= 0.2 * frontWeightBias;
  rearCamber += 0.1 * frontWeightBias;
  caster += 0.3 * frontWeightBias;

  switch (stringValue(drivetrain).toUpperCase()) {
    case "FWD":
      frontCamber -= 0.1;
      rearCamber += 0.1;
      caster += 0.2;
      break;
    case "RWD":
      rearCamber -= 0.1;
      break;
    default:
      break;
  }

  const balanceAxis = baselineBiasAxis(balanceBias);
  if (balanceAxis > 0) {
    frontCamber -= 0.1 * balanceAxis;
    rearCamber += 0.1 * balanceAxis;
  } else if (balanceAxis < 0) {
    frontCamber += 0.1 * Math.abs(balanceAxis);
    rearCamber -= 0.1 * Math.abs(balanceAxis);
  }

  let frontToe = 0;
  let rearToe = 0;
  if (balanceBias >= 115) frontToe = -0.1;
  if (balanceBias <= 85) rearToe = 0.1;

  return {
    frontCamber: roundTunePlanStep(clamp(frontCamber, -2.5, -1.0), 0.1),
    rearCamber: roundTunePlanStep(clamp(rearCamber, -1.8, -0.6), 0.1),
    frontToe: roundTunePlanStep(clamp(frontToe, -0.1, 0), 0.1),
    rearToe: roundTunePlanStep(clamp(rearToe, 0, 0.1), 0.1),
    caster: roundTunePlanStep(clamp(caster, 4.8, 6.8), 0.1),
  };
}

function looseSurfaceAlignment(useCase, carClass, drivetrain, frontWeightPct, balanceBias) {
  const t = classInterpolationT(carClass);
  const frontWeightBias = roadFrontHeavyBalanceFactor(frontWeightPct);
  const offroad = equalsIgnoreCase(useCase, "Offroad");
  const balanceAxis = baselineBiasAxis(balanceBias);
  let frontCamber = offroad ? lerp(-0.6, -1.1, t) : lerp(-0.9, -1.5, t);
  let rearCamber = offroad ? lerp(-0.4, -0.8, t) : lerp(-0.6, -1.0, t);
  let caster = offroad ? lerp(4.8, 5.8, t) : lerp(5.2, 6.2, t);
  frontCamber -= 0.1 * frontWeightBias;
  rearCamber += 0.05 * frontWeightBias;
  caster += 0.2 * frontWeightBias;
  if (stringValue(drivetrain).toUpperCase() === "FWD") {
    frontCamber -= 0.1;
  }
  if (balanceAxis > 0) {
    frontCamber -= 0.1 * balanceAxis;
  } else if (balanceAxis < 0) {
    rearCamber -= 0.1 * Math.abs(balanceAxis);
  }
  return {
    frontCamber: roundTunePlanStep(clamp(frontCamber, offroad ? -1.5 : -1.8, -0.4), 0.1),
    rearCamber: roundTunePlanStep(clamp(rearCamber, offroad ? -1.0 : -1.3, -0.3), 0.1),
    frontToe: 0,
    rearToe: 0,
    caster: roundTunePlanStep(clamp(caster, 4.5, 6.5), 0.1),
  };
}

function dragAlignment(drivetrain) {
  const rearCamber = stringValue(drivetrain).toUpperCase() === "RWD" ? -0.2 : -0.1;
  return {
    frontCamber: 0,
    rearCamber,
    frontToe: 0,
    rearToe: 0,
    caster: 5.0,
  };
}

function roadAlignmentBaseByClass(carClass) {
  switch (stringValue(carClass).toUpperCase()) {
    case "A":
      return { frontCamber: -1.5, rearCamber: -1.0, caster: 5.5 };
    case "S1":
      return { frontCamber: -1.8, rearCamber: -1.1, caster: 6.0 };
    case "S2":
    case "R":
    case "X":
      return { frontCamber: -2.1, rearCamber: -1.2, caster: 6.5 };
    default:
      return { frontCamber: -1.2, rearCamber: -0.8, caster: 5.0 };
  }
}

function baselineDamping(useCase, weightKG, frontWeightPct, carClass, springFactor, frontSpring, rearSpring, drivetrain) {
  const kgToLb = 2.2046226218;
  const frontAxleLb = weightKG * kgToLb * frontWeightPct / 100;
  const baseBump = dampingMinBump(useCase, carClass) + (frontAxleLb / 200) * 0.1;
  const frontBump = baseBump * springDampingMultiplier(springFactor);
  const frontRebound = frontBump / dampingBumpRatio(useCase);
  const offset = rearDampingOffset(frontSpring, rearSpring);
  const ratio = dampingRatiosForUseCase(useCase, frontWeightPct, drivetrain);
  return {
    frontRebound: frontRebound * ratio.front,
    rearRebound: (frontRebound + offset.rebound) * ratio.rear,
    frontBump: frontBump * ratio.front,
    rearBump: (frontBump + offset.bump) * ratio.rear,
  };
}

function dampingMinBump(useCase, carClass) {
  if (equalsIgnoreCase(useCase, "Drift")) return 4.8;
  if (equalsIgnoreCase(useCase, "Rally")) return 4.3;
  if (equalsIgnoreCase(useCase, "Offroad")) return 3.9;
  if (equalsIgnoreCase(useCase, "Drag")) return 4.6;
  switch (stringValue(carClass).toUpperCase()) {
    case "S1":
      return 4.85;
    case "S2":
    case "R":
    case "X":
      return 4.9;
    default:
      return 4.8;
  }
}

function dampingBumpRatio(useCase) {
  switch (stringValue(useCase).toLowerCase()) {
    case "offroad":
    case "rally":
      return 0.55;
    case "drag":
      return 0.58;
    default:
      return 0.60;
  }
}

function springDampingMultiplier(springFactor) {
  return 1 + Math.max(0, springFactor - 0.30) * 2.0;
}

function rearDampingOffset(frontSpring, rearSpring) {
  const avg = (frontSpring + rearSpring) / 2;
  const diffPct = avg > 0 ? Math.abs(frontSpring - rearSpring) / avg * 100 : 0;
  let rebound = 0.2;
  let bump = 0.1;
  if (diffPct > 40) {
    rebound = 1.2;
    bump = 0.8;
  } else if (diffPct > 35) {
    rebound = 0.6;
    bump = 0.4;
  } else if (diffPct > 1.5) {
    rebound = 0.3;
    bump = 0.2;
  }
  if (frontSpring > rearSpring) return { rebound: -rebound, bump: -bump };
  if (rearSpring > frontSpring) return { rebound, bump };
  return { rebound: -0.2, bump: -0.1 };
}

function baselineARB(useCase, frontWeightPct, carClass, drivetrain) {
  const t = classInterpolationT(carClass);
  if (equalsIgnoreCase(useCase, "Drift")) {
    if (stringValue(drivetrain).toUpperCase() === "AWD") {
      return { front: Math.round(lerp(13, 22, t)), rear: Math.round(lerp(22, 36, t)) };
    }
    return { front: Math.round(lerp(15, 25, t)), rear: Math.round(lerp(18, 30, t)) };
  }
  if (equalsIgnoreCase(useCase, "Rally")) {
    return looseSurfaceARB(t, drivetrain, frontWeightPct, false);
  }
  if (equalsIgnoreCase(useCase, "Offroad")) {
    return looseSurfaceARB(t, drivetrain, frontWeightPct, true);
  }
  if (equalsIgnoreCase(useCase, "Drag")) {
    return dragARB(t, drivetrain);
  }
  const ratios = roadFrontHeavyARBRatios(frontWeightPct);
  const scale = (front, rear) => ({
    front: Math.round(front * ratios.front),
    rear: Math.round(rear * ratios.rear),
  });
  switch (stringValue(drivetrain).toUpperCase()) {
    case "RWD":
      return scale(lerp(18, 25, t), lerp(25, 35, t));
    case "FWD":
      return scale(lerp(8, 15, t), lerp(25, 40, t));
    case "AWD":
      return scale(lerp(22, 30, t), lerp(28, 38, t));
    default:
      return scale(lerp(18, 25, t), lerp(25, 35, t));
  }
}

function looseSurfaceARB(t, drivetrain, frontWeightPct, offroad) {
  const factor = roadFrontHeavyBalanceFactor(frontWeightPct);
  const frontRatio = 1 - 0.05 * factor;
  const rearRatio = 1 + 0.06 * factor;
  const range = offroad
    ? { frontLow: 5, frontHigh: 12, rearLow: 7, rearHigh: 16 }
    : { frontLow: 10, frontHigh: 20, rearLow: 14, rearHigh: 26 };
  let front = lerp(range.frontLow, range.frontHigh, t);
  let rear = lerp(range.rearLow, range.rearHigh, t);
  switch (stringValue(drivetrain).toUpperCase()) {
    case "FWD":
      front *= 0.85;
      rear *= 1.12;
      break;
    case "RWD":
      front *= 0.95;
      rear *= 1.05;
      break;
    default:
      break;
  }
  return {
    front: Math.round(front * frontRatio),
    rear: Math.round(rear * rearRatio),
  };
}

function dragARB(t, drivetrain) {
  if (stringValue(drivetrain).toUpperCase() === "FWD") {
    return {
      front: Math.round(lerp(8, 14, t)),
      rear: Math.round(lerp(2, 6, t)),
    };
  }
  return {
    front: Math.round(lerp(2, 8, t)),
    rear: Math.round(lerp(4, 10, t)),
  };
}

function supportRatiosForUseCase(useCase, frontWeightPct, drivetrain) {
  const factor = roadFrontHeavyBalanceFactor(frontWeightPct);
  if (equalsIgnoreCase(useCase, "Drift")) {
    if (stringValue(drivetrain).toUpperCase() === "AWD") {
      return { front: 0.96 - 0.03 * factor, rear: 1.10 + 0.08 * factor };
    }
    return { front: 1 - 0.02 * factor, rear: 1 + 0.06 * factor };
  }
  if (equalsIgnoreCase(useCase, "Rally")) {
    return { front: 1 - 0.03 * factor, rear: 1 + 0.08 * factor };
  }
  if (equalsIgnoreCase(useCase, "Offroad")) {
    return { front: 0.96 - 0.02 * factor, rear: 1.08 + 0.06 * factor };
  }
  if (equalsIgnoreCase(useCase, "Drag")) {
    return { front: 0.86, rear: 1.15 };
  }
  return { front: 1 - 0.08 * factor, rear: 1 + 0.09 * factor };
}

function dampingRatiosForUseCase(useCase, frontWeightPct, drivetrain) {
  const factor = roadFrontHeavyBalanceFactor(frontWeightPct);
  if (equalsIgnoreCase(useCase, "Drift")) {
    if (stringValue(drivetrain).toUpperCase() === "AWD") {
      return { front: 0.96 - 0.02 * factor, rear: 1.10 + 0.06 * factor };
    }
    return { front: 1, rear: 1 + 0.05 * factor };
  }
  if (equalsIgnoreCase(useCase, "Rally")) {
    return { front: 0.92, rear: 1.05 + 0.04 * factor };
  }
  if (equalsIgnoreCase(useCase, "Offroad")) {
    return { front: 0.82, rear: 0.96 + 0.04 * factor };
  }
  if (equalsIgnoreCase(useCase, "Drag")) {
    return { front: 0.72, rear: 1.08 };
  }
  return { front: 1 - 0.06 * factor, rear: 1 + 0.06 * factor };
}

function roadFrontHeavyARBRatios(frontWeightPct) {
  const factor = roadFrontHeavyBalanceFactor(frontWeightPct);
  return { front: 1 - 0.06 * factor, rear: 1 + 0.08 * factor };
}

function roadFrontHeavyBalanceFactor(frontWeightPct) {
  return clamp((frontWeightPct - 50) / 10, 0, 1);
}

function classInterpolationT(carClass) {
  switch (stringValue(carClass).toUpperCase()) {
    case "D":
      return 0.10;
    case "C":
      return 0.20;
    case "B":
      return 0.30;
    case "A":
      return 0.40;
    case "S1":
      return 0.60;
    case "S2":
      return 0.75;
    case "R":
      return 0.90;
    case "X":
      return 1.00;
    default:
      return 0.40;
  }
}

function baselineBrakeBalance(useCase, drivetrain, frontWeightPct, frontTireWidthMm, rearTireWidthMm) {
  if (equalsIgnoreCase(useCase, "Drift")) return 48;
  if (equalsIgnoreCase(useCase, "Rally")) {
    return stringValue(drivetrain).toUpperCase() === "FWD" ? 56 : 52;
  }
  if (equalsIgnoreCase(useCase, "Offroad")) {
    return stringValue(drivetrain).toUpperCase() === "FWD" ? 55 : 51;
  }
  if (equalsIgnoreCase(useCase, "Drag")) return 50;
  const frontWeightAdj = roadBrakeFrontWeightAdjustment(frontWeightPct);
  const tireWidthAdj = roadBrakeTireWidthAdjustment(frontTireWidthMm, rearTireWidthMm);
  const value = (base) => clamp(roundTunePlanStep(base + frontWeightAdj + tireWidthAdj, 1), 45, 65);
  switch (stringValue(drivetrain).toUpperCase()) {
    case "FWD":
      return value(56);
    case "AWD":
      return value(53);
    default:
      return value(52);
  }
}

function roadBrakeFrontWeightAdjustment(frontWeightPct) {
  if (frontWeightPct <= 48) return 1;
  if (frontWeightPct >= 60) return -2;
  if (frontWeightPct >= 57) return -1;
  return 0;
}

function roadBrakeTireWidthAdjustment(frontTireWidthMm, rearTireWidthMm) {
  const axis = tireWidthBalanceAxis(frontTireWidthMm, rearTireWidthMm);
  if (axis === 0) return 0;
  return clamp(-1.5 * axis, -2, 1);
}

function tireWidthBalanceAxis(frontTireWidthMm, rearTireWidthMm) {
  if (!frontTireWidthMm || !rearTireWidthMm) return 0;
  const diffMm = rearTireWidthMm - frontTireWidthMm;
  if (Math.abs(diffMm) < 10) return 0;
  return clamp(diffMm / 40, -1.5, 1.5);
}

function appendDifferentialBaseline(result, useCase, carClass, drivetrain, weightKG, frontWeightPct, balanceBias, powerKW, torqueNM, add, skip) {
  if (equalsIgnoreCase(useCase, "Drift")) {
    switch (stringValue(drivetrain).toUpperCase()) {
      case "RWD":
        add("rearDiffAccel", "differential", 100, "Drift rear acceleration differential baseline; RWD preferred full lock starting point.");
        add("rearDiffDecel", "differential", 100, "Drift rear deceleration differential baseline; RWD preferred full lock starting point.");
        break;
      case "AWD":
        appendAwdDriftDifferential(carClass, weightKG, frontWeightPct, balanceBias, powerKW, torqueNM, add);
        break;
      case "FWD":
        skip("frontDiffAccel", "differential", "drift_rwd_preferred", "Drift quick tune prefers RWD; FWD drift differential values are not generated automatically.");
        skip("frontDiffDecel", "differential", "drift_rwd_preferred", "Drift quick tune prefers RWD; FWD drift differential values are not generated automatically.");
        skip("rearDiffAccel", "differential", "drift_rwd_preferred", "FWD drift does not have a rear differential to tune.");
        skip("rearDiffDecel", "differential", "drift_rwd_preferred", "FWD drift does not have a rear differential to tune.");
        break;
      default:
        break;
    }
    return;
  }
  if (equalsIgnoreCase(useCase, "Rally") || equalsIgnoreCase(useCase, "Offroad") || equalsIgnoreCase(useCase, "Drag")) {
    appendSpecialUseDifferential(useCase, carClass, drivetrain, weightKG, frontWeightPct, balanceBias, powerKW, torqueNM, add, skip);
    return;
  }

  const diff = baselineDifferential(carClass, drivetrain, weightKG, frontWeightPct, balanceBias);
  switch (stringValue(drivetrain).toUpperCase()) {
    case "FWD":
      add("frontDiffAccel", "differential", diff.frontAccel, "FWD road differential baseline from PI class, axle load, vehicle weight, and balance bias.");
      add("frontDiffDecel", "differential", diff.frontDecel, "FWD road deceleration differential baseline from PI class, axle load, vehicle weight, and balance bias.");
      break;
    case "RWD":
      add("rearDiffAccel", "differential", diff.rearAccel, "RWD road differential baseline from PI class, axle load, vehicle weight, and balance bias.");
      add("rearDiffDecel", "differential", diff.rearDecel, "RWD road deceleration differential baseline from PI class, axle load, vehicle weight, and balance bias.");
      break;
    case "AWD":
      add("frontDiffAccel", "differential", diff.frontAccel, "AWD front differential baseline from PI class, axle load, vehicle weight, and balance bias.");
      add("frontDiffDecel", "differential", diff.frontDecel, "AWD front deceleration differential baseline from PI class, axle load, vehicle weight, and balance bias.");
      add("rearDiffAccel", "differential", diff.rearAccel, "AWD rear differential baseline from PI class, axle load, vehicle weight, and balance bias.");
      add("rearDiffDecel", "differential", diff.rearDecel, "AWD rear deceleration differential baseline from PI class, axle load, vehicle weight, and balance bias.");
      add("centerDiffBalance", "differential", diff.centerSplit, "AWD center balance baseline from PI class, front weight distribution, and balance bias.");
      break;
    default:
      break;
  }
}

function appendAwdDriftDifferential(carClass, weightKG, frontWeightPct, balanceBias, powerKW, torqueNM, add) {
  const classT = classInterpolationT(carClass);
  const frontLoadBias = clamp((frontWeightPct - 50) / 15, -1, 1);
  const heavyBias = clamp((weightKG - 1400) / 600, -1, 1);
  const balanceAxis = baselineBiasAxis(balanceBias);
  const powerBias = performanceDifferentialBias(powerKW, torqueNM, weightKG, carClass, "Drift");
  const value = (raw) => clamp(roundTunePlanStep(raw, 1), 0, 100);

  add("frontDiffAccel", "differential", value(15 + 6 * classT + powerBias + 0.5 * frontLoadBias - 4 * balanceAxis), "AWD drift front acceleration differential baseline keeps front pull very low so the car holds angle instead of straightening.");
  add("frontDiffDecel", "differential", value(0 + 3 * classT + heavyBias - 2 * balanceAxis), "AWD drift front deceleration differential baseline keeps front coast locking low for easier initiation.");
  add("rearDiffAccel", "differential", value(96 + 6 * classT + 4 * powerBias + heavyBias + 3 * balanceAxis), "AWD drift rear acceleration differential baseline strongly locks the rear for sustained wheelspin.");
  add("rearDiffDecel", "differential", value(88 + 10 * classT + heavyBias + 3 * balanceAxis), "AWD drift rear deceleration differential baseline is more aggressive for initiation and transitions.");
  add("centerDiffBalance", "differential", value(84 + 10 * classT + 3 * powerBias + 3 * balanceAxis - frontLoadBias), "AWD drift center balance strongly biases torque rearward while retaining a small amount of front pull.");
}

function appendSpecialUseDifferential(useCase, carClass, drivetrain, weightKG, frontWeightPct, balanceBias, powerKW, torqueNM, add, skip) {
  const drive = stringValue(drivetrain).toUpperCase();
  const classT = classInterpolationT(carClass);
  const frontLoadBias = clamp((frontWeightPct - 50) / 15, -1, 1);
  const heavyBias = clamp((weightKG - 1400) / 600, -1, 1);
  const balanceAxis = baselineBiasAxis(balanceBias);
  const powerBias = performanceDifferentialBias(powerKW, torqueNM, weightKG, carClass, useCase);
  const value = (raw) => clamp(roundTunePlanStep(raw, 1), 0, 100);

  if (equalsIgnoreCase(useCase, "Drag")) {
    switch (drive) {
      case "FWD":
        add("frontDiffAccel", "differential", value(74 + 10 * classT + 4 * powerBias + 2 * heavyBias + 2 * frontLoadBias), "Drag FWD acceleration differential baseline for launch traction.");
        add("frontDiffDecel", "differential", 0, "Drag deceleration differential baseline keeps coast locking low.");
        return;
      case "AWD":
        add("frontDiffAccel", "differential", value(38 + 10 * classT + 3 * powerBias + heavyBias), "Drag AWD front acceleration differential baseline for launch support.");
        add("frontDiffDecel", "differential", 0, "Drag deceleration differential baseline keeps coast locking low.");
        add("rearDiffAccel", "differential", value(92 + 10 * classT + 4 * powerBias + heavyBias + 2 * balanceAxis), "Drag AWD rear acceleration differential baseline prioritizes rear launch drive.");
        add("rearDiffDecel", "differential", 0, "Drag deceleration differential baseline keeps coast locking low.");
        add("centerDiffBalance", "differential", value(72 + 10 * classT + 3 * powerBias + balanceAxis), "Drag AWD center balance baseline biases launch torque rearward.");
        return;
      default:
        add("rearDiffAccel", "differential", value(90 + 12 * classT + 5 * powerBias + heavyBias + 2 * balanceAxis), "Drag RWD acceleration differential baseline for launch traction.");
        add("rearDiffDecel", "differential", 0, "Drag deceleration differential baseline keeps coast locking low.");
        return;
    }
  }

  const offroad = equalsIgnoreCase(useCase, "Offroad");
  switch (drive) {
    case "FWD":
      add(
        "frontDiffAccel",
        "differential",
        value((offroad ? 42 : 34) + (offroad ? 10 : 8) * classT + 2 * powerBias + heavyBias + frontLoadBias - 2 * balanceAxis),
        `${useCase} FWD acceleration differential baseline for loose-surface traction.`
      );
      add(
        "frontDiffDecel",
        "differential",
        value((offroad ? 15 : 10) + (offroad ? 5 : 4) * classT + heavyBias - balanceAxis),
        `${useCase} FWD deceleration differential baseline for rotation on loose surfaces.`
      );
      return;
    case "RWD":
      add(
        "rearDiffAccel",
        "differential",
        value((offroad ? 66 : 58) + 12 * classT + 2 * powerBias + heavyBias - frontLoadBias + 2 * balanceAxis),
        `${useCase} RWD acceleration differential baseline for loose-surface drive.`
      );
      add(
        "rearDiffDecel",
        "differential",
        value((offroad ? 23 : 18) + (offroad ? 10 : 8) * classT + heavyBias + 1.5 * balanceAxis),
        `${useCase} RWD deceleration differential baseline for stability on entry.`
      );
      return;
    case "AWD":
      add(
        "frontDiffAccel",
        "differential",
        value((offroad ? 40 : 30) + (offroad ? 7 : 8) * classT + powerBias + frontLoadBias - 2 * balanceAxis),
        `${useCase} AWD front acceleration differential baseline for loose-surface pull.`
      );
      add(
        "frontDiffDecel",
        "differential",
        value((offroad ? 15 : 10) + (offroad ? 5 : 4) * classT + heavyBias - balanceAxis),
        `${useCase} AWD front deceleration differential baseline for entry rotation.`
      );
      add(
        "rearDiffAccel",
        "differential",
        value((offroad ? 70 : 62) + 10 * classT + 2 * powerBias + heavyBias - 0.5 * frontLoadBias + 2 * balanceAxis),
        `${useCase} AWD rear acceleration differential baseline for loose-surface drive.`
      );
      add(
        "rearDiffDecel",
        "differential",
        value((offroad ? 24 : 22) + (offroad ? 8 : 7) * classT + heavyBias + 1.5 * balanceAxis),
        `${useCase} AWD rear deceleration differential baseline for stability.`
      );
      add(
        "centerDiffBalance",
        "differential",
        value((offroad ? 54 : 60) + (offroad ? 6 : 8) * classT + 0.5 * frontLoadBias + 2 * balanceAxis + powerBias),
        `${useCase} AWD center balance baseline for mixed-grip exits.`
      );
      return;
    default:
      skip("frontDiffAccel", "differential", "unsupported_drivetrain", "Unsupported drivetrain for differential generation.");
  }
}

function performanceDifferentialBias(powerKW, torqueNM, weightKG, carClass, useCase) {
  if (!Number.isFinite(weightKG) || weightKG <= 0) return 0;
  const reference = performanceReferencePerTon(carClass, useCase);
  const weights = performanceSignalWeights(useCase);
  let weightedSum = 0;
  let weightSum = 0;
  if (Number.isFinite(powerKW) && powerKW > 0) {
    const kwPerTon = powerKW / weightKG * 1000;
    weightedSum += clamp((kwPerTon - reference.kwPerTon) / (reference.kwPerTon * 0.45), -1, 1) * weights.power;
    weightSum += weights.power;
  }
  if (Number.isFinite(torqueNM) && torqueNM > 0) {
    const nmPerTon = torqueNM / weightKG * 1000;
    weightedSum += clamp((nmPerTon - reference.nmPerTon) / (reference.nmPerTon * 0.45), -1, 1) * weights.torque;
    weightSum += weights.torque;
  }
  return weightSum === 0 ? 0 : weightedSum / weightSum;
}

function performanceReferencePerTon(carClass, useCase) {
  const classReference = {
    D: { kwPerTon: 65, nmPerTon: 160 },
    C: { kwPerTon: 90, nmPerTon: 220 },
    B: { kwPerTon: 130, nmPerTon: 300 },
    A: { kwPerTon: 190, nmPerTon: 420 },
    S1: { kwPerTon: 270, nmPerTon: 560 },
    S2: { kwPerTon: 400, nmPerTon: 780 },
    R: { kwPerTon: 560, nmPerTon: 1000 },
    X: { kwPerTon: 720, nmPerTon: 1200 },
  };
  const multipliers = performanceUseCaseMultipliers(useCase);
  const base = classReference[stringValue(carClass)] || classReference.A;
  return {
    kwPerTon: base.kwPerTon * multipliers.power,
    nmPerTon: base.nmPerTon * multipliers.torque,
  };
}

function performanceUseCaseMultipliers(useCase) {
  if (equalsIgnoreCase(useCase, "Drag")) return { power: 1.2, torque: 1.1 };
  if (equalsIgnoreCase(useCase, "Drift")) return { power: 0.95, torque: 0.9 };
  if (equalsIgnoreCase(useCase, "Rally")) return { power: 0.9, torque: 0.85 };
  if (equalsIgnoreCase(useCase, "Offroad")) return { power: 0.85, torque: 0.8 };
  return { power: 1, torque: 1 };
}

function performanceSignalWeights(useCase) {
  if (equalsIgnoreCase(useCase, "Drag")) return { power: 0.6, torque: 0.4 };
  if (equalsIgnoreCase(useCase, "Drift")) return { power: 0.4, torque: 0.6 };
  return { power: 0.45, torque: 0.55 };
}

function baselineRideHeightTier(useCase) {
  if (equalsIgnoreCase(useCase, "Drift")) {
    return {
      tier: "low",
      reason: "Drift baseline targets a low ride-height tier, about the lower 10% slider area; set manually in game.",
    };
  }
  if (equalsIgnoreCase(useCase, "Rally")) {
    return {
      tier: "high",
      reason: "Rally baseline uses a high ride-height tier to preserve travel over mixed surfaces.",
    };
  }
  if (equalsIgnoreCase(useCase, "Offroad")) {
    return {
      tier: "highest",
      reason: "Offroad baseline uses the highest ride-height tier for bumps, jumps, and clearance.",
    };
  }
  if (equalsIgnoreCase(useCase, "Drag")) {
    return {
      tier: "low",
      reason: "Drag baseline keeps ride height low for straight-line stability.",
    };
  }
  return {
    tier: "low",
    reason: "Road baseline targets about 15% ride-height slider; set manually in game.",
  };
}

function baselineAeroTier(useCase) {
  if (equalsIgnoreCase(useCase, "Drift")) {
    return {
      tier: "low",
      reason: "Drift baseline treats aero as low priority; use a low tier only when adjustable and needed.",
    };
  }
  if (equalsIgnoreCase(useCase, "Rally")) {
    return {
      tier: "medium",
      reason: "Rally baseline keeps aero balanced because grip changes quickly across surfaces.",
    };
  }
  if (equalsIgnoreCase(useCase, "Offroad")) {
    return {
      tier: "low",
      reason: "Offroad baseline favors speed and suspension compliance over aero load.",
    };
  }
  if (equalsIgnoreCase(useCase, "Drag")) {
    return {
      tier: "lowest",
      reason: "Drag baseline favors straight-line speed with minimum aero load.",
    };
  }
  return {
    tier: "medium",
    reason: "Road baseline uses medium adjustable aero, roughly the middle slider range; set manually in game.",
  };
}

function baselineDifferential(carClass, drivetrain, weightKG, frontWeightPct, balanceBias) {
  const classT = classInterpolationT(carClass);
  const frontLoadBias = clamp((frontWeightPct - 50) / 15, -1, 1);
  const heavyBias = clamp((weightKG - 1400) / 600, -1, 1);
  const balanceAxis = baselineBiasAxis(balanceBias);
  const value = (raw) => clamp(roundTunePlanStep(raw, 1), 0, 100);

  switch (stringValue(drivetrain).toUpperCase()) {
    case "FWD":
      return {
        frontAccel: value(lerp(22, 30, classT) + 1.0 * frontLoadBias + 0.5 * heavyBias - 2.0 * balanceAxis),
        frontDecel: value(lerp(5, 9, classT) + 0.5 * heavyBias - 1.0 * balanceAxis),
      };
    case "RWD":
      return {
        rearAccel: value(lerp(44, 54, classT) - 1.0 * frontLoadBias + 0.5 * heavyBias + 2.0 * balanceAxis),
        rearDecel: value(lerp(26, 34, classT) - 0.5 * frontLoadBias + 0.5 * heavyBias + 2.0 * balanceAxis),
      };
    case "AWD":
      return {
        frontAccel: value(lerp(17, 23, classT) + 0.4 * frontLoadBias + 0.5 * heavyBias - 1.5 * balanceAxis),
        frontDecel: value(lerp(5, 8, classT) + 0.5 * heavyBias - 1.0 * balanceAxis),
        rearAccel: value(lerp(55, 68, classT) - 0.3 * frontLoadBias + 0.5 * heavyBias + 2.5 * balanceAxis),
        rearDecel: value(lerp(20, 28, classT) - 0.25 * frontLoadBias + 0.5 * heavyBias + 1.5 * balanceAxis),
        centerSplit: value(lerp(66, 76, classT) + 0.5 * frontLoadBias + 2.5 * balanceAxis),
      };
    default:
      return {};
  }
}

function appendDriftTargetSpeedWarning(result, input) {
  if (!equalsIgnoreCase(input.useCase, "Drift")) return;
  const target = input.targetTopSpeedKmh;
  if (target === null || target === undefined) return;
  if (target >= 40 && target <= 180) return;
  result.warnings.push("漂移目标速度已按软限制生成。低于 40 km/h 或高于 180 km/h 时，齿轮结果更依赖实际动力曲线和常用漂移挡位，建议实测后微调。");
}

function applyRoadBaselineBiases(result, input) {
  const balanceAxis = baselineBiasAxis(input.balanceBias);
  const stiffnessAxis = baselineBiasAxis(input.stiffnessBias);
  const speedAxis = baselineBiasAxis(input.speedBias);
  const tractionAxis = baselineBiasAxis(input.tractionBias);
  const shiftAxis = baselineBiasAxis(input.shiftBias);
  const correctionMultiplier = normalizeBaselineBias(input.correctionStrengthBias) / 100;

  if (balanceAxis !== 0) {
    const note = `Balance bias ${input.balanceBias.toFixed(0)} adjusts front/rear ratio for stability versus rotation.`;
    const frontRatio = 1 - 0.08 * balanceAxis;
    const rearRatio = 1 + 0.08 * balanceAxis;
    const frontSupportRatio = 1 - 0.04 * balanceAxis;
    const rearSupportRatio = 1 + 0.04 * balanceAxis;
    scaleBaselineGeneratedField(result, "frontArb", frontRatio, note);
    scaleBaselineGeneratedField(result, "rearArb", rearRatio, note);
    scaleBaselineGeneratedField(result, "frontSpring", frontSupportRatio, note);
    scaleBaselineGeneratedField(result, "rearSpring", rearSupportRatio, note);
    scaleBaselineGeneratedField(result, "frontRebound", frontSupportRatio, note);
    scaleBaselineGeneratedField(result, "rearRebound", rearSupportRatio, note);
    scaleBaselineGeneratedField(result, "frontBump", frontSupportRatio, note);
    scaleBaselineGeneratedField(result, "rearBump", rearSupportRatio, note);
    adjustBaselineGeneratedField(result, "brakeBalance", (value) => clamp(value - 2 * balanceAxis, 45, 65), note);
  }

  if (stiffnessAxis !== 0) {
    const note = `Stiffness bias ${input.stiffnessBias.toFixed(0)} scales roll, spring, and damping support.`;
    const ratio = 1 + 0.12 * stiffnessAxis;
    ["frontArb", "rearArb", "frontSpring", "rearSpring", "frontRebound", "rearRebound", "frontBump", "rearBump"].forEach((key) => {
      scaleBaselineGeneratedField(result, key, ratio, note);
    });
  }

  if (speedAxis !== 0) {
    let note = `Speed bias ${input.speedBias.toFixed(0)} adjusts final drive toward top speed or acceleration while preserving gear spacing.`;
    if (equalsIgnoreCase(input.useCase, "Drift")) {
      note = `Drift speed bias ${input.speedBias.toFixed(0)} adjusts final drive toward higher-speed drift or lower-speed high-RPM drift while preserving gear spacing.`;
    }
    const ratio = 1 - 0.08 * speedAxis;
    scaleBaselineGeneratedField(result, "finalDrive", ratio, note);
  }

  applyRoadTireWidthBiases(result, input);
  applyGearFeedbackBiases(result, input, tractionAxis, shiftAxis);
  applyTrackFeedbackBiases(result, input, correctionMultiplier);
  applyDriftFeedbackBiases(result, input);
  applyOffroadFeedbackBiases(result, input);
}

function applyRoadTireWidthBiases(result, input) {
  if (!equalsIgnoreCase(input.useCase, "Road")) return;
  const axis = tireWidthBalanceAxis(input.frontTireWidthMm, input.rearTireWidthMm);
  if (axis === 0) return;
  const note = `Front/rear tire width split ${input.frontTireWidthMm}/${input.rearTireWidthMm} mm adjusts road brake and drivetrain load.`;
  const frontLimitDelta = clamp(axis, -1, 1.5);
  adjustBaselineGeneratedField(result, "frontDiffAccel", (value) => clamp(value - 1.5 * frontLimitDelta, 15, 35), note);
  adjustBaselineGeneratedField(result, "frontDiffDecel", (value) => clamp(value - 1.0 * frontLimitDelta, 0, 20), note);
  adjustBaselineGeneratedField(result, "centerDiffBalance", (value) => clamp(value + 2.5 * frontLimitDelta, 55, 82), note);
  adjustBaselineGeneratedField(result, "frontTirePressure", (value) => clamp(value - 0.02 * frontLimitDelta, 1.00, 4.00), note);
}

function applyGearFeedbackBiases(result, input, tractionAxis, shiftAxis) {
  if (!hasGeneratedGearing(result, input)) return;

  if (tractionAxis !== 0) {
    const note = `Traction bias ${input.tractionBias.toFixed(0)} adjusts launch and corner-exit gearing; differential compensation is intentionally small.`;
    scaleBaselineGeneratedField(result, "finalDrive", 1 + 0.035 * tractionAxis, note);
    scaleBaselineGeneratedField(result, "gear1", 1 + 0.060 * tractionAxis, note);
    scaleBaselineGeneratedField(result, "gear2", 1 + 0.045 * tractionAxis, note);
    scaleBaselineGeneratedField(result, "gear3", 1 + 0.025 * tractionAxis, note);
    const diffDelta = tractionAxis < 0 ? 2.0 * tractionAxis : 1.5 * tractionAxis;
    ["frontDiffAccel", "rearDiffAccel"].forEach((key) => {
      adjustBaselineGeneratedField(result, key, (value) => clamp(value + diffDelta, 0, 100), note);
    });
  }

  if (shiftAxis !== 0) {
    const note = `Shift bias ${input.shiftBias.toFixed(0)} adjusts intermediate gear spacing without changing final drive.`;
    const gearCount = input.gearCount || 0;
    const firstMiddle = 2;
    const lastMiddle = Math.max(firstMiddle, gearCount - 1);
    const midpoint = (firstMiddle + lastMiddle) / 2;
    const spread = Math.max(1, (lastMiddle - firstMiddle) / 2);
    for (let gear = firstMiddle; gear <= lastMiddle; gear += 1) {
      const centerWeight = clamp(1 - Math.abs(gear - midpoint) / spread * 0.35, 0.65, 1);
      scaleBaselineGeneratedField(result, `gear${gear}`, 1 + 0.050 * shiftAxis * centerWeight, note);
    }
  }
}

function hasGeneratedGearing(result, input) {
  if (!input || input.gearCount === null || input.gearCount === undefined) return false;
  if (typeof result.profileDraft.finalDrive !== "number") return false;
  return typeof result.profileDraft.gear1 === "number";
}

function applyTrackFeedbackBiases(result, input, correctionMultiplier) {
  if (!supportsTrackFeedbackUseCase(input.useCase)) return;
  const scene = normalizeTrackFeedbackScene(input.trackFeedbackScene);
  const symptom = normalizeTrackFeedbackSymptom(scene, input.trackFeedbackSymptom);
  if (!scene || !symptom) return;
  const strength = clamp(correctionMultiplier, 0.5, 1.5);
  const profile = trackFeedbackProfile(input.useCase);
  const note = `Track feedback ${scene}/${symptom} applies a ${input.correctionStrengthBias.toFixed(0)} strength secondary correction.${profile.note}`;
  const ratio = (value) => 1 + value * strength;
  const delta = (value) => value * strength;

  if (scene === "lowSpeedCorner") {
    switch (symptom) {
      case "entryUndersteer":
        scaleBaselineGeneratedField(result, "frontArb", ratio(-0.035 * profile.arb), note);
        scaleBaselineGeneratedField(result, "rearArb", ratio(0.025 * profile.arb), note);
        scaleBaselineGeneratedField(result, "frontSpring", ratio(-0.025 * profile.spring), note);
        scaleBaselineGeneratedField(result, "frontRebound", ratio(-0.045 * profile.damping), note);
        scaleBaselineGeneratedField(result, "frontBump", ratio(-0.035 * profile.damping), note);
        adjustBaselineGeneratedField(result, "frontCamber", (value) => value - delta(0.1 * profile.camber), note);
        adjustBaselineGeneratedField(result, "brakeBalance", (value) => clamp(value - delta(1.0 * profile.brake), 45, 65), note);
        reduceDecelLock(result, delta(1.0 * profile.diff), note);
        break;
      case "midUndersteer":
        scaleBaselineGeneratedField(result, "frontArb", ratio(-0.045 * profile.arb), note);
        scaleBaselineGeneratedField(result, "rearArb", ratio(0.035 * profile.arb), note);
        scaleBaselineGeneratedField(result, "frontSpring", ratio(-0.040 * profile.spring), note);
        scaleBaselineGeneratedField(result, "rearSpring", ratio(0.015 * profile.spring), note);
        scaleBaselineGeneratedField(result, "frontRebound", ratio(-0.030 * profile.damping), note);
        scaleBaselineGeneratedField(result, "frontBump", ratio(-0.035 * profile.damping), note);
        adjustBaselineGeneratedField(result, "frontCamber", (value) => value - delta(0.1 * profile.camber), note);
        reduceDecelLock(result, delta(1.0 * profile.diff), note);
        break;
      case "exitWheelspin":
        scaleBaselineGeneratedField(result, "finalDrive", ratio(-0.025 * profile.gear), note);
        scaleBaselineGeneratedField(result, "gear1", ratio(-0.030 * profile.gear), note);
        scaleBaselineGeneratedField(result, "gear2", ratio(-0.025 * profile.gear), note);
        reduceAccelLock(result, delta(3.0 * profile.diff), note);
        scaleBaselineGeneratedField(result, "rearBump", ratio(-0.025 * profile.damping), note);
        break;
      case "brakingInstability":
        adjustBaselineGeneratedField(result, "brakeBalance", (value) => clamp(value + delta(2.0 * profile.brake), 45, 65), note);
        reduceDecelLock(result, delta(2.0 * profile.diff), note);
        scaleBaselineGeneratedField(result, "rearRebound", ratio(-0.025 * profile.damping), note);
        scaleBaselineGeneratedField(result, "rearBump", ratio(-0.025 * profile.damping), note);
        break;
      default:
        break;
    }
    return;
  }

  if (scene === "highSpeedCorner") {
    switch (symptom) {
      case "highSpeedEntryInstability":
        scaleBaselineGeneratedField(result, "rearArb", ratio(-0.035 * profile.arb), note);
        scaleBaselineGeneratedField(result, "rearRebound", ratio(-0.035 * profile.damping), note);
        adjustBaselineGeneratedField(result, "brakeBalance", (value) => clamp(value + delta(1.0 * profile.brake), 45, 65), note);
        adjustTierRecommendation(result, "rearAero", profile.aeroTierDelta, note);
        break;
      case "midUndersteer":
        adjustBaselineGeneratedField(result, "frontCamber", (value) => value - delta(0.1 * profile.camber), note);
        scaleBaselineGeneratedField(result, "frontArb", ratio(-0.025 * profile.arb), note);
        scaleBaselineGeneratedField(result, "rearArb", ratio(0.020 * profile.arb), note);
        scaleBaselineGeneratedField(result, "frontSpring", ratio(-0.010 * profile.spring), note);
        scaleBaselineGeneratedField(result, "frontRebound", ratio(-0.015 * profile.damping), note);
        scaleBaselineGeneratedField(result, "frontBump", ratio(-0.015 * profile.damping), note);
        adjustTierRecommendation(result, "frontAero", profile.aeroTierDelta, note);
        break;
      case "highSpeedOversteer":
        scaleBaselineGeneratedField(result, "rearArb", ratio(-0.045 * profile.arb), note);
        scaleBaselineGeneratedField(result, "rearRebound", ratio(-0.035 * profile.damping), note);
        scaleBaselineGeneratedField(result, "rearBump", ratio(-0.030 * profile.damping), note);
        adjustTierRecommendation(result, "rearAero", profile.aeroTierDelta, note);
        break;
      case "bodyBounce":
        ["frontBump", "rearBump", "frontRebound", "rearRebound"].forEach((key) => {
          scaleBaselineGeneratedField(result, key, ratio(-0.050 * profile.damping), note);
        });
        ["frontArb", "rearArb"].forEach((key) => {
          scaleBaselineGeneratedField(result, key, ratio(-0.030 * profile.arb), note);
        });
        adjustTierRecommendation(result, "frontRideHeight", 1, note);
        adjustTierRecommendation(result, "rearRideHeight", 1, note);
        break;
      default:
        break;
    }
  }
}

function trackFeedbackProfile(useCase) {
  if (equalsIgnoreCase(useCase, "Rally")) {
    return {
      arb: 0.75,
      spring: 0.65,
      damping: 1.15,
      camber: 0.6,
      brake: 0.85,
      diff: 1.2,
      gear: 1.1,
      aeroTierDelta: 0,
      note: " Rally feedback is scaled toward loose-surface damping, traction, and differential changes instead of road aero and stiff roll support.",
    };
  }
  return {
    arb: 1,
    spring: 1,
    damping: 1,
    camber: 1,
    brake: 1,
    diff: 1,
    gear: 1,
    aeroTierDelta: 1,
    note: "",
  };
}

function applyDriftFeedbackBiases(result, input) {
  if (!equalsIgnoreCase(input.useCase, "Drift")) return;
  const symptom = normalizeDriftFeedbackSymptom(input.driftFeedbackSymptom);
  if (!symptom) return;
  const strength = clamp(normalizeBaselineBias(input.driftCorrectionStrengthBias) / 100, 0.5, 1.5);
  const note = `Drift feedback ${symptom} applies a ${input.driftCorrectionStrengthBias.toFixed(0)} strength secondary correction.`;
  const ratio = (value) => 1 + value * strength;
  const delta = (value) => value * strength;

  switch (symptom) {
    case "initiationDifficult":
      scaleBaselineGeneratedField(result, "frontArb", ratio(0.035), note);
      adjustBaselineGeneratedField(result, "frontToe", (value) => value + delta(0.1), note);
      adjustBaselineGeneratedField(result, "rearTirePressure", (value) => value + delta(0.03), note);
      adjustBaselineGeneratedField(result, "rearDiffAccel", (value) => clamp(value + delta(2), 95, 100), note);
      applyDriftGearFeedback(result, input, ratio(0.025), note);
      break;
    case "initiationTooSensitive":
      scaleBaselineGeneratedField(result, "rearArb", ratio(-0.040), note);
      scaleBaselineGeneratedField(result, "rearRebound", ratio(-0.035), note);
      scaleBaselineGeneratedField(result, "rearBump", ratio(-0.035), note);
      adjustBaselineGeneratedField(result, "rearTirePressure", (value) => value - delta(0.04), note);
      adjustBaselineGeneratedField(result, "rearDiffAccel", (value) => clamp(value - delta(3), 95, 100), note);
      applyDriftGearFeedback(result, input, ratio(-0.025), note);
      break;
    case "angleTooSmall":
      adjustBaselineGeneratedField(result, "frontCamber", (value) => value - delta(0.15), note);
      adjustBaselineGeneratedField(result, "frontToe", (value) => value + delta(0.1), note);
      adjustBaselineGeneratedField(result, "rearTirePressure", (value) => value + delta(0.04), note);
      scaleBaselineGeneratedField(result, "frontArb", ratio(0.030), note);
      scaleBaselineGeneratedField(result, "rearArb", ratio(-0.020), note);
      applyDriftGearFeedback(result, input, ratio(0.020), note);
      break;
    case "angleTooLarge":
      adjustBaselineGeneratedField(result, "frontToe", (value) => value - delta(0.1), note);
      adjustBaselineGeneratedField(result, "rearTirePressure", (value) => value - delta(0.04), note);
      scaleBaselineGeneratedField(result, "rearArb", ratio(-0.040), note);
      scaleBaselineGeneratedField(result, "rearRebound", ratio(-0.030), note);
      adjustBaselineGeneratedField(result, "rearDiffDecel", (value) => clamp(value - delta(3), 90, 100), note);
      applyDriftGearFeedback(result, input, ratio(-0.020), note);
      break;
    case "rearWheelspin":
      adjustBaselineGeneratedField(result, "rearTirePressure", (value) => value - delta(0.06), note);
      scaleBaselineGeneratedField(result, "rearRebound", ratio(-0.040), note);
      scaleBaselineGeneratedField(result, "rearBump", ratio(-0.040), note);
      adjustBaselineGeneratedField(result, "rearDiffAccel", (value) => clamp(value - delta(6), 90, 100), note);
      applyDriftGearFeedback(result, input, ratio(-0.040), note);
      break;
    case "rearGripTooStrong":
      adjustBaselineGeneratedField(result, "rearTirePressure", (value) => value + delta(0.06), note);
      scaleBaselineGeneratedField(result, "rearArb", ratio(0.040), note);
      adjustBaselineGeneratedField(result, "rearDiffAccel", (value) => clamp(value + delta(4), 95, 100), note);
      applyDriftGearFeedback(result, input, ratio(0.035), note);
      break;
    default:
      break;
  }
}

function applyDriftGearFeedback(result, input, gearRatio, note) {
  if (!hasGeneratedGearing(result, input)) return;
  scaleBaselineGeneratedField(result, "finalDrive", gearRatio, note);
  const coreGear = driftCoreGear(input.gearCount || 0);
  const lowGear = Math.max(1, coreGear - 1);
  const highGear = Math.min(input.gearCount || coreGear, coreGear + 1);
  for (let gear = lowGear; gear <= highGear; gear += 1) {
    scaleBaselineGeneratedField(result, `gear${gear}`, gearRatio, note);
  }
}

function applyOffroadFeedbackBiases(result, input) {
  if (!equalsIgnoreCase(input.useCase, "Offroad")) return;
  const symptom = normalizeOffroadFeedbackSymptom(input.offroadFeedbackSymptom);
  if (!symptom) return;
  const strength = clamp(normalizeBaselineBias(input.offroadCorrectionStrengthBias) / 100, 0.5, 1.5);
  const note = `Offroad feedback ${symptom} applies a ${input.offroadCorrectionStrengthBias.toFixed(0)} strength secondary correction.`;
  const ratio = (value) => 1 + value * strength;
  const delta = (value) => value * strength;

  switch (symptom) {
    case "bumpKick":
      adjustOffroadTirePressure(result, -delta(0.05), note);
      ["frontArb", "rearArb"].forEach((key) => scaleBaselineGeneratedField(result, key, ratio(-0.055), note));
      ["frontBump", "rearBump", "frontRebound", "rearRebound"].forEach((key) => {
        scaleBaselineGeneratedField(result, key, ratio(-0.060), note);
      });
      adjustOffroadRideHeight(result, 1, note);
      break;
    case "bottomingOut":
      adjustOffroadRideHeight(result, offroadTierDelta(strength, true), note);
      ["frontSpring", "rearSpring"].forEach((key) => scaleBaselineGeneratedField(result, key, ratio(0.055), note));
      ["frontBump", "rearBump"].forEach((key) => scaleBaselineGeneratedField(result, key, ratio(0.060), note));
      break;
    case "landingUnstable":
      scaleBaselineGeneratedField(result, "rearRebound", ratio(0.055), note);
      scaleBaselineGeneratedField(result, "rearBump", ratio(0.045), note);
      scaleBaselineGeneratedField(result, "rearArb", ratio(-0.045), note);
      adjustBaselineGeneratedField(result, "brakeBalance", (value) => clamp(value + delta(1.0), 45, 65), note);
      reduceAccelLock(result, delta(2.0), note);
      adjustBaselineGeneratedField(result, "centerDiffBalance", (value) => clamp(value - delta(2.0), 35, 80), note);
      break;
    case "lazyTurnIn":
      scaleBaselineGeneratedField(result, "frontArb", ratio(-0.040), note);
      scaleBaselineGeneratedField(result, "rearArb", ratio(0.035), note);
      adjustBaselineGeneratedField(result, "frontCamber", (value) => value - delta(0.1), note);
      reduceDecelLock(result, delta(1.5), note);
      adjustBaselineGeneratedField(result, "centerDiffBalance", (value) => clamp(value + delta(2.0), 35, 80), note);
      break;
    case "exitWheelspin":
      adjustOffroadTirePressure(result, -delta(0.04), note);
      reduceAccelLock(result, delta(3.0), note);
      adjustBaselineGeneratedField(result, "centerDiffBalance", (value) => clamp(value - delta(2.0), 35, 80), note);
      applyOffroadGearFeedback(result, input, ratio(-0.035), note);
      break;
    case "highSpeedFloat":
      ["frontArb", "rearArb"].forEach((key) => scaleBaselineGeneratedField(result, key, ratio(0.035), note));
      ["frontRebound", "rearRebound"].forEach((key) => scaleBaselineGeneratedField(result, key, ratio(0.045), note));
      applyOffroadGearFeedback(result, input, ratio(-0.030), note);
      break;
    default:
      break;
  }
}

function adjustOffroadTirePressure(result, delta, note) {
  adjustBaselineGeneratedField(result, "frontTirePressure", (value) => value + delta, note);
  adjustBaselineGeneratedField(result, "rearTirePressure", (value) => value + delta, note);
}

function adjustOffroadRideHeight(result, delta, note) {
  adjustTierRecommendation(result, "frontRideHeight", delta, note);
  adjustTierRecommendation(result, "rearRideHeight", delta, note);
}

function offroadTierDelta(strength, strong) {
  if (strong && strength >= 1.25) return 2;
  return 1;
}

function applyOffroadGearFeedback(result, input, gearRatio, note) {
  if (!hasGeneratedGearing(result, input)) return;
  scaleBaselineGeneratedField(result, "finalDrive", gearRatio, note);
  scaleBaselineGeneratedField(result, "gear1", gearRatio, note);
  scaleBaselineGeneratedField(result, "gear2", gearRatio, note);
  scaleBaselineGeneratedField(result, "gear3", gearRatio, note);
}

function reduceAccelLock(result, amount, note) {
  ["frontDiffAccel", "rearDiffAccel"].forEach((key) => {
    adjustBaselineGeneratedField(result, key, (value) => clamp(value - amount, 0, 100), note);
  });
}

function reduceDecelLock(result, amount, note) {
  ["frontDiffDecel", "rearDiffDecel"].forEach((key) => {
    adjustBaselineGeneratedField(result, key, (value) => clamp(value - amount, 0, 100), note);
  });
}

function adjustTierRecommendation(result, fieldKey, delta, note) {
  const item = result.tierRecommendations.find((candidate) => candidate.fieldKey === fieldKey);
  if (!item) return;
  const tier = shiftTier(item.tier, delta);
  if (tier === item.tier) return;
  item.tier = tier;
  item.reason = appendBaselineBiasReason(item.reason, note);
}

function shiftTier(tier, delta) {
  const tiers = ["lowest", "low", "medium", "high", "highest"];
  const index = tiers.indexOf(tier);
  if (index < 0) return tier;
  return tiers[clamp(index + delta, 0, tiers.length - 1)];
}

function baselineBiasAxis(value) {
  return clamp((normalizeBaselineBias(value) - 100) / 50, -1, 1);
}

function scaleBaselineGeneratedField(result, key, ratio, note) {
  adjustBaselineGeneratedField(result, key, (value) => value * ratio, note);
}

function adjustBaselineGeneratedField(result, key, transform, note) {
  const current = result.profileDraft[key];
  if (current === null || current === undefined) return;
  setProfileField(result.profileDraft, key, transform(current));
  const updated = result.profileDraft[key];
  const field = result.generatedFields.find((item) => item.fieldKey === key);
  if (field) {
    field.value = updated;
    field.reason = appendBaselineBiasReason(field.reason, note);
  }
}

function appendBaselineBiasReason(reason, note) {
  if (!note) return reason;
  if (reason.includes(note)) return reason;
  return `${reason} ${note}`.trim();
}

function baselineGearing(input) {
  if (input.redlineRPM === null || input.gearCount === null || input.tireDiameterCm === null || input.targetTopSpeedKmh === null) {
    return {
      fields: [],
      reason: "missing_gear_input",
      message: "Static gearing needs redline RPM, gear count, tire size, and target top speed.",
    };
  }
  const redline = input.redlineRPM;
  const gearCount = input.gearCount;
  const tireDiameterCm = input.tireDiameterCm;
  const targetTopSpeedKmh = input.targetTopSpeedKmh;
  if (redline < 1000 || redline > 20000) {
    return { fields: [], reason: "invalid_gear_input", message: "Redline RPM should be between 1000 and 20000." };
  }
  if (gearCount < 2 || gearCount > 10) {
    return { fields: [], reason: "invalid_gear_input", message: "Gear count should be between 2 and 10." };
  }
  if (tireDiameterCm < 40 || tireDiameterCm > 120) {
    return { fields: [], reason: "invalid_gear_input", message: "Tire size should produce a diameter between 40 cm and 120 cm." };
  }
  if (targetTopSpeedKmh <= 0 || targetTopSpeedKmh > 600) {
    return { fields: [], reason: "invalid_gear_input", message: "Target top speed should be between 1 km/h and 600 km/h." };
  }

  const circumferenceMeters = Math.PI * tireDiameterCm / 100;
  const targetMetersPerMinute = targetTopSpeedKmh * 1000 / 60;
  const wheelRPMAtTarget = targetMetersPerMinute / circumferenceMeters;
  if (wheelRPMAtTarget <= 0) {
    return { fields: [], reason: "invalid_gear_input", message: "Target speed and tire size do not produce a valid wheel speed." };
  }

  if (equalsIgnoreCase(input.useCase, "Drift")) {
    return baselineDriftGearing(redline, gearCount, targetTopSpeedKmh, wheelRPMAtTarget);
  }
  if (equalsIgnoreCase(input.useCase, "Drag")) {
    return baselineDragGearing(redline, gearCount, wheelRPMAtTarget);
  }

  const topTotalRatio = redline / wheelRPMAtTarget;
  const finalDrive = clamp(roundTunePlanStep(topTotalRatio / 0.82, 0.01), 2.20, 5.50);
  const topGear = clamp(roundTunePlanStep(topTotalRatio / finalDrive, 0.01), 0.45, 6.00);
  const gears = [];
  gears[gearCount] = topGear;
  for (let gear = gearCount - 1; gear >= 1; gear -= 1) {
    gears[gear] = gears[gear + 1] / roadGearRetention(gearCount, gear);
  }
  const fields = [{
    key: "finalDrive",
    value: finalDrive,
    reason: "Balanced road final drive from target top speed, redline RPM, and tire size.",
  }];
  for (let gear = 1; gear <= gearCount; gear += 1) {
    fields.push({
      key: `gear${gear}`,
      value: clamp(roundTunePlanStep(gears[gear], 0.01), 0.45, 6.00),
      reason: "Segmented road static gear spread with wider low gears and progressively tighter high gears; verify with telemetry after the first test.",
    });
  }
  return { fields, reason: "", message: "" };
}

function baselineDragGearing(redline, gearCount, wheelRPMAtTarget) {
  const topTotalRatio = redline / wheelRPMAtTarget;
  const finalDrive = clamp(roundTunePlanStep(topTotalRatio / 0.78, 0.01), 2.20, 5.50);
  const topGear = clamp(roundTunePlanStep(topTotalRatio / finalDrive, 0.01), 0.45, 6.00);
  const gears = [];
  gears[gearCount] = topGear;
  for (let gear = gearCount - 1; gear >= 1; gear -= 1) {
    gears[gear] = gears[gear + 1] / dragGearRetention(gearCount, gear);
  }
  const fields = [{
    key: "finalDrive",
    value: finalDrive,
    reason: "Drag final drive baseline targets trap speed near redline in top gear.",
  }];
  for (let gear = 1; gear <= gearCount; gear += 1) {
    fields.push({
      key: `gear${gear}`,
      value: clamp(roundTunePlanStep(gears[gear], 0.01), 0.45, 6.00),
      reason: "Drag static gear spread uses wider launch gears and tighter upper gears; verify against shift RPM after test runs.",
    });
  }
  return { fields, reason: "", message: "" };
}

function dragGearRetention(gearCount, shiftIndex) {
  if (gearCount <= 2) return 0.80;
  const t = clamp((shiftIndex - 1) / Math.max(1, gearCount - 2), 0, 1);
  const smooth = t * t * (3 - 2 * t);
  return 0.68 + (0.88 - 0.68) * smooth;
}

function baselineDriftGearing(redline, gearCount, targetDriftSpeedKmh, wheelRPMAtTarget) {
  if (targetDriftSpeedKmh < 20 || targetDriftSpeedKmh > 260) {
    return { fields: [], reason: "invalid_gear_input", message: "Target drift speed should be between 20 km/h and 260 km/h." };
  }
  const coreGear = driftCoreGear(gearCount);
  const coreTotalRatio = redline * 0.88 / wheelRPMAtTarget;
  const finalDrive = clamp(roundTunePlanStep(coreTotalRatio / driftDesiredCoreGear(coreGear), 0.01), 2.20, 5.50);
  const coreRatio = clamp(roundTunePlanStep(coreTotalRatio / finalDrive, 0.01), 0.45, 6.00);
  const gears = [];
  gears[coreGear] = coreRatio;
  for (let gear = coreGear - 1; gear >= 1; gear -= 1) {
    gears[gear] = gears[gear + 1] / driftLowerGearRetention(gear);
  }
  for (let gear = coreGear + 1; gear <= gearCount; gear += 1) {
    gears[gear] = gears[gear - 1] * driftUpperGearRetention(gear - 1, coreGear);
  }
  const fields = [{
    key: "finalDrive",
    value: finalDrive,
    reason: `Drift final drive targets about 88% redline in gear ${coreGear} at the selected drift speed.`,
  }];
  for (let gear = 1; gear <= gearCount; gear += 1) {
    fields.push({
      key: `gear${gear}`,
      value: clamp(roundTunePlanStep(gears[gear], 0.01), 0.45, 6.00),
      reason: `Drift static gearing centers gear ${coreGear} around high RPM at ${targetDriftSpeedKmh.toFixed(0)} km/h; lower gears are shorter for initiation and upper gears are transition gears.`,
    });
  }
  return { fields, reason: "", message: "" };
}

function driftCoreGear(gearCount) {
  if (gearCount <= 4) return 2;
  if (gearCount <= 6) return 3;
  return 4;
}

function driftDesiredCoreGear(coreGear) {
  if (coreGear === 2) return 2.05;
  if (coreGear === 3) return 1.65;
  return 1.35;
}

function driftLowerGearRetention(shiftIndex) {
  if (shiftIndex === 1) return 0.68;
  if (shiftIndex === 2) return 0.72;
  if (shiftIndex === 3) return 0.76;
  return 0.78;
}

function driftUpperGearRetention(shiftIndex, coreGear) {
  switch (shiftIndex - coreGear) {
    case 0:
      return 0.82;
    case 1:
      return 0.86;
    case 2:
      return 0.89;
    case 3:
      return 0.91;
    default:
      return 0.93;
  }
}

function roadGearRetention(gearCount, shiftIndex) {
  if (gearCount <= 2) return 0.78;
  const extra = clamp(gearCount - 5, 0, 5);
  const low = 0.70 + 0.01 * extra;
  const high = 0.84 + 0.016 * extra;
  const t = clamp((shiftIndex - 1) / (gearCount - 2), 0, 1);
  const smooth = t * t * (3 - 2 * t);
  return low + (high - low) * smooth;
}

function tunePlanFieldUnit(key) {
  if (["frontTirePressure", "rearTirePressure"].includes(key)) return "BAR";
  if (["frontCamber", "rearCamber", "frontToe", "rearToe", "caster"].includes(key)) return "deg";
  if (["frontSpring", "rearSpring"].includes(key)) return "kgf/mm";
  if (["frontRideHeight", "rearRideHeight"].includes(key)) return "cm";
  if (["frontAero", "rearAero"].includes(key)) return "kgf";
  if (["brakeBalance", "brakePressure", "frontDiffAccel", "frontDiffDecel", "rearDiffAccel", "rearDiffDecel", "centerDiffBalance"].includes(key)) return "%";
  return "";
}

function tunePlanFieldStep(key) {
  if (["finalDrive", "gear1", "gear2", "gear3", "gear4", "gear5", "gear6", "gear7", "gear8", "gear9", "gear10"].includes(key)) return 0.01;
  if (["frontTirePressure", "rearTirePressure"].includes(key)) return 0.01;
  if (["frontArb", "rearArb"].includes(key)) return 0.1;
  if (["frontAero", "rearAero", "brakeBalance", "brakePressure", "frontDiffAccel", "frontDiffDecel", "rearDiffAccel", "rearDiffDecel", "centerDiffBalance"].includes(key)) return 1;
  return 0.1;
}

function setProfileField(profile, key, value) {
  const stepped = roundTunePlanStep(value, tunePlanFieldStep(key));
  profile[key] = clampTunePlanFieldValue(key, stepped);
}

function clampTunePlanFieldValue(key, value) {
  if (typeof value !== "number" || !Number.isFinite(value)) return value;
  if (key === "finalDrive") return clamp(value, 2.20, 5.50);
  if (/^gear\d+$/.test(key)) return clamp(value, 0.45, 6.00);
  if (["frontRebound", "rearRebound", "frontBump", "rearBump"].includes(key)) return clamp(value, 1, 20);
  if (["frontArb", "rearArb"].includes(key)) return clamp(value, 1, 65);
  if (["frontSpring", "rearSpring"].includes(key)) return clamp(value, 0, 999);
  if (["frontTirePressure", "rearTirePressure"].includes(key)) return clamp(value, 1.00, 4.00);
  if (["frontCamber", "rearCamber"].includes(key)) return clamp(value, -5.0, 0);
  if (["frontToe", "rearToe"].includes(key)) return clamp(value, -5.0, 5.0);
  if (key === "caster") return clamp(value, 1.0, 7.0);
  if (["brakeBalance", "frontDiffAccel", "frontDiffDecel", "rearDiffAccel", "rearDiffDecel", "centerDiffBalance"].includes(key)) {
    return clamp(value, 0, 100);
  }
  if (key === "brakePressure") return clamp(value, 0, 200);
  return value;
}

function normalizeTuneProfilePower(profile) {
  const out = { ...profile };
  out.powerKW = positiveNumberOrNull(out.powerKW);
  out.torqueNM = positiveNumberOrNull(out.torqueNM);
  out.weightKG = positiveNumberOrNull(out.weightKG);
  out.frontWeightPct = boundedNumberOrNull(out.frontWeightPct, 0, 100);
  out.redlineRPM = positiveNumberOrNull(out.redlineRPM);
  if (out.powerKW !== null && out.weightKG !== null && out.powerKW > 0 && out.weightKG > 0) {
    out.powerToWeightKWPerKG = Math.round((out.powerKW / out.weightKG) * 10000) / 10000;
  } else {
    out.powerToWeightKWPerKG = null;
  }
  return out;
}

function positiveNumberOrNull(value) {
  return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : null;
}

function boundedNumberOrNull(value, min, max) {
  if (typeof value !== "number" || !Number.isFinite(value) || value < min || value > max) return null;
  return value;
}

function requiredInteger(value, label) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || !isWholeNumber(parsed)) {
    throw new Error(`${label} is required and must be an integer`);
  }
  return parsed;
}

function optionalInteger(value) {
  if (value === null || value === undefined || value === "") return null;
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || !isWholeNumber(parsed)) {
    throw new Error("optional integer field must be a valid integer");
  }
  return parsed;
}

function optionalNumber(value) {
  if (value === null || value === undefined || value === "") return null;
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    throw new Error("optional numeric field must be a valid number");
  }
  return parsed;
}

function stringValue(value) {
  return value === null || value === undefined ? "" : String(value).trim();
}

function equalsIgnoreCase(a, b) {
  return stringValue(a).toLowerCase() === stringValue(b).toLowerCase();
}

function isWholeNumber(value) {
  return Math.abs(value - Math.round(value)) < 1e-9;
}

function roundTunePlanStep(value, step) {
  if (step <= 0) return value;
  let decimals = 2;
  if (step >= 1) decimals = 0;
  else if (step >= 0.1) decimals = 1;
  const factor = 10 ** decimals;
  return Math.round(Math.round(value / step) * step * factor) / factor;
}

function clamp(value, min, max) {
  if (value < min) return min;
  if (value > max) return max;
  return value;
}

function lerp(a, b, t) {
  return a + (b - a) * t;
}
