package storage

import (
	"errors"
	"fmt"
	"math"
	"sort"
	"strings"
)

type RoadStaticTuneBaselineInput struct {
	CarName           string   `json:"carName"`
	VersionName       string   `json:"versionName"`
	UseCase           string   `json:"useCase,omitempty"`
	CarOrdinal        *int64   `json:"carOrdinal,omitempty"`
	CarCategory       *int64   `json:"carCategory,omitempty"`
	PI                int64    `json:"pi"`
	Drivetrain        string   `json:"drivetrain"`
	TireCompound      string   `json:"tireCompound,omitempty"`
	WeightKG          float64  `json:"weightKG"`
	FrontWeightPct    float64  `json:"frontWeightPct"`
	PowerKW           *float64 `json:"powerKW,omitempty"`
	TorqueNM          *float64 `json:"torqueNM,omitempty"`
	RedlineRPM        *float64 `json:"redlineRPM,omitempty"`
	GearCount         *int64   `json:"gearCount,omitempty"`
	TireDiameterCm    *float64 `json:"tireDiameterCm,omitempty"`
	TargetTopSpeedKmh *float64 `json:"targetTopSpeedKmh,omitempty"`

	FrontRideHeightMinCm *float64 `json:"frontRideHeightMinCm,omitempty"`
	FrontRideHeightMaxCm *float64 `json:"frontRideHeightMaxCm,omitempty"`
	RearRideHeightMinCm  *float64 `json:"rearRideHeightMinCm,omitempty"`
	RearRideHeightMaxCm  *float64 `json:"rearRideHeightMaxCm,omitempty"`

	FrontAeroMinKgf *float64 `json:"frontAeroMinKgf,omitempty"`
	FrontAeroMaxKgf *float64 `json:"frontAeroMaxKgf,omitempty"`
	RearAeroMinKgf  *float64 `json:"rearAeroMinKgf,omitempty"`
	RearAeroMaxKgf  *float64 `json:"rearAeroMaxKgf,omitempty"`

	FrontRideHeightAdjustable bool `json:"frontRideHeightAdjustable,omitempty"`
	RearRideHeightAdjustable  bool `json:"rearRideHeightAdjustable,omitempty"`
	FrontAeroAdjustable       bool `json:"frontAeroAdjustable,omitempty"`
	RearAeroAdjustable        bool `json:"rearAeroAdjustable,omitempty"`

	BalanceBias   float64 `json:"balanceBias,omitempty"`
	StiffnessBias float64 `json:"stiffnessBias,omitempty"`
	SpeedBias     float64 `json:"speedBias,omitempty"`
}

type BaselineGeneratedField struct {
	FieldKey        string   `json:"fieldKey"`
	Group           string   `json:"group"`
	Value           *float64 `json:"value,omitempty"`
	Unit            string   `json:"unit"`
	Reason          string   `json:"reason"`
	DefaultSelected bool     `json:"defaultSelected"`
}

type BaselineSkippedField struct {
	FieldKey string `json:"fieldKey"`
	Group    string `json:"group"`
	Reason   string `json:"reason"`
	Message  string `json:"message"`
}

type BaselineTierRecommendation struct {
	FieldKey   string `json:"fieldKey"`
	Group      string `json:"group"`
	Tier       string `json:"tier"`
	Reason     string `json:"reason"`
	Applicable bool   `json:"applicable"`
}

type RoadStaticTuneBaselineResult struct {
	ProfileDraft        TuneProfileInput             `json:"profileDraft"`
	Confidence          string                       `json:"confidence"`
	GeneratedFields     []BaselineGeneratedField     `json:"generatedFields"`
	TierRecommendations []BaselineTierRecommendation `json:"tierRecommendations"`
	SkippedFields       []BaselineSkippedField       `json:"skippedFields"`
	Warnings            []string                     `json:"warnings"`
	NextTestPlan        []string                     `json:"nextTestPlan"`
}

type RoadStaticTuneBaselineApplyInput struct {
	CreateNew         bool                        `json:"createNew"`
	TargetProfileID   int64                       `json:"targetProfileId"`
	BaselineInput     RoadStaticTuneBaselineInput `json:"baselineInput"`
	SelectedFieldKeys []string                    `json:"selectedFieldKeys"`
}

type RoadStaticTuneBaselineApplyResult struct {
	Profile       TuneProfile            `json:"profile"`
	AppliedFields []string               `json:"appliedFields"`
	SkippedFields []BaselineSkippedField `json:"skippedFields"`
}

func GenerateRoadStaticTuneBaseline(input RoadStaticTuneBaselineInput) (*RoadStaticTuneBaselineResult, error) {
	normalized, err := normalizeRoadStaticBaselineInput(input)
	if err != nil {
		return nil, err
	}

	carClass := classFromPI(normalized.PI)
	useCase := normalized.UseCase
	pi := normalized.PI
	weight := normalized.WeightKG
	frontWeight := normalized.FrontWeightPct
	versionName := strings.TrimSpace(normalized.VersionName)
	if versionName == "" {
		versionName = baselineDefaultVersionName(useCase)
	}

	draft := TuneProfileInput{
		CarName:        strings.TrimSpace(normalized.CarName),
		CarOrdinal:     normalized.CarOrdinal,
		CarCategory:    normalized.CarCategory,
		CarClass:       carClass,
		PI:             &pi,
		Drivetrain:     normalized.Drivetrain,
		UseCase:        useCase,
		VersionName:    versionName,
		WeightKG:       &weight,
		FrontWeightPct: &frontWeight,
		PowerKW:        normalized.PowerKW,
		TorqueNM:       normalized.TorqueNM,
		RedlineRPM:     normalized.RedlineRPM,
		Notes:          fmt.Sprintf("Generated by %s Static Baseline.", useCase),
	}
	draft = normalizeTuneProfilePower(draft)

	result := &RoadStaticTuneBaselineResult{
		ProfileDraft: draft,
		Confidence:   "high",
		Warnings: []string{
			"Baseline values use Forza in-game slider/display units, not real-world engineering units.",
		},
		NextTestPlan: []string{
			baselineNextTestPlanIntro(useCase),
			"Watch tire temperature, slip balance, brake stability, and platform bottoming first.",
			"Use gear/power diagnostics later for gearing instead of static guesses.",
		},
	}

	add := func(key string, group string, value float64, reason string) {
		setTuneProfileInputFloat(&result.ProfileDraft, key, value)
		current, _ := getTuneProfileInputFloat(result.ProfileDraft, key)
		result.GeneratedFields = append(result.GeneratedFields, BaselineGeneratedField{
			FieldKey:        key,
			Group:           group,
			Value:           current,
			Unit:            tunePlanFieldUnit(key),
			Reason:          reason,
			DefaultSelected: true,
		})
	}
	addMeta := func(key string, group string, value *float64, unit string, reason string) {
		if value == nil {
			return
		}
		result.GeneratedFields = append(result.GeneratedFields, BaselineGeneratedField{
			FieldKey:        key,
			Group:           group,
			Value:           value,
			Unit:            unit,
			Reason:          reason,
			DefaultSelected: true,
		})
	}
	skip := func(key string, group string, reason string, message string) {
		result.SkippedFields = append(result.SkippedFields, BaselineSkippedField{
			FieldKey: key,
			Group:    group,
			Reason:   reason,
			Message:  message,
		})
	}
	addTier := func(key string, group string, tier string, applicable bool, reason string) {
		result.TierRecommendations = append(result.TierRecommendations, BaselineTierRecommendation{
			FieldKey:   key,
			Group:      group,
			Tier:       tier,
			Reason:     reason,
			Applicable: applicable,
		})
		if !applicable {
			skip(key, group, "not_confirmed_adjustable", "Confirm this tuning item is unlocked before using the tier recommendation.")
		}
	}

	addMeta("weightKG", "power", result.ProfileDraft.WeightKG, "kg", "Required baseline input.")
	addMeta("frontWeightPct", "power", result.ProfileDraft.FrontWeightPct, "%", "Required baseline input.")
	addMeta("powerKW", "power", result.ProfileDraft.PowerKW, "kW", "Optional profile context.")
	addMeta("torqueNM", "power", result.ProfileDraft.TorqueNM, "Nm", "Optional profile context.")
	addMeta("redlineRPM", "power", result.ProfileDraft.RedlineRPM, "rpm", "Static gearing input and power-band context.")

	frontTirePressure, rearTirePressure := baselineTirePressures(useCase, normalized.Drivetrain, normalized.TireCompound, normalized.WeightKG)
	add("frontTirePressure", "tire", frontTirePressure, baselineReason(useCase, "cold-pressure baseline in BAR from tire compound, vehicle weight, and drivetrain split."))
	add("rearTirePressure", "tire", rearTirePressure, baselineReason(useCase, "cold-pressure baseline in BAR from tire compound, vehicle weight, and drivetrain split."))
	alignment := baselineAlignment(useCase, carClass, normalized.Drivetrain, normalized.FrontWeightPct, normalized.BalanceBias)
	add("frontCamber", "alignment", alignment.frontCamber, baselineReason(useCase, "alignment baseline from PI class, front weight distribution, drivetrain, and balance bias."))
	add("rearCamber", "alignment", alignment.rearCamber, baselineReason(useCase, "alignment baseline from PI class, front weight distribution, drivetrain, and balance bias."))
	add("frontToe", "alignment", alignment.frontToe, baselineReason(useCase, "toe baseline; only strong balance bias moves Road away from neutral, while Drift uses fixed steering response."))
	add("rearToe", "alignment", alignment.rearToe, baselineReason(useCase, "toe baseline; only strong balance bias moves Road away from neutral, while Drift uses fixed steering response."))
	add("caster", "alignment", alignment.caster, baselineReason(useCase, "caster baseline from PI class, front weight distribution, and drivetrain."))

	springFactor := springFactorForBaseline(useCase, carClass)
	frontSpring, rearSpring := baselineSprings(useCase, normalized.Drivetrain, normalized.WeightKG, normalized.FrontWeightPct, springFactor)
	add("frontSpring", "springs", frontSpring, "FH6 kgf/mm menu value calculated from vehicle weight, axle weight distribution, and PI spring factor.")
	add("rearSpring", "springs", rearSpring, "FH6 kgf/mm menu value calculated from vehicle weight, axle weight distribution, and PI spring factor.")

	frontARB, rearARB := baselineARB(useCase, normalized.FrontWeightPct, carClass, normalized.Drivetrain)
	add("frontArb", "antiroll", frontARB, baselineReason(useCase, "lateral load-transfer baseline."))
	add("rearArb", "antiroll", rearARB, baselineReason(useCase, "lateral load-transfer baseline."))

	frontRebound, rearRebound, frontBump, rearBump := baselineDamping(useCase, normalized.WeightKG, normalized.FrontWeightPct, carClass, springFactor, frontSpring, rearSpring)
	add("frontRebound", "damping", frontRebound, baselineReason(useCase, "damping slider baseline from front axle weight, PI/use-case minimum bump, spring-factor multiplier, and bump/rebound ratio."))
	add("rearRebound", "damping", rearRebound, baselineReason(useCase, "rear damping slider baseline offset from front rebound by front/rear spring display difference."))
	add("frontBump", "damping", frontBump, baselineReason(useCase, "bump slider baseline from front axle weight, PI/use-case minimum bump, and spring-factor multiplier."))
	add("rearBump", "damping", rearBump, baselineReason(useCase, "rear bump slider baseline offset from front bump by front/rear spring display difference."))

	rideTier, rideReason := baselineRideHeightTier(useCase)
	aeroTier, aeroReason := baselineAeroTier(useCase)
	addTier("frontRideHeight", "springs", rideTier, normalized.FrontRideHeightAdjustable, rideReason)
	addTier("rearRideHeight", "springs", rideTier, normalized.RearRideHeightAdjustable, rideReason)
	addTier("frontAero", "aero", aeroTier, normalized.FrontAeroAdjustable, aeroReason)
	addTier("rearAero", "aero", aeroTier, normalized.RearAeroAdjustable, aeroReason)

	add("brakeBalance", "brake", baselineBrakeBalance(useCase, normalized.Drivetrain), baselineReason(useCase, "brake-balance baseline by use case and drivetrain."))
	add("brakePressure", "brake", baselineBrakePressure(useCase), baselineReason(useCase, "brake-pressure baseline by use case."))
	appendDifferentialBaseline(result, useCase, carClass, normalized.Drivetrain, normalized.WeightKG, normalized.FrontWeightPct, normalized.BalanceBias, add, skip)

	if gearValues, reason, message := baselineGearing(normalized); len(gearValues) > 0 {
		for _, field := range gearValues {
			add(field.key, "gearing", field.value, field.reason)
		}
		gearCount := int(*normalized.GearCount)
		for i := gearCount + 1; i <= 10; i++ {
			skip(fmt.Sprintf("gear%d", i), "gearing", "locked_or_unavailable", "Gear is above the selected gear count and is treated as not unlocked.")
		}
	} else {
		skip("finalDrive", "gearing", reason, message)
		for i := 1; i <= 10; i++ {
			skip(fmt.Sprintf("gear%d", i), "gearing", reason, message)
		}
	}

	applyRoadBaselineBiases(result, normalized)

	sort.Slice(result.GeneratedFields, func(i, j int) bool {
		if result.GeneratedFields[i].Group == result.GeneratedFields[j].Group {
			return result.GeneratedFields[i].FieldKey < result.GeneratedFields[j].FieldKey
		}
		return result.GeneratedFields[i].Group < result.GeneratedFields[j].Group
	})
	result.ProfileDraft = normalizeTuneProfilePower(result.ProfileDraft)
	return result, nil
}

func (s *Store) ApplyRoadStaticTuneBaseline(input RoadStaticTuneBaselineApplyInput) (*RoadStaticTuneBaselineApplyResult, error) {
	result, err := GenerateRoadStaticTuneBaseline(input.BaselineInput)
	if err != nil {
		return nil, err
	}
	selected, err := selectedBaselineFieldSet(input.SelectedFieldKeys, result.GeneratedFields)
	if err != nil {
		return nil, err
	}
	if len(selected) == 0 {
		return nil, errors.New("at least one generated field must be selected")
	}

	applied := sortedKeys(selected)
	var profile *TuneProfile
	if input.CreateNew {
		createInput := baselineIdentityInput(result.ProfileDraft)
		if strings.TrimSpace(createInput.CarName) == "" {
			createInput.CarName = quickTuneAutoName(result.ProfileDraft)
		}
		for key := range selected {
			if err := copyBaselineField(&createInput, result.ProfileDraft, key); err != nil {
				return nil, err
			}
		}
		profile, err = s.CreateTuneProfile(createInput)
	} else {
		if input.TargetProfileID <= 0 {
			return nil, errors.New("target profile is required")
		}
		existing, err := s.GetTuneProfile(input.TargetProfileID)
		if err != nil {
			return nil, err
		}
		updateInput := existing.ToInput()
		for key := range selected {
			if err := copyBaselineField(&updateInput, result.ProfileDraft, key); err != nil {
				return nil, err
			}
		}
		profile, err = s.updateTuneProfile(input.TargetProfileID, updateInput, staticBaselineChangeReason(result.ProfileDraft.UseCase))
	}
	if err != nil {
		return nil, err
	}
	return &RoadStaticTuneBaselineApplyResult{
		Profile:       *profile,
		AppliedFields: applied,
		SkippedFields: result.SkippedFields,
	}, nil
}

func staticBaselineChangeReason(useCase string) string {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return "drift_static_baseline"
	case "Rally":
		return "rally_static_baseline"
	case "Offroad":
		return "offroad_static_baseline"
	case "Drag":
		return "drag_static_baseline"
	default:
		return "road_static_baseline"
	}
}

func normalizeRoadStaticBaselineInput(input RoadStaticTuneBaselineInput) (RoadStaticTuneBaselineInput, error) {
	input.CarName = strings.TrimSpace(input.CarName)
	input.VersionName = strings.TrimSpace(input.VersionName)
	input.UseCase = normalizeStaticBaselineUseCase(input.UseCase)
	if !isSupportedStaticBaselineUseCase(input.UseCase) {
		return input, errors.New("use case must be Road, Drift, Rally, Offroad, or Drag")
	}
	input.Drivetrain = strings.ToUpper(strings.TrimSpace(input.Drivetrain))
	input.TireCompound = normalizeTireCompoundForUseCase(input.TireCompound, input.UseCase)
	if !isSupportedTireCompound(input.TireCompound) {
		return input, fmt.Errorf("tire compound must be one of: %s", strings.Join(supportedTireCompounds(), ", "))
	}
	if input.PI < 100 || input.PI > 999 {
		return input, errors.New("PI must be between 100 and 999")
	}
	if !isWholeNumber(input.WeightKG) || input.WeightKG < 300 || input.WeightKG > 3000 {
		return input, errors.New("weight kg must be an integer between 300 and 3000")
	}
	if !isWholeNumber(input.FrontWeightPct) || input.FrontWeightPct < 1 || input.FrontWeightPct > 99 {
		return input, errors.New("front weight percentage must be an integer between 1 and 99")
	}
	if input.RedlineRPM != nil && (!isWholeNumber(*input.RedlineRPM) || *input.RedlineRPM < 1000 || *input.RedlineRPM > 20000) {
		return input, errors.New("redline RPM must be an integer between 1000 and 20000")
	}
	if input.GearCount != nil && (*input.GearCount < 2 || *input.GearCount > 10) {
		return input, errors.New("gear count must be between 2 and 10")
	}
	if input.TireDiameterCm != nil && (*input.TireDiameterCm < 40 || *input.TireDiameterCm > 120) {
		return input, errors.New("tire diameter must be between 40 cm and 120 cm")
	}
	if input.TargetTopSpeedKmh != nil {
		switch normalizeStaticBaselineUseCase(input.UseCase) {
		case "Drift":
			if !isWholeNumber(*input.TargetTopSpeedKmh) || *input.TargetTopSpeedKmh < 40 || *input.TargetTopSpeedKmh > 180 {
				return input, errors.New("target drift speed must be an integer between 40 and 180 km/h")
			}
		case "Drag":
			if !isWholeNumber(*input.TargetTopSpeedKmh) || *input.TargetTopSpeedKmh < 40 || *input.TargetTopSpeedKmh > 450 {
				return input, errors.New("target drag terminal speed must be an integer between 40 and 450 km/h")
			}
		default:
			if !isWholeNumber(*input.TargetTopSpeedKmh) || *input.TargetTopSpeedKmh <= 0 || *input.TargetTopSpeedKmh > 600 {
				return input, errors.New("target top speed must be an integer between 1 and 600")
			}
		}
	}
	input.BalanceBias = normalizeBaselineBias(input.BalanceBias)
	input.StiffnessBias = normalizeBaselineBias(input.StiffnessBias)
	input.SpeedBias = normalizeBaselineBias(input.SpeedBias)
	if err := validateBaselineBias(input.BalanceBias, "balance bias"); err != nil {
		return input, err
	}
	if err := validateBaselineBias(input.StiffnessBias, "stiffness bias"); err != nil {
		return input, err
	}
	if err := validateBaselineBias(input.SpeedBias, "speed bias"); err != nil {
		return input, err
	}
	switch input.Drivetrain {
	case "FWD", "RWD", "AWD":
	default:
		return input, errors.New("drivetrain must be FWD, RWD, or AWD")
	}
	return input, nil
}

func normalizeStaticBaselineUseCase(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "", "road", "公路":
		return "Road"
	case "drift", "漂移":
		return "Drift"
	case "rally", "拉力":
		return "Rally"
	case "offroad", "off-road", "off road", "越野":
		return "Offroad"
	case "drag", "直线", "直線":
		return "Drag"
	default:
		return strings.TrimSpace(value)
	}
}

func isSupportedStaticBaselineUseCase(value string) bool {
	switch normalizeStaticBaselineUseCase(value) {
	case "Road", "Drift", "Rally", "Offroad", "Drag":
		return true
	default:
		return false
	}
}

func baselineDefaultVersionName(useCase string) string {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return "Drift Baseline"
	case "Rally":
		return "Rally Baseline"
	case "Offroad":
		return "Offroad Baseline"
	case "Drag":
		return "Drag Baseline"
	default:
		return "Road Baseline"
	}
}

func baselineNextTestPlanIntro(useCase string) string {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return "Run one controlled drift test with the baseline before changing multiple systems."
	case "Rally":
		return "Run one clean rally stage with the baseline and watch suspension travel, tire slip, and landing stability."
	case "Offroad":
		return "Run one cross-country test with the baseline and watch bottoming, landing stability, and tire slip."
	case "Drag":
		return "Run one straight-line launch test with the baseline and watch wheelspin, shift RPM, and terminal speed."
	default:
		return "Run one clean road test with the baseline before changing multiple systems."
	}
}

func baselineReason(useCase string, text string) string {
	prefix := "Road"
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		prefix = "Drift"
	case "Rally":
		prefix = "Rally"
	case "Offroad":
		prefix = "Offroad"
	case "Drag":
		prefix = "Drag"
	}
	return strings.TrimSpace(prefix + " " + text)
}

func normalizeBaselineBias(value float64) float64 {
	if value == 0 {
		return 100
	}
	return value
}

func validateBaselineBias(value float64, name string) error {
	if !isWholeNumber(value) || value < 50 || value > 150 {
		return fmt.Errorf("%s must be an integer between 50 and 150", name)
	}
	return nil
}

func isWholeNumber(value float64) bool {
	return math.Abs(value-math.Round(value)) < 1e-9
}

func quickTuneAutoName(draft TuneProfileInput) string {
	carClass := strings.TrimSpace(draft.CarClass)
	pi := ""
	if draft.PI != nil && *draft.PI > 0 {
		pi = fmt.Sprintf("%d", *draft.PI)
	}
	drivetrain := strings.ToUpper(strings.TrimSpace(draft.Drivetrain))
	parts := []string{"Quick Tune"}
	switch normalizeStaticBaselineUseCase(draft.UseCase) {
	case "Drift":
		parts = []string{"Quick Drift"}
	case "Rally":
		parts = []string{"Quick Rally"}
	case "Offroad":
		parts = []string{"Quick Offroad"}
	case "Drag":
		parts = []string{"Quick Drag"}
	}
	if carClass != "" || pi != "" {
		parts = append(parts, strings.TrimSpace(carClass+pi))
	}
	if drivetrain != "" {
		parts = append(parts, drivetrain)
	}
	return strings.Join(parts, " ")
}

func classFromPI(pi int64) string {
	switch {
	case pi <= 400:
		return "D"
	case pi <= 500:
		return "C"
	case pi <= 600:
		return "B"
	case pi <= 700:
		return "A"
	case pi <= 800:
		return "S1"
	case pi <= 900:
		return "S2"
	case pi <= 998:
		return "R"
	default:
		return "X"
	}
}

func baselineTirePressures(useCase string, drivetrain string, tireCompound string, weightKG float64) (float64, float64) {
	if strings.EqualFold(useCase, "Drift") {
		return baselineDriftTirePressures(weightKG)
	}

	base := tireCompoundBasePressureBar(tireCompound)
	weightAdj := tirePressureWeightAddBar(weightKG)
	frontSplit, rearSplit := tirePressureSplitBar(useCase, drivetrain)

	front := base + weightAdj + frontSplit
	rear := base + weightAdj + rearSplit

	minPressure, maxPressure := tirePressureClampBar(useCase)
	return clamp(roundTunePlanStep(front, 0.01), minPressure, maxPressure),
		clamp(roundTunePlanStep(rear, 0.01), minPressure, maxPressure)
}

func baselineDriftTirePressures(weightKG float64) (float64, float64) {
	front := clamp(roundTunePlanStep(2.10+tirePressureWeightAddBar(weightKG), 0.01), 2.10, 2.60)
	rear := clamp(roundTunePlanStep(front+0.40, 0.01), 2.50, 3.00)
	return front, rear
}

func normalizeTireCompound(value string) string {
	compound := strings.ToLower(strings.TrimSpace(value))
	if compound == "" {
		return "sport"
	}
	return compound
}

func normalizeTireCompoundForUseCase(value string, useCase string) string {
	compound := strings.ToLower(strings.TrimSpace(value))
	if compound == "" {
		switch normalizeStaticBaselineUseCase(useCase) {
		case "Drift":
			return "drift"
		case "Rally":
			return "rally"
		case "Offroad":
			return "offroad"
		case "Drag":
			return "drag"
		default:
			return "sport"
		}
	}
	return normalizeTireCompound(compound)
}

func supportedTireCompounds() []string {
	return []string{"stock", "street", "sport", "semi", "slick", "rally", "offroad", "drift", "drag", "snow"}
}

func isSupportedTireCompound(value string) bool {
	for _, compound := range supportedTireCompounds() {
		if value == compound {
			return true
		}
	}
	return false
}

func tireCompoundBasePressureBar(tireCompound string) float64 {
	switch normalizeTireCompound(tireCompound) {
	case "stock", "street":
		return 2.14
	case "semi":
		return 2.21
	case "slick":
		return 2.24
	case "rally":
		return 2.03
	case "offroad", "snow":
		return 2.00
	case "drift":
		return 1.52
	case "drag":
		return 1.72
	default:
		return 2.17
	}
}

func tirePressureWeightAddBar(weightKG float64) float64 {
	switch {
	case weightKG < 900:
		return -0.07
	case weightKG < 1200:
		return -0.03
	case weightKG < 1500:
		return 0
	case weightKG < 1700:
		return 0.03
	case weightKG < 1900:
		return 0.07
	default:
		return 0.10
	}
}

func tirePressureSplitBar(useCase string, drivetrain string) (float64, float64) {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Rally", "Offroad":
		return 0, 0
	case "Drag":
		switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
		case "RWD":
			return 0.48, 0
		case "FWD":
			return 0, 0.48
		default:
			return 0, 0
		}
	}
	switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
	case "FWD":
		return 0.07, -0.03
	case "RWD":
		return 0.03, -0.03
	default:
		return 0, -0.03
	}
}

func tirePressureClampBar(useCase string) (float64, float64) {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return 2.10, 3.60
	case "Rally":
		return 1.97, 2.10
	case "Offroad":
		return 1.93, 2.07
	case "Drag":
		return 1.24, 2.41
	default:
		return 1.93, 2.41
	}
}

func baselineSprings(useCase string, drivetrain string, weightKG float64, frontWeightPct float64, springFactor float64) (float64, float64) {
	const kgToLb = 2.2046226218
	const lbInPerForzaMetricDisplayUnit = 5.59974

	weightLb := weightKG * kgToLb
	frontShare := frontWeightPct / 100
	rearShare := 1 - frontShare
	frontBalanceRatio, rearBalanceRatio := supportRatiosForUseCase(useCase, drivetrain, frontWeightPct)
	calc := func(axleShare float64) float64 {
		lbIn := weightLb * axleShare * springFactor
		return clamp(roundTunePlanStep(lbIn/lbInPerForzaMetricDisplayUnit, 0.1), 0, 999)
	}
	return clamp(roundTunePlanStep(calc(frontShare)*frontBalanceRatio, 0.1), 0, 999),
		clamp(roundTunePlanStep(calc(rearShare)*rearBalanceRatio, 0.1), 0, 999)
}

func roadSpringFactorForClass(carClass string) float64 {
	switch strings.ToUpper(strings.TrimSpace(carClass)) {
	case "A":
		return 0.42
	case "S1":
		return 0.48
	case "S2":
		return 0.54
	case "R":
		return 0.58
	case "X":
		return 0.62
	default:
		return 0.35
	}
}

func driftSpringFactorForClass(carClass string) float64 {
	switch strings.ToUpper(strings.TrimSpace(carClass)) {
	case "A":
		return 0.32
	case "S1":
		return 0.35
	case "S2":
		return 0.38
	case "R":
		return 0.42
	case "X":
		return 0.45
	default:
		return 0.30
	}
}

func rallySpringFactorForClass(carClass string) float64 {
	switch strings.ToUpper(strings.TrimSpace(carClass)) {
	case "A":
		return 0.26
	case "S1":
		return 0.28
	case "S2":
		return 0.30
	case "R":
		return 0.32
	case "X":
		return 0.34
	default:
		return 0.24
	}
}

func offroadSpringFactorForClass(carClass string) float64 {
	switch strings.ToUpper(strings.TrimSpace(carClass)) {
	case "A":
		return 0.22
	case "S1":
		return 0.24
	case "S2":
		return 0.26
	case "R":
		return 0.28
	case "X":
		return 0.30
	default:
		return 0.20
	}
}

func dragSpringFactorForClass(carClass string) float64 {
	switch strings.ToUpper(strings.TrimSpace(carClass)) {
	case "A":
		return 0.30
	case "S1":
		return 0.33
	case "S2":
		return 0.36
	case "R":
		return 0.40
	case "X":
		return 0.42
	default:
		return 0.27
	}
}

func springFactorForBaseline(useCase string, carClass string) float64 {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return driftSpringFactorForClass(carClass)
	case "Rally":
		return rallySpringFactorForClass(carClass)
	case "Offroad":
		return offroadSpringFactorForClass(carClass)
	case "Drag":
		return dragSpringFactorForClass(carClass)
	default:
		return roadSpringFactorForClass(carClass)
	}
}

type roadAlignmentBaseline struct {
	frontCamber float64
	rearCamber  float64
	frontToe    float64
	rearToe     float64
	caster      float64
}

func baselineAlignment(useCase string, carClass string, drivetrain string, frontWeightPct float64, balanceBias float64) roadAlignmentBaseline {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return roadAlignmentBaseline{
			frontCamber: -4.5,
			rearCamber:  -0.5,
			frontToe:    1.0,
			rearToe:     0.0,
			caster:      7.0,
		}
	case "Rally":
		return roadAlignmentBaseline{
			frontCamber: -1.2,
			rearCamber:  -0.8,
			frontToe:    0.0,
			rearToe:     0.0,
			caster:      5.8,
		}
	case "Offroad":
		return roadAlignmentBaseline{
			frontCamber: -0.8,
			rearCamber:  -0.5,
			frontToe:    0.0,
			rearToe:     0.0,
			caster:      5.2,
		}
	case "Drag":
		return roadAlignmentBaseline{
			frontCamber: 0.0,
			rearCamber:  0.0,
			frontToe:    0.0,
			rearToe:     0.0,
			caster:      6.0,
		}
	}
	frontCamber, rearCamber, caster := roadAlignmentBaseByClass(carClass)
	frontWeightBias := roadFrontHeavyBalanceFactor(frontWeightPct)
	frontCamber -= 0.2 * frontWeightBias
	rearCamber += 0.1 * frontWeightBias
	caster += 0.3 * frontWeightBias

	switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
	case "FWD":
		frontCamber -= 0.1
		rearCamber += 0.1
		caster += 0.2
	case "RWD":
		rearCamber -= 0.1
	}

	balanceAxis := baselineBiasAxis(balanceBias)
	if balanceAxis > 0 {
		frontCamber -= 0.1 * balanceAxis
		rearCamber += 0.1 * balanceAxis
	} else if balanceAxis < 0 {
		frontCamber += 0.1 * math.Abs(balanceAxis)
		rearCamber -= 0.1 * math.Abs(balanceAxis)
	}

	frontToe := 0.0
	rearToe := 0.0
	if balanceBias >= 115 {
		frontToe = -0.1
	}
	if balanceBias <= 85 {
		rearToe = 0.1
	}

	return roadAlignmentBaseline{
		frontCamber: roundTunePlanStep(clamp(frontCamber, -2.5, -1.0), 0.1),
		rearCamber:  roundTunePlanStep(clamp(rearCamber, -1.8, -0.6), 0.1),
		frontToe:    roundTunePlanStep(clamp(frontToe, -0.1, 0), 0.1),
		rearToe:     roundTunePlanStep(clamp(rearToe, 0, 0.1), 0.1),
		caster:      roundTunePlanStep(clamp(caster, 4.8, 6.8), 0.1),
	}
}

func roadAlignmentBaseByClass(carClass string) (float64, float64, float64) {
	switch strings.ToUpper(strings.TrimSpace(carClass)) {
	case "A":
		return -1.5, -1.0, 5.5
	case "S1":
		return -1.8, -1.2, 6.0
	case "S2", "R", "X":
		return -2.1, -1.4, 6.5
	default:
		return -1.2, -0.8, 5.0
	}
}

func baselineDamping(useCase string, weightKG float64, frontWeightPct float64, carClass string, springFactor float64, frontSpring float64, rearSpring float64) (float64, float64, float64, float64) {
	const kgToLb = 2.2046226218

	frontAxleLb := weightKG * kgToLb * frontWeightPct / 100
	baseBump := dampingMinBump(useCase, carClass) + (frontAxleLb/200)*0.1
	frontBump := baseBump * springDampingMultiplier(springFactor)
	frontRebound := frontBump / dampingBumpRatio(useCase)
	reboundOffset, bumpOffset := rearDampingOffset(frontSpring, rearSpring)
	frontBalanceRatio, rearBalanceRatio := dampingRatiosForUseCase(useCase, frontWeightPct)
	return frontRebound * frontBalanceRatio,
		(frontRebound + reboundOffset) * rearBalanceRatio,
		frontBump * frontBalanceRatio,
		(frontBump + bumpOffset) * rearBalanceRatio
}

func dampingMinBump(useCase string, carClass string) float64 {
	switch strings.ToLower(strings.TrimSpace(useCase)) {
	case "drift":
		return 4.8
	case "rally":
		return 4.2
	case "offroad":
		return 4.0
	case "drag":
		return 4.5
	}
	switch strings.ToUpper(strings.TrimSpace(carClass)) {
	case "S1":
		return 4.85
	case "S2", "R", "X":
		return 4.9
	default:
		return 4.8
	}
}

func dampingBumpRatio(useCase string) float64 {
	switch strings.ToLower(strings.TrimSpace(useCase)) {
	case "offroad", "rally":
		return 0.55
	case "drag":
		return 0.58
	default:
		return 0.60
	}
}

func springDampingMultiplier(springFactor float64) float64 {
	return 1 + math.Max(0, springFactor-0.30)*2.0
}

func rearDampingOffset(frontSpring float64, rearSpring float64) (float64, float64) {
	avg := (frontSpring + rearSpring) / 2
	diffPct := 0.0
	if avg > 0 {
		diffPct = math.Abs(frontSpring-rearSpring) / avg * 100
	}
	reboundOffset := 0.2
	bumpOffset := 0.1
	switch {
	case diffPct > 40:
		reboundOffset = 1.2
		bumpOffset = 0.8
	case diffPct > 35:
		reboundOffset = 0.6
		bumpOffset = 0.4
	case diffPct > 1.5:
		reboundOffset = 0.3
		bumpOffset = 0.2
	}
	if frontSpring > rearSpring {
		return -reboundOffset, -bumpOffset
	}
	if rearSpring > frontSpring {
		return reboundOffset, bumpOffset
	}
	return -0.2, -0.1
}

func baselineARB(useCase string, frontWeightPct float64, carClass string, drivetrain string) (float64, float64) {
	t := classInterpolationT(carClass)
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return math.Round(lerp(15, 25, t)), math.Round(lerp(18, 30, t))
	case "Rally":
		return 10, 12
	case "Offroad":
		return 6, 8
	case "Drag":
		switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
		case "FWD":
			return 8, 12
		case "AWD":
			return 10, 10
		default:
			return 12, 8
		}
	}
	frontRatio, rearRatio := roadFrontHeavyARBRatios(frontWeightPct)
	scale := func(front, rear float64) (float64, float64) {
		return math.Round(front * frontRatio), math.Round(rear * rearRatio)
	}
	switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
	case "RWD":
		return scale(lerp(18, 25, t), lerp(25, 35, t))
	case "FWD":
		return scale(lerp(8, 15, t), lerp(25, 40, t))
	case "AWD":
		return scale(lerp(22, 30, t), lerp(28, 38, t))
	default:
		return scale(lerp(18, 25, t), lerp(25, 35, t))
	}
}

func roadFrontHeavySupportRatios(frontWeightPct float64) (float64, float64) {
	factor := roadFrontHeavyBalanceFactor(frontWeightPct)
	return 1 - 0.06*factor, 1 + 0.08*factor
}

func driftFrontHeavySupportRatios(frontWeightPct float64) (float64, float64) {
	factor := roadFrontHeavyBalanceFactor(frontWeightPct)
	return 1 - 0.02*factor, 1 + 0.06*factor
}

func dragSupportRatios(drivetrain string) (float64, float64) {
	switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
	case "RWD":
		return 1.00, 0.92
	case "FWD":
		return 0.92, 1.00
	default:
		return 1.00, 1.00
	}
}

func supportRatiosForUseCase(useCase string, drivetrain string, frontWeightPct float64) (float64, float64) {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return driftFrontHeavySupportRatios(frontWeightPct)
	case "Rally", "Offroad":
		return 1, 1
	case "Drag":
		return dragSupportRatios(drivetrain)
	default:
		return roadFrontHeavySupportRatios(frontWeightPct)
	}
}

func roadFrontHeavyDampingRatios(frontWeightPct float64) (float64, float64) {
	factor := roadFrontHeavyBalanceFactor(frontWeightPct)
	return 1 - 0.04*factor, 1 + 0.06*factor
}

func driftFrontHeavyDampingRatios(frontWeightPct float64) (float64, float64) {
	factor := roadFrontHeavyBalanceFactor(frontWeightPct)
	return 1, 1 + 0.05*factor
}

func dampingRatiosForUseCase(useCase string, frontWeightPct float64) (float64, float64) {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return driftFrontHeavyDampingRatios(frontWeightPct)
	case "Rally", "Offroad", "Drag":
		return 1, 1
	default:
		return roadFrontHeavyDampingRatios(frontWeightPct)
	}
}

func roadFrontHeavyARBRatios(frontWeightPct float64) (float64, float64) {
	factor := roadFrontHeavyBalanceFactor(frontWeightPct)
	return 1 - 0.06*factor, 1 + 0.08*factor
}

func roadFrontHeavyBalanceFactor(frontWeightPct float64) float64 {
	return clamp((frontWeightPct-50)/10, 0, 1)
}

func classInterpolationT(carClass string) float64 {
	switch strings.ToUpper(strings.TrimSpace(carClass)) {
	case "D":
		return 0.10
	case "C":
		return 0.20
	case "B":
		return 0.30
	case "A":
		return 0.40
	case "S1":
		return 0.60
	case "S2":
		return 0.75
	case "R":
		return 0.90
	case "X":
		return 1.00
	default:
		return 0.40
	}
}

func lerp(a float64, b float64, t float64) float64 {
	return a + (b-a)*t
}

func baselineBrakeBalance(useCase string, drivetrain string) float64 {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return 48
	case "Drag":
		if strings.EqualFold(drivetrain, "RWD") {
			return 50
		}
	}
	switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
	case "FWD":
		return 58
	case "AWD":
		return 54
	default:
		return 52
	}
}

func baselineBrakePressure(useCase string) float64 {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Rally", "Offroad":
		return 95
	default:
		return 100
	}
}

type roadDifferentialBaseline struct {
	frontAccel  *float64
	frontDecel  *float64
	rearAccel   *float64
	rearDecel   *float64
	centerSplit *float64
}

func appendDifferentialBaseline(result *RoadStaticTuneBaselineResult, useCase string, carClass string, drivetrain string, weightKG float64, frontWeightPct float64, balanceBias float64, add func(string, string, float64, string), skip func(string, string, string, string)) {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
		case "RWD":
			add("rearDiffAccel", "differential", 100, "Drift rear acceleration differential baseline; RWD preferred full lock starting point.")
			add("rearDiffDecel", "differential", 100, "Drift rear deceleration differential baseline; RWD preferred full lock starting point.")
		case "FWD", "AWD":
			skip("frontDiffAccel", "differential", "drift_rwd_preferred", "Drift quick tune is RWD-first; front/AWD differential values are not generated automatically.")
			skip("frontDiffDecel", "differential", "drift_rwd_preferred", "Drift quick tune is RWD-first; front/AWD differential values are not generated automatically.")
			skip("rearDiffAccel", "differential", "drift_rwd_preferred", "Drift quick tune is RWD-first; use a RWD setup for automatic 100/100 rear differential.")
			skip("rearDiffDecel", "differential", "drift_rwd_preferred", "Drift quick tune is RWD-first; use a RWD setup for automatic 100/100 rear differential.")
			if strings.EqualFold(drivetrain, "AWD") {
				skip("centerDiffBalance", "differential", "drift_rwd_preferred", "Drift quick tune does not generate AWD center balance in this MVP.")
			}
		}
		return
	case "Rally":
		appendUseCaseDifferentialBaseline(useCase, drivetrain, add, roadDifferentialBaseline{
			frontAccel:  float64Ptr(30),
			frontDecel:  float64Ptr(5),
			rearAccel:   float64Ptr(60),
			rearDecel:   float64Ptr(20),
			centerSplit: float64Ptr(65),
		})
		return
	case "Offroad":
		appendUseCaseDifferentialBaseline(useCase, drivetrain, add, roadDifferentialBaseline{
			frontAccel:  float64Ptr(35),
			frontDecel:  float64Ptr(8),
			rearAccel:   float64Ptr(70),
			rearDecel:   float64Ptr(20),
			centerSplit: float64Ptr(60),
		})
		return
	case "Drag":
		switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
		case "FWD":
			appendUseCaseDifferentialBaseline(useCase, drivetrain, add, roadDifferentialBaseline{
				frontAccel: float64Ptr(85),
				frontDecel: float64Ptr(20),
			})
		case "AWD":
			appendUseCaseDifferentialBaseline(useCase, drivetrain, add, roadDifferentialBaseline{
				frontAccel:  float64Ptr(35),
				frontDecel:  float64Ptr(5),
				rearAccel:   float64Ptr(85),
				rearDecel:   float64Ptr(20),
				centerSplit: float64Ptr(75),
			})
		default:
			appendUseCaseDifferentialBaseline(useCase, drivetrain, add, roadDifferentialBaseline{
				rearAccel: float64Ptr(85),
				rearDecel: float64Ptr(20),
			})
		}
		return
	}
	diff := baselineDifferential(carClass, drivetrain, weightKG, frontWeightPct, balanceBias)
	switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
	case "FWD":
		add("frontDiffAccel", "differential", *diff.frontAccel, "FWD road differential baseline from PI class, axle load, vehicle weight, and balance bias.")
		add("frontDiffDecel", "differential", *diff.frontDecel, "FWD road deceleration differential baseline from PI class, axle load, vehicle weight, and balance bias.")
	case "RWD":
		add("rearDiffAccel", "differential", *diff.rearAccel, "RWD road differential baseline from PI class, axle load, vehicle weight, and balance bias.")
		add("rearDiffDecel", "differential", *diff.rearDecel, "RWD road deceleration differential baseline from PI class, axle load, vehicle weight, and balance bias.")
	case "AWD":
		add("frontDiffAccel", "differential", *diff.frontAccel, "AWD front differential baseline from PI class, axle load, vehicle weight, and balance bias.")
		add("frontDiffDecel", "differential", *diff.frontDecel, "AWD front deceleration differential baseline from PI class, axle load, vehicle weight, and balance bias.")
		add("rearDiffAccel", "differential", *diff.rearAccel, "AWD rear differential baseline from PI class, axle load, vehicle weight, and balance bias.")
		add("rearDiffDecel", "differential", *diff.rearDecel, "AWD rear deceleration differential baseline from PI class, axle load, vehicle weight, and balance bias.")
		add("centerDiffBalance", "differential", *diff.centerSplit, "AWD center balance baseline from PI class, front weight distribution, and balance bias.")
	}
}

func appendUseCaseDifferentialBaseline(useCase string, drivetrain string, add func(string, string, float64, string), diff roadDifferentialBaseline) {
	reason := baselineReason(useCase, "differential static baseline by use case and drivetrain.")
	switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
	case "FWD":
		if diff.frontAccel != nil {
			add("frontDiffAccel", "differential", *diff.frontAccel, reason)
		}
		if diff.frontDecel != nil {
			add("frontDiffDecel", "differential", *diff.frontDecel, reason)
		}
	case "RWD":
		if diff.rearAccel != nil {
			add("rearDiffAccel", "differential", *diff.rearAccel, reason)
		}
		if diff.rearDecel != nil {
			add("rearDiffDecel", "differential", *diff.rearDecel, reason)
		}
	case "AWD":
		if diff.frontAccel != nil {
			add("frontDiffAccel", "differential", *diff.frontAccel, reason)
		}
		if diff.frontDecel != nil {
			add("frontDiffDecel", "differential", *diff.frontDecel, reason)
		}
		if diff.rearAccel != nil {
			add("rearDiffAccel", "differential", *diff.rearAccel, reason)
		}
		if diff.rearDecel != nil {
			add("rearDiffDecel", "differential", *diff.rearDecel, reason)
		}
		if diff.centerSplit != nil {
			add("centerDiffBalance", "differential", *diff.centerSplit, reason)
		}
	}
}

func baselineRideHeightTier(useCase string) (string, string) {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return "low", "Drift baseline targets a low ride-height tier, about the lower 10% slider area; set manually in game."
	case "Rally":
		return "medium", "Rally baseline keeps a medium-high ride-height tier to preserve suspension travel; set manually in game."
	case "Offroad":
		return "high", "Offroad baseline targets a high ride-height tier for bumps, jumps, and landings; set manually in game."
	case "Drag":
		return "medium", "Drag baseline uses a medium ride-height tier; adjust manually for launch grip and bottoming."
	default:
		return "low", "Road baseline targets about 15% ride-height slider; set manually in game."
	}
}

func baselineAeroTier(useCase string) (string, string) {
	switch normalizeStaticBaselineUseCase(useCase) {
	case "Drift":
		return "low", "Drift baseline treats aero as low priority; use a low tier only when adjustable and needed."
	case "Rally":
		return "low", "Rally baseline treats aero as low to medium priority; use low tier unless high-speed dirt stability needs more."
	case "Offroad":
		return "low", "Offroad baseline does not rely on aero; use a low tier only when adjustable."
	case "Drag":
		return "low", "Drag baseline prioritizes low drag; use the lowest practical aero tier unless stability requires more."
	default:
		return "medium", "Road baseline uses medium adjustable aero, roughly the middle slider range; set manually in game."
	}
}

func baselineDifferential(carClass string, drivetrain string, weightKG float64, frontWeightPct float64, balanceBias float64) roadDifferentialBaseline {
	classT := classInterpolationT(carClass)
	frontLoadBias := clamp((frontWeightPct-50)/15, -1, 1)
	heavyBias := clamp((weightKG-1400)/600, -1, 1)
	balanceAxis := baselineBiasAxis(balanceBias)
	valuePtr := func(value float64) *float64 {
		rounded := clamp(roundTunePlanStep(value, 1), 0, 100)
		return &rounded
	}

	switch strings.ToUpper(strings.TrimSpace(drivetrain)) {
	case "FWD":
		frontAccel := lerp(22, 30, classT) + 1.0*frontLoadBias + 0.5*heavyBias - 2.0*balanceAxis
		frontDecel := lerp(5, 9, classT) + 0.5*heavyBias - 1.0*balanceAxis
		return roadDifferentialBaseline{
			frontAccel: valuePtr(frontAccel),
			frontDecel: valuePtr(frontDecel),
		}
	case "RWD":
		rearAccel := lerp(44, 54, classT) - 1.0*frontLoadBias + 0.5*heavyBias + 2.0*balanceAxis
		rearDecel := lerp(26, 34, classT) - 0.5*frontLoadBias + 0.5*heavyBias + 2.0*balanceAxis
		return roadDifferentialBaseline{
			rearAccel: valuePtr(rearAccel),
			rearDecel: valuePtr(rearDecel),
		}
	case "AWD":
		frontAccel := lerp(18, 25, classT) + 0.5*frontLoadBias + 0.5*heavyBias - 2.0*balanceAxis
		frontDecel := lerp(5, 8, classT) + 0.5*heavyBias - 1.0*balanceAxis
		rearAccel := lerp(50, 60, classT) - 0.5*frontLoadBias + 0.5*heavyBias + 2.0*balanceAxis
		rearDecel := lerp(22, 30, classT) - 0.25*frontLoadBias + 0.5*heavyBias + 2.0*balanceAxis
		centerSplit := lerp(62, 70, classT) + 1.0*frontLoadBias + 2.0*balanceAxis
		return roadDifferentialBaseline{
			frontAccel:  valuePtr(frontAccel),
			frontDecel:  valuePtr(frontDecel),
			rearAccel:   valuePtr(rearAccel),
			rearDecel:   valuePtr(rearDecel),
			centerSplit: valuePtr(centerSplit),
		}
	default:
		return roadDifferentialBaseline{}
	}
}

func applyRoadBaselineBiases(result *RoadStaticTuneBaselineResult, input RoadStaticTuneBaselineInput) {
	balanceAxis := baselineBiasAxis(input.BalanceBias)
	stiffnessAxis := baselineBiasAxis(input.StiffnessBias)
	speedAxis := baselineBiasAxis(input.SpeedBias)

	if balanceAxis != 0 {
		note := fmt.Sprintf("Balance bias %.0f adjusts front/rear ratio for stability versus rotation.", input.BalanceBias)
		frontRatio := 1 - 0.08*balanceAxis
		rearRatio := 1 + 0.08*balanceAxis
		frontSupportRatio := 1 - 0.04*balanceAxis
		rearSupportRatio := 1 + 0.04*balanceAxis
		scaleBaselineGeneratedField(result, "frontArb", frontRatio, note)
		scaleBaselineGeneratedField(result, "rearArb", rearRatio, note)
		scaleBaselineGeneratedField(result, "frontSpring", frontSupportRatio, note)
		scaleBaselineGeneratedField(result, "rearSpring", rearSupportRatio, note)
		scaleBaselineGeneratedField(result, "frontRebound", frontSupportRatio, note)
		scaleBaselineGeneratedField(result, "rearRebound", rearSupportRatio, note)
		scaleBaselineGeneratedField(result, "frontBump", frontSupportRatio, note)
		scaleBaselineGeneratedField(result, "rearBump", rearSupportRatio, note)
		adjustBaselineGeneratedField(result, "brakeBalance", func(value float64) float64 {
			return clamp(value-2*balanceAxis, 45, 65)
		}, note)
	}

	if stiffnessAxis != 0 {
		note := fmt.Sprintf("Stiffness bias %.0f scales roll, spring, and damping support.", input.StiffnessBias)
		ratio := 1 + 0.12*stiffnessAxis
		for _, key := range []string{"frontArb", "rearArb", "frontSpring", "rearSpring", "frontRebound", "rearRebound", "frontBump", "rearBump"} {
			scaleBaselineGeneratedField(result, key, ratio, note)
		}
	}

	if speedAxis != 0 {
		note := fmt.Sprintf("Speed bias %.0f adjusts final drive toward top speed or acceleration while preserving gear spacing.", input.SpeedBias)
		switch normalizeStaticBaselineUseCase(input.UseCase) {
		case "Drift":
			note = fmt.Sprintf("Drift speed bias %.0f adjusts final drive toward higher-speed drift or lower-speed high-RPM drift while preserving gear spacing.", input.SpeedBias)
		case "Drag":
			note = fmt.Sprintf("Drag speed bias %.0f adjusts final drive toward terminal speed or launch acceleration while preserving gear spacing.", input.SpeedBias)
		}
		ratio := 1 + 0.08*speedAxis
		scaleBaselineGeneratedField(result, "finalDrive", ratio, note)
	}
}

func baselineBiasAxis(value float64) float64 {
	return clamp((normalizeBaselineBias(value)-100)/50, -1, 1)
}

func scaleBaselineGeneratedField(result *RoadStaticTuneBaselineResult, key string, ratio float64, note string) {
	adjustBaselineGeneratedField(result, key, func(value float64) float64 {
		return value * ratio
	}, note)
}

func adjustBaselineGeneratedField(result *RoadStaticTuneBaselineResult, key string, transform func(float64) float64, note string) {
	current, ok := getTuneProfileInputFloat(result.ProfileDraft, key)
	if !ok || current == nil {
		return
	}
	if !setTuneProfileInputFloat(&result.ProfileDraft, key, transform(*current)) {
		return
	}
	updated, _ := getTuneProfileInputFloat(result.ProfileDraft, key)
	for i := range result.GeneratedFields {
		if result.GeneratedFields[i].FieldKey == key {
			result.GeneratedFields[i].Value = updated
			result.GeneratedFields[i].Reason = appendBaselineBiasReason(result.GeneratedFields[i].Reason, note)
			return
		}
	}
}

func appendBaselineBiasReason(reason string, note string) string {
	if strings.TrimSpace(note) == "" {
		return reason
	}
	if strings.Contains(reason, note) {
		return reason
	}
	return strings.TrimSpace(reason) + " " + note
}

type baselineGearField struct {
	key    string
	value  float64
	reason string
}

func baselineGearing(input RoadStaticTuneBaselineInput) ([]baselineGearField, string, string) {
	if input.RedlineRPM == nil || input.GearCount == nil || input.TireDiameterCm == nil || input.TargetTopSpeedKmh == nil {
		return nil, "missing_gear_input", "Static gearing needs redline RPM, gear count, tire size, and target top speed."
	}
	redline := *input.RedlineRPM
	gearCount := int(*input.GearCount)
	tireDiameterCm := *input.TireDiameterCm
	targetTopSpeedKmh := *input.TargetTopSpeedKmh
	if redline < 1000 || redline > 20000 {
		return nil, "invalid_gear_input", "Redline RPM should be between 1000 and 20000."
	}
	if gearCount < 2 || gearCount > 10 {
		return nil, "invalid_gear_input", "Gear count should be between 2 and 10."
	}
	if tireDiameterCm < 40 || tireDiameterCm > 120 {
		return nil, "invalid_gear_input", "Tire size should produce a diameter between 40 cm and 120 cm."
	}
	if targetTopSpeedKmh <= 0 || targetTopSpeedKmh > 600 {
		return nil, "invalid_gear_input", "Target top speed should be between 1 km/h and 600 km/h."
	}

	circumferenceMeters := math.Pi * tireDiameterCm / 100
	targetMetersPerMinute := targetTopSpeedKmh * 1000 / 60
	wheelRPMAtTarget := targetMetersPerMinute / circumferenceMeters
	if wheelRPMAtTarget <= 0 {
		return nil, "invalid_gear_input", "Target speed and tire size do not produce a valid wheel speed."
	}

	if strings.EqualFold(input.UseCase, "Drift") {
		return baselineDriftGearing(redline, gearCount, tireDiameterCm, targetTopSpeedKmh, wheelRPMAtTarget)
	}
	if strings.EqualFold(input.UseCase, "Drag") {
		return baselineDragGearing(redline, gearCount, targetTopSpeedKmh, wheelRPMAtTarget)
	}

	topTotalRatio := redline / wheelRPMAtTarget
	finalDrive := clamp(roundTunePlanStep(topTotalRatio/0.82, 0.01), 2.20, 5.50)
	topGear := clamp(roundTunePlanStep(topTotalRatio/finalDrive, 0.01), 0.45, 6.00)
	gears := make([]float64, gearCount+1)
	gears[gearCount] = topGear
	for gear := gearCount - 1; gear >= 1; gear-- {
		retention := roadGearRetention(gearCount, gear)
		gears[gear] = gears[gear+1] / retention
	}

	useCaseLabel := normalizeStaticBaselineUseCase(input.UseCase)
	gearReason := "Segmented road static gear spread with wider low gears and progressively tighter high gears; verify with telemetry after the first test."
	finalDriveReason := "Balanced road final drive from target top speed, redline RPM, and tire size."
	if useCaseLabel == "Rally" || useCaseLabel == "Offroad" {
		gearReason = useCaseLabel + " MVP uses the generic Road static gear spread as a starting point; verify on the target route and telemetry."
		finalDriveReason = useCaseLabel + " MVP uses a generic final drive from target top speed, redline RPM, and tire size; refine after route testing."
	}

	fields := []baselineGearField{{
		key:    "finalDrive",
		value:  finalDrive,
		reason: finalDriveReason,
	}}
	for gear := 1; gear <= gearCount; gear++ {
		fields = append(fields, baselineGearField{
			key:    fmt.Sprintf("gear%d", gear),
			value:  clamp(roundTunePlanStep(gears[gear], 0.01), 0.45, 6.00),
			reason: gearReason,
		})
	}
	return fields, "", ""
}

func baselineDragGearing(redline float64, gearCount int, targetTrapSpeedKmh float64, wheelRPMAtTarget float64) ([]baselineGearField, string, string) {
	if targetTrapSpeedKmh < 40 || targetTrapSpeedKmh > 450 {
		return nil, "invalid_gear_input", "Target drag terminal speed should be between 40 km/h and 450 km/h."
	}
	topTotalRatio := redline * 0.96 / wheelRPMAtTarget
	finalDrive := clamp(roundTunePlanStep(topTotalRatio/0.88, 0.01), 2.20, 5.50)
	topGear := clamp(roundTunePlanStep(topTotalRatio/finalDrive, 0.01), 0.45, 6.00)
	gears := make([]float64, gearCount+1)
	gears[gearCount] = topGear
	for gear := gearCount - 1; gear >= 1; gear-- {
		retention := dragGearRetention(gearCount, gear)
		gears[gear] = gears[gear+1] / retention
	}

	fields := []baselineGearField{{
		key:    "finalDrive",
		value:  finalDrive,
		reason: "Drag final drive targets the selected terminal speed near redline while keeping launch gears usable.",
	}}
	for gear := 1; gear <= gearCount; gear++ {
		fields = append(fields, baselineGearField{
			key:    fmt.Sprintf("gear%d", gear),
			value:  clamp(roundTunePlanStep(gears[gear], 0.01), 0.45, 6.00),
			reason: "Drag static gear spread keeps shift RPM tighter than Road and targets strong acceleration through the selected terminal speed.",
		})
	}
	return fields, "", ""
}

func dragGearRetention(gearCount int, shiftIndex int) float64 {
	extra := clamp(float64(gearCount-5), 0, 5)
	low := 0.76 + 0.008*extra
	high := 0.88 + 0.010*extra
	if gearCount <= 2 {
		return high
	}
	t := float64(shiftIndex-1) / float64(gearCount-2)
	smooth := t * t * (3 - 2*t)
	return low + (high-low)*smooth
}

func baselineDriftGearing(redline float64, gearCount int, tireDiameterCm float64, targetDriftSpeedKmh float64, wheelRPMAtTarget float64) ([]baselineGearField, string, string) {
	if targetDriftSpeedKmh < 40 || targetDriftSpeedKmh > 180 {
		return nil, "invalid_gear_input", "Target drift speed should be between 40 km/h and 180 km/h."
	}
	coreGear := driftCoreGear(gearCount)
	coreTotalRatio := redline * 0.88 / wheelRPMAtTarget
	finalDrive := clamp(roundTunePlanStep(coreTotalRatio/driftDesiredCoreGear(coreGear), 0.01), 2.20, 5.50)
	coreRatio := clamp(roundTunePlanStep(coreTotalRatio/finalDrive, 0.01), 0.45, 6.00)

	gears := make([]float64, gearCount+1)
	gears[coreGear] = coreRatio
	for gear := coreGear - 1; gear >= 1; gear-- {
		gears[gear] = gears[gear+1] / driftLowerGearRetention(gear)
	}
	for gear := coreGear + 1; gear <= gearCount; gear++ {
		gears[gear] = gears[gear-1] * driftUpperGearRetention(gear-1, coreGear)
	}

	fields := []baselineGearField{{
		key:    "finalDrive",
		value:  finalDrive,
		reason: fmt.Sprintf("Drift final drive targets about 88%% redline in gear %d at the selected drift speed.", coreGear),
	}}
	for gear := 1; gear <= gearCount; gear++ {
		fields = append(fields, baselineGearField{
			key:    fmt.Sprintf("gear%d", gear),
			value:  clamp(roundTunePlanStep(gears[gear], 0.01), 0.45, 6.00),
			reason: fmt.Sprintf("Drift static gearing centers gear %d around high RPM at %.0f km/h; lower gears are shorter for initiation and upper gears are transition gears.", coreGear, targetDriftSpeedKmh),
		})
	}
	return fields, "", ""
}

func driftCoreGear(gearCount int) int {
	switch {
	case gearCount <= 4:
		return 2
	case gearCount <= 6:
		return 3
	default:
		return 4
	}
}

func driftDesiredCoreGear(coreGear int) float64 {
	switch coreGear {
	case 2:
		return 2.05
	case 3:
		return 1.65
	default:
		return 1.35
	}
}

func driftLowerGearRetention(shiftIndex int) float64 {
	switch shiftIndex {
	case 1:
		return 0.68
	case 2:
		return 0.72
	case 3:
		return 0.76
	default:
		return 0.78
	}
}

func driftUpperGearRetention(shiftIndex int, coreGear int) float64 {
	switch shiftIndex - coreGear {
	case 0:
		return 0.82
	case 1:
		return 0.86
	case 2:
		return 0.89
	case 3:
		return 0.91
	default:
		return 0.93
	}
}

func roadGearRetention(gearCount int, shiftIndex int) float64 {
	if gearCount <= 2 {
		return 0.78
	}
	extra := clamp(float64(gearCount-5), 0, 5)
	low := 0.70 + 0.01*extra
	high := 0.84 + 0.016*extra
	t := clamp(float64(shiftIndex-1)/float64(gearCount-2), 0, 1)
	smooth := t * t * (3 - 2*t)
	return low + (high-low)*smooth
}

func rangeBaselineValue(min *float64, max *float64, ratio float64) (float64, bool) {
	if min == nil || max == nil || *max <= *min {
		return 0, false
	}
	return *min + (*max-*min)*ratio, true
}

func midpointBaselineValue(min *float64, max *float64) (float64, bool) {
	if min == nil || max == nil || *max <= *min {
		return 0, false
	}
	return (*min + *max) / 2, true
}

func baselineIdentityInput(draft TuneProfileInput) TuneProfileInput {
	return TuneProfileInput{
		CarName:     draft.CarName,
		CarOrdinal:  draft.CarOrdinal,
		CarCategory: draft.CarCategory,
		CarClass:    draft.CarClass,
		PI:          draft.PI,
		Drivetrain:  draft.Drivetrain,
		UseCase:     draft.UseCase,
		VersionName: draft.VersionName,
		Notes:       draft.Notes,
	}
}

func selectedBaselineFieldSet(keys []string, generated []BaselineGeneratedField) (map[string]bool, error) {
	allowed := map[string]bool{}
	defaults := map[string]bool{}
	for _, field := range generated {
		allowed[field.FieldKey] = true
		if field.DefaultSelected {
			defaults[field.FieldKey] = true
		}
	}
	if len(keys) == 0 {
		return defaults, nil
	}
	selected := map[string]bool{}
	for _, key := range keys {
		key = strings.TrimSpace(key)
		if key == "" {
			continue
		}
		if !allowed[key] {
			return nil, fmt.Errorf("selected field %q was not generated", key)
		}
		selected[key] = true
	}
	return selected, nil
}

func copyBaselineField(target *TuneProfileInput, source TuneProfileInput, key string) error {
	if value, ok := getTuneProfileInputFloat(source, key); ok && value != nil {
		if setTuneProfileInputFloat(target, key, *value) {
			return nil
		}
		switch key {
		case "weightKG":
			target.WeightKG = value
		case "frontWeightPct":
			target.FrontWeightPct = value
		case "powerKW":
			target.PowerKW = value
		case "torqueNM":
			target.TorqueNM = value
		case "redlineRPM":
			target.RedlineRPM = value
		default:
			return fmt.Errorf("unsupported baseline field %q", key)
		}
		return nil
	}
	return fmt.Errorf("baseline field %q has no value", key)
}

func getTuneProfileInputFloat(input TuneProfileInput, key string) (*float64, bool) {
	switch key {
	case "weightKG":
		return input.WeightKG, true
	case "frontWeightPct":
		return input.FrontWeightPct, true
	case "powerKW":
		return input.PowerKW, true
	case "torqueNM":
		return input.TorqueNM, true
	case "redlineRPM":
		return input.RedlineRPM, true
	case "frontTirePressure":
		return input.FrontTirePressure, true
	case "rearTirePressure":
		return input.RearTirePressure, true
	case "finalDrive":
		return input.FinalDrive, true
	case "gear1":
		return input.Gear1, true
	case "gear2":
		return input.Gear2, true
	case "gear3":
		return input.Gear3, true
	case "gear4":
		return input.Gear4, true
	case "gear5":
		return input.Gear5, true
	case "gear6":
		return input.Gear6, true
	case "gear7":
		return input.Gear7, true
	case "gear8":
		return input.Gear8, true
	case "gear9":
		return input.Gear9, true
	case "gear10":
		return input.Gear10, true
	case "frontCamber":
		return input.FrontCamber, true
	case "rearCamber":
		return input.RearCamber, true
	case "frontToe":
		return input.FrontToe, true
	case "rearToe":
		return input.RearToe, true
	case "caster":
		return input.Caster, true
	case "frontArb":
		return input.FrontARB, true
	case "rearArb":
		return input.RearARB, true
	case "frontSpring":
		return input.FrontSpring, true
	case "rearSpring":
		return input.RearSpring, true
	case "frontRideHeight":
		return input.FrontRideHeight, true
	case "rearRideHeight":
		return input.RearRideHeight, true
	case "frontRebound":
		return input.FrontRebound, true
	case "rearRebound":
		return input.RearRebound, true
	case "frontBump":
		return input.FrontBump, true
	case "rearBump":
		return input.RearBump, true
	case "frontAero":
		return input.FrontAero, true
	case "rearAero":
		return input.RearAero, true
	case "brakeBalance":
		return input.BrakeBalance, true
	case "brakePressure":
		return input.BrakePressure, true
	case "frontDiffAccel":
		return input.FrontDiffAccel, true
	case "frontDiffDecel":
		return input.FrontDiffDecel, true
	case "rearDiffAccel":
		return input.RearDiffAccel, true
	case "rearDiffDecel":
		return input.RearDiffDecel, true
	case "centerDiffBalance":
		return input.CenterDiffBalance, true
	default:
		return nil, false
	}
}

func sortedKeys(values map[string]bool) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func clamp(value float64, min float64, max float64) float64 {
	if value < min {
		return min
	}
	if value > max {
		return max
	}
	return value
}
