package storage

import (
	"fmt"
)

const tuneToTireInfluenceVersion = "mvp4r-static-v1"

type TuneToTireInfluenceMap struct {
	Version string               `json:"version"`
	Items   []TuneFieldInfluence `json:"items"`
}

type TuneFieldInfluence struct {
	FieldKey      string   `json:"fieldKey"`
	Category      string   `json:"category"`
	LabelZH       string   `json:"labelZh"`
	LabelEN       string   `json:"labelEn"`
	InfluenceType string   `json:"influenceType"`
	Scope         []string `json:"scope"`
	Phases        []string `json:"phases"`
	TireMetrics   []string `json:"tireMetrics"`
	EvidenceKeys  []string `json:"evidenceKeys"`
	SideEffects   []string `json:"sideEffects"`
	Conditions    []string `json:"conditions"`
	SummaryZH     string   `json:"summaryZh"`
	SummaryEN     string   `json:"summaryEn"`
}

func GetTuneToTireInfluenceMap() TuneToTireInfluenceMap {
	items := buildTuneToTireInfluences()
	out := make([]TuneFieldInfluence, len(items))
	copy(out, items)
	return TuneToTireInfluenceMap{Version: tuneToTireInfluenceVersion, Items: out}
}

func ExplainTuneFieldInfluence(fieldKey string) (TuneFieldInfluence, error) {
	for _, item := range buildTuneToTireInfluences() {
		if item.FieldKey == fieldKey {
			return item, nil
		}
	}
	return TuneFieldInfluence{}, fmt.Errorf("unknown tune field influence: %s", fieldKey)
}

func buildTuneToTireInfluences() []TuneFieldInfluence {
	items := []TuneFieldInfluence{
		{
			FieldKey:      "frontTirePressure",
			Category:      "tire",
			LabelZH:       "前胎压",
			LabelEN:       "Front tire pressure",
			InfluenceType: "direct",
			Scope:         []string{"front_axle"},
			Phases:        []string{"all_phases"},
			TireMetrics:   []string{"tire_temp", "combined_slip", "slip_angle"},
			EvidenceKeys:  []string{"front_tire_temp_avg", "front_combined_slip_p90", "front_slip_angle_p90"},
			SideEffects:   []string{"can_increase_tire_temp", "can_reduce_stability"},
			Conditions:    []string{"high_load_only"},
			SummaryZH:     "直接改变前轮接地响应、热管理和横向抓地窗口。",
			SummaryEN:     "Directly changes front tire contact response, heat management, and lateral grip window.",
		},
		{
			FieldKey:      "rearTirePressure",
			Category:      "tire",
			LabelZH:       "后胎压",
			LabelEN:       "Rear tire pressure",
			InfluenceType: "direct",
			Scope:         []string{"rear_axle"},
			Phases:        []string{"all_phases"},
			TireMetrics:   []string{"tire_temp", "combined_slip", "slip_angle", "slip_ratio"},
			EvidenceKeys:  []string{"rear_tire_temp_avg", "rear_combined_slip_p90", "rear_slip_angle_p90", "rear_slip_ratio_p90"},
			SideEffects:   []string{"can_increase_tire_temp", "can_reduce_stability"},
			Conditions:    []string{"high_load_only"},
			SummaryZH:     "直接改变后轮接地响应、热管理、出弯稳定和牵引窗口。",
			SummaryEN:     "Directly changes rear tire contact response, heat management, exit stability, and traction window.",
		},
		{
			FieldKey:      "finalDrive",
			Category:      "gearing",
			LabelZH:       "终传比",
			LabelEN:       "Final drive",
			InfluenceType: "indirect",
			Scope:         []string{"driven_wheels"},
			Phases:        []string{"launch", "corner_exit", "straight_power"},
			TireMetrics:   []string{"slip_ratio", "speed_rpm", "wheel_torque"},
			EvidenceKeys:  []string{"rpm_band_ratio", "driven_slip_ratio_p90", "gear_power_strategy"},
			SideEffects:   []string{"can_affect_acceleration", "can_affect_top_speed"},
			Conditions:    []string{"throttle_sensitive", "drivetrain_sensitive", "unlocked_only"},
			SummaryZH:     "通过整套齿比改变驱动轮轮上扭矩和发动机转速落点。",
			SummaryEN:     "Changes driven-wheel torque and engine RPM placement through the whole gear set.",
		},
		{
			FieldKey:      "frontCamber",
			Category:      "alignment",
			LabelZH:       "前外倾角",
			LabelEN:       "Front camber",
			InfluenceType: "direct",
			Scope:         []string{"front_axle"},
			Phases:        []string{"sustained_cornering", "high_speed_corner"},
			TireMetrics:   []string{"slip_angle", "combined_slip", "tire_temp", "g_force"},
			EvidenceKeys:  []string{"front_slip_angle_p90", "front_combined_slip_p90", "front_tire_temp_avg", "lateral_g_p90"},
			SideEffects:   []string{"can_reduce_stability", "can_mask_camber_issue"},
			Conditions:    []string{"high_load_only"},
			SummaryZH:     "直接影响前轮过弯接地形态，主要看持续转向时的滑移角和综合滑移。",
			SummaryEN:     "Directly affects front tire contact shape in corners, mainly visible through slip angle and combined slip under sustained steering.",
		},
		{
			FieldKey:      "rearCamber",
			Category:      "alignment",
			LabelZH:       "后外倾角",
			LabelEN:       "Rear camber",
			InfluenceType: "direct",
			Scope:         []string{"rear_axle"},
			Phases:        []string{"sustained_cornering", "corner_exit", "high_speed_corner"},
			TireMetrics:   []string{"slip_angle", "combined_slip", "tire_temp", "g_force"},
			EvidenceKeys:  []string{"rear_slip_angle_p90", "rear_combined_slip_p90", "rear_tire_temp_avg", "lateral_g_p90"},
			SideEffects:   []string{"can_reduce_stability", "can_mask_camber_issue"},
			Conditions:    []string{"high_load_only"},
			SummaryZH:     "直接影响后轮过弯接地形态和出弯稳定。",
			SummaryEN:     "Directly affects rear tire contact shape in corners and exit stability.",
		},
		{
			FieldKey:      "frontToe",
			Category:      "alignment",
			LabelZH:       "前束角",
			LabelEN:       "Front toe",
			InfluenceType: "direct",
			Scope:         []string{"front_axle"},
			Phases:        []string{"corner_entry", "sustained_cornering"},
			TireMetrics:   []string{"slip_angle", "yaw_response", "tire_temp"},
			EvidenceKeys:  []string{"steer_response", "front_slip_angle_p90", "front_tire_temp_avg"},
			SideEffects:   []string{"can_reduce_stability", "can_increase_tire_temp"},
			Conditions:    []string{"speed_sensitive"},
			SummaryZH:     "直接改变前轮初段转向响应和直线稳定性。",
			SummaryEN:     "Directly changes front initial steering response and straight-line stability.",
		},
		{
			FieldKey:      "rearToe",
			Category:      "alignment",
			LabelZH:       "后束角",
			LabelEN:       "Rear toe",
			InfluenceType: "direct",
			Scope:         []string{"rear_axle"},
			Phases:        []string{"corner_entry", "sustained_cornering", "high_speed_corner"},
			TireMetrics:   []string{"slip_angle", "yaw_response", "tire_temp"},
			EvidenceKeys:  []string{"yaw_rate_p90", "rear_slip_angle_p90", "rear_tire_temp_avg"},
			SideEffects:   []string{"can_create_oversteer", "can_increase_tire_temp"},
			Conditions:    []string{"speed_sensitive"},
			SummaryZH:     "直接改变后轮稳定与车辆旋转响应。",
			SummaryEN:     "Directly changes rear stability and vehicle rotation response.",
		},
		{
			FieldKey:      "caster",
			Category:      "alignment",
			LabelZH:       "前轮后倾角",
			LabelEN:       "Front caster",
			InfluenceType: "direct",
			Scope:         []string{"front_axle"},
			Phases:        []string{"corner_entry", "sustained_cornering"},
			TireMetrics:   []string{"slip_angle", "yaw_response", "g_force"},
			EvidenceKeys:  []string{"front_slip_angle_p90", "steer_response", "lateral_g_p90"},
			SideEffects:   []string{"can_reduce_stability"},
			Conditions:    []string{"speed_sensitive"},
			SummaryZH:     "通过转向时的动态外倾变化影响前轮抓地和回正感。",
			SummaryEN:     "Influences front grip and self-centering through dynamic camber gain while steering.",
		},
		{
			FieldKey:      "frontArb",
			Category:      "antiroll",
			LabelZH:       "前防倾杆",
			LabelEN:       "Front anti-roll bar",
			InfluenceType: "indirect",
			Scope:         []string{"front_axle"},
			Phases:        []string{"corner_entry", "sustained_cornering", "high_speed_corner"},
			TireMetrics:   []string{"combined_slip", "slip_angle", "g_force", "suspension_offset"},
			EvidenceKeys:  []string{"front_combined_slip_p90", "front_rear_slip_delta", "lateral_g_p90", "front_suspension_offset_p90"},
			SideEffects:   []string{"can_reduce_opposite_axle_grip", "can_create_understeer"},
			Conditions:    []string{"high_load_only"},
			SummaryZH:     "通过横向载荷转移间接影响前轮横向抓地和前后平衡。",
			SummaryEN:     "Indirectly changes front lateral grip and axle balance through lateral load transfer.",
		},
		{
			FieldKey:      "rearArb",
			Category:      "antiroll",
			LabelZH:       "后防倾杆",
			LabelEN:       "Rear anti-roll bar",
			InfluenceType: "indirect",
			Scope:         []string{"rear_axle"},
			Phases:        []string{"sustained_cornering", "corner_exit", "high_speed_corner"},
			TireMetrics:   []string{"combined_slip", "slip_angle", "g_force", "suspension_offset"},
			EvidenceKeys:  []string{"rear_combined_slip_p90", "front_rear_slip_delta", "lateral_g_p90", "rear_suspension_offset_p90"},
			SideEffects:   []string{"can_reduce_opposite_axle_grip", "can_create_oversteer"},
			Conditions:    []string{"high_load_only"},
			SummaryZH:     "通过横向载荷转移间接影响后轮横向抓地、旋转和出弯稳定。",
			SummaryEN:     "Indirectly changes rear lateral grip, rotation, and exit stability through lateral load transfer.",
		},
		{
			FieldKey:      "frontSpring",
			Category:      "springs",
			LabelZH:       "前弹簧",
			LabelEN:       "Front spring",
			InfluenceType: "indirect",
			Scope:         []string{"front_axle"},
			Phases:        []string{"braking", "corner_entry", "sustained_cornering"},
			TireMetrics:   []string{"combined_slip", "suspension_offset", "g_force"},
			EvidenceKeys:  []string{"front_suspension_offset_p90", "front_combined_slip_p90", "brake_avg"},
			SideEffects:   []string{"can_create_understeer", "can_reduce_stability"},
			Conditions:    []string{"high_load_only"},
			SummaryZH:     "通过俯仰、侧倾和悬挂行程间接影响前轮接地稳定。",
			SummaryEN:     "Indirectly affects front tire contact stability through pitch, roll, and suspension travel.",
		},
		{
			FieldKey:      "rearSpring",
			Category:      "springs",
			LabelZH:       "后弹簧",
			LabelEN:       "Rear spring",
			InfluenceType: "indirect",
			Scope:         []string{"rear_axle"},
			Phases:        []string{"corner_exit", "sustained_cornering", "straight_power"},
			TireMetrics:   []string{"combined_slip", "suspension_offset", "slip_ratio", "g_force"},
			EvidenceKeys:  []string{"rear_suspension_offset_p90", "rear_combined_slip_p90", "rear_slip_ratio_p90"},
			SideEffects:   []string{"can_create_oversteer", "can_reduce_stability"},
			Conditions:    []string{"high_load_only", "throttle_sensitive"},
			SummaryZH:     "通过后轴平台和重量转移间接影响后轮稳定与牵引。",
			SummaryEN:     "Indirectly affects rear stability and traction through rear platform control and weight transfer.",
		},
		{
			FieldKey:      "frontRideHeight",
			Category:      "springs",
			LabelZH:       "前车高",
			LabelEN:       "Front ride height",
			InfluenceType: "indirect",
			Scope:         []string{"front_axle"},
			Phases:        []string{"braking", "corner_entry", "high_speed_corner"},
			TireMetrics:   []string{"suspension_offset", "combined_slip", "g_force"},
			EvidenceKeys:  []string{"front_suspension_offset_p90", "front_combined_slip_p90", "speed_kmh"},
			SideEffects:   []string{"can_reduce_stability", "can_affect_top_speed"},
			Conditions:    []string{"aero_speed_sensitive", "high_load_only"},
			SummaryZH:     "通过悬挂余量、重心和高速平台间接影响前轮接地。",
			SummaryEN:     "Indirectly affects front tire contact through travel margin, center of gravity, and high-speed platform.",
		},
		{
			FieldKey:      "rearRideHeight",
			Category:      "springs",
			LabelZH:       "后车高",
			LabelEN:       "Rear ride height",
			InfluenceType: "indirect",
			Scope:         []string{"rear_axle"},
			Phases:        []string{"corner_exit", "straight_power", "high_speed_corner"},
			TireMetrics:   []string{"suspension_offset", "combined_slip", "slip_ratio", "g_force"},
			EvidenceKeys:  []string{"rear_suspension_offset_p90", "rear_combined_slip_p90", "rear_slip_ratio_p90"},
			SideEffects:   []string{"can_reduce_stability", "can_affect_top_speed"},
			Conditions:    []string{"aero_speed_sensitive", "throttle_sensitive", "high_load_only"},
			SummaryZH:     "通过悬挂余量、重量转移和高速平台间接影响后轮接地与牵引。",
			SummaryEN:     "Indirectly affects rear tire contact and traction through travel margin, weight transfer, and high-speed platform.",
		},
		{
			FieldKey:      "frontRebound",
			Category:      "damping",
			LabelZH:       "前回弹阻尼",
			LabelEN:       "Front rebound",
			InfluenceType: "indirect",
			Scope:         []string{"front_axle"},
			Phases:        []string{"corner_entry", "sustained_cornering", "transition"},
			TireMetrics:   []string{"combined_slip", "suspension_offset", "yaw_response"},
			EvidenceKeys:  []string{"front_combined_slip_p90", "front_suspension_offset_p90", "yaw_rate_p90"},
			SideEffects:   []string{"can_reduce_stability", "can_create_understeer"},
			Conditions:    []string{"high_load_only", "speed_sensitive"},
			SummaryZH:     "通过悬挂伸展速度间接影响前轮转向响应和过渡稳定。",
			SummaryEN:     "Indirectly affects front response and transition stability through suspension extension speed.",
		},
		{
			FieldKey:      "rearRebound",
			Category:      "damping",
			LabelZH:       "后回弹阻尼",
			LabelEN:       "Rear rebound",
			InfluenceType: "indirect",
			Scope:         []string{"rear_axle"},
			Phases:        []string{"corner_entry", "corner_exit", "transition"},
			TireMetrics:   []string{"combined_slip", "suspension_offset", "yaw_response"},
			EvidenceKeys:  []string{"rear_combined_slip_p90", "rear_suspension_offset_p90", "yaw_rate_p90"},
			SideEffects:   []string{"can_reduce_stability", "can_create_oversteer"},
			Conditions:    []string{"high_load_only", "speed_sensitive"},
			SummaryZH:     "通过后悬挂伸展速度间接影响车尾响应和出弯稳定。",
			SummaryEN:     "Indirectly affects rear response and exit stability through rear suspension extension speed.",
		},
		{
			FieldKey:      "frontBump",
			Category:      "damping",
			LabelZH:       "前压缩阻尼",
			LabelEN:       "Front bump",
			InfluenceType: "indirect",
			Scope:         []string{"front_axle"},
			Phases:        []string{"braking", "corner_entry", "kerb_impact"},
			TireMetrics:   []string{"combined_slip", "suspension_offset", "g_force"},
			EvidenceKeys:  []string{"front_suspension_offset_p90", "front_combined_slip_p90", "brake_avg"},
			SideEffects:   []string{"can_reduce_stability", "can_create_understeer"},
			Conditions:    []string{"brake_sensitive", "high_load_only"},
			SummaryZH:     "通过前悬挂压缩速度间接影响带刹入弯和颠簸接地。",
			SummaryEN:     "Indirectly affects braking entry and bump compliance through front compression speed.",
		},
		{
			FieldKey:      "rearBump",
			Category:      "damping",
			LabelZH:       "后压缩阻尼",
			LabelEN:       "Rear bump",
			InfluenceType: "indirect",
			Scope:         []string{"rear_axle"},
			Phases:        []string{"corner_exit", "straight_power", "kerb_impact"},
			TireMetrics:   []string{"combined_slip", "suspension_offset", "slip_ratio"},
			EvidenceKeys:  []string{"rear_suspension_offset_p90", "rear_combined_slip_p90", "rear_slip_ratio_p90"},
			SideEffects:   []string{"can_reduce_stability", "can_create_oversteer"},
			Conditions:    []string{"throttle_sensitive", "high_load_only"},
			SummaryZH:     "通过后悬挂压缩速度间接影响出弯牵引和颠簸稳定。",
			SummaryEN:     "Indirectly affects exit traction and bump stability through rear compression speed.",
		},
		{
			FieldKey:      "frontAero",
			Category:      "aero",
			LabelZH:       "前下压力",
			LabelEN:       "Front aero",
			InfluenceType: "indirect",
			Scope:         []string{"front_axle"},
			Phases:        []string{"high_speed_corner", "corner_entry"},
			TireMetrics:   []string{"combined_slip", "slip_angle", "g_force"},
			EvidenceKeys:  []string{"speed_kmh", "front_combined_slip_p90", "lateral_g_p90"},
			SideEffects:   []string{"can_affect_top_speed", "can_increase_tire_temp"},
			Conditions:    []string{"aero_speed_sensitive"},
			SummaryZH:     "随速度增加前轮法向载荷，主要影响高速入弯和高速弯前轴抓地。",
			SummaryEN:     "Adds speed-dependent front vertical load, mostly affecting high-speed entry and front grip.",
		},
		{
			FieldKey:      "rearAero",
			Category:      "aero",
			LabelZH:       "后下压力",
			LabelEN:       "Rear aero",
			InfluenceType: "indirect",
			Scope:         []string{"rear_axle"},
			Phases:        []string{"high_speed_corner", "corner_exit"},
			TireMetrics:   []string{"combined_slip", "slip_angle", "g_force"},
			EvidenceKeys:  []string{"speed_kmh", "rear_combined_slip_p90", "lateral_g_p90"},
			SideEffects:   []string{"can_affect_top_speed", "can_increase_tire_temp"},
			Conditions:    []string{"aero_speed_sensitive"},
			SummaryZH:     "随速度增加后轮法向载荷，主要影响高速稳定和高速出弯后轴抓地。",
			SummaryEN:     "Adds speed-dependent rear vertical load, mostly affecting high-speed stability and rear grip.",
		},
		{
			FieldKey:      "aeroBalance",
			Category:      "aero",
			LabelZH:       "空力平衡",
			LabelEN:       "Aero balance",
			InfluenceType: "indirect",
			Scope:         []string{"front_axle", "rear_axle"},
			Phases:        []string{"high_speed_corner"},
			TireMetrics:   []string{"combined_slip", "slip_angle", "g_force"},
			EvidenceKeys:  []string{"speed_kmh", "front_rear_slip_delta", "lateral_g_p90"},
			SideEffects:   []string{"can_affect_top_speed", "can_create_understeer", "can_create_oversteer"},
			Conditions:    []string{"aero_speed_sensitive"},
			SummaryZH:     "改变高速时前后轴下压力分配，影响高速推头或甩尾倾向。",
			SummaryEN:     "Changes high-speed aero load split, influencing high-speed understeer or oversteer tendency.",
		},
		{
			FieldKey:      "brakeBalance",
			Category:      "brake",
			LabelZH:       "刹车平衡",
			LabelEN:       "Brake balance",
			InfluenceType: "indirect",
			Scope:         []string{"front_axle", "rear_axle"},
			Phases:        []string{"braking", "corner_entry"},
			TireMetrics:   []string{"brake_slip", "slip_ratio", "combined_slip"},
			EvidenceKeys:  []string{"front_brake_lockup", "rear_brake_lockup", "brake_avg", "front_rear_slip_delta"},
			SideEffects:   []string{"can_increase_lockup_risk", "can_create_understeer", "can_create_oversteer"},
			Conditions:    []string{"brake_sensitive"},
			SummaryZH:     "通过制动力分配间接改变四轮纵向滑移和带刹入弯平衡。",
			SummaryEN:     "Indirectly changes wheel longitudinal slip and braking-entry balance through brake force distribution.",
		},
		{
			FieldKey:      "brakePressure",
			Category:      "brake",
			LabelZH:       "刹车压力",
			LabelEN:       "Brake pressure",
			InfluenceType: "indirect",
			Scope:         []string{"all_wheels"},
			Phases:        []string{"braking", "corner_entry"},
			TireMetrics:   []string{"brake_slip", "slip_ratio", "combined_slip"},
			EvidenceKeys:  []string{"max_brake_slip", "brake_avg", "decel_g_p90"},
			SideEffects:   []string{"can_increase_lockup_risk", "can_reduce_stability"},
			Conditions:    []string{"brake_sensitive"},
			SummaryZH:     "通过制动力建立速度影响四轮纵向抓地是否被过快用尽。",
			SummaryEN:     "Influences whether longitudinal grip is consumed too quickly by changing brake force buildup.",
		},
		{
			FieldKey:      "frontDiffAccel",
			Category:      "differential",
			LabelZH:       "前加速差速",
			LabelEN:       "Front diff accel",
			InfluenceType: "indirect",
			Scope:         []string{"driven_wheels", "front_axle"},
			Phases:        []string{"corner_exit", "straight_power"},
			TireMetrics:   []string{"slip_ratio", "combined_slip", "yaw_response"},
			EvidenceKeys:  []string{"front_slip_ratio_p90", "driven_slip_ratio_p90", "throttle_avg"},
			SideEffects:   []string{"can_create_understeer", "can_reduce_stability"},
			Conditions:    []string{"throttle_sensitive", "drivetrain_sensitive", "unlocked_only"},
			SummaryZH:     "加速时通过前差速锁止改变前驱动轮纵向滑移和出弯转向。",
			SummaryEN:     "Changes front driven tire slip and exit steering through front diff lock under throttle.",
		},
		{
			FieldKey:      "frontDiffDecel",
			Category:      "differential",
			LabelZH:       "前减速差速",
			LabelEN:       "Front diff decel",
			InfluenceType: "indirect",
			Scope:         []string{"driven_wheels", "front_axle"},
			Phases:        []string{"braking", "corner_entry", "coast"},
			TireMetrics:   []string{"slip_ratio", "combined_slip", "yaw_response"},
			EvidenceKeys:  []string{"front_combined_slip_p90", "brake_avg", "throttle_avg"},
			SideEffects:   []string{"can_create_understeer", "can_reduce_stability"},
			Conditions:    []string{"brake_sensitive", "drivetrain_sensitive", "unlocked_only"},
			SummaryZH:     "松油或制动时通过前差速锁止影响入弯稳定和前轮滑移。",
			SummaryEN:     "Changes entry stability and front tire slip through front diff lock while coasting or braking.",
		},
		{
			FieldKey:      "rearDiffAccel",
			Category:      "differential",
			LabelZH:       "后加速差速",
			LabelEN:       "Rear diff accel",
			InfluenceType: "indirect",
			Scope:         []string{"driven_wheels", "rear_axle"},
			Phases:        []string{"corner_exit", "straight_power"},
			TireMetrics:   []string{"slip_ratio", "combined_slip", "yaw_response"},
			EvidenceKeys:  []string{"rear_slip_ratio_p90", "driven_slip_ratio_p90", "throttle_avg"},
			SideEffects:   []string{"can_create_oversteer", "can_reduce_stability"},
			Conditions:    []string{"throttle_sensitive", "drivetrain_sensitive", "unlocked_only"},
			SummaryZH:     "加速时通过后差速锁止改变后驱动轮牵引、甩尾倾向和出弯稳定。",
			SummaryEN:     "Changes rear driven tire traction, oversteer tendency, and exit stability through rear diff lock under throttle.",
		},
		{
			FieldKey:      "rearDiffDecel",
			Category:      "differential",
			LabelZH:       "后减速差速",
			LabelEN:       "Rear diff decel",
			InfluenceType: "indirect",
			Scope:         []string{"driven_wheels", "rear_axle"},
			Phases:        []string{"braking", "corner_entry", "coast"},
			TireMetrics:   []string{"slip_ratio", "combined_slip", "yaw_response"},
			EvidenceKeys:  []string{"rear_combined_slip_p90", "brake_avg", "throttle_avg"},
			SideEffects:   []string{"can_create_oversteer", "can_reduce_stability"},
			Conditions:    []string{"brake_sensitive", "drivetrain_sensitive", "unlocked_only"},
			SummaryZH:     "松油或制动时通过后差速锁止影响车尾稳定和入弯旋转。",
			SummaryEN:     "Changes rear stability and entry rotation through rear diff lock while coasting or braking.",
		},
		{
			FieldKey:      "centerDiffBalance",
			Category:      "differential",
			LabelZH:       "中央差速分配",
			LabelEN:       "Center diff balance",
			InfluenceType: "indirect",
			Scope:         []string{"driven_wheels", "front_axle", "rear_axle"},
			Phases:        []string{"launch", "corner_exit", "straight_power", "high_speed_corner"},
			TireMetrics:   []string{"slip_ratio", "combined_slip", "yaw_response"},
			EvidenceKeys:  []string{"front_slip_ratio_p90", "rear_slip_ratio_p90", "front_rear_slip_delta"},
			SideEffects:   []string{"can_create_understeer", "can_create_oversteer"},
			Conditions:    []string{"drivetrain_sensitive", "throttle_sensitive", "unlocked_only"},
			SummaryZH:     "改变 AWD 前后驱动力分配，影响四轮纵向滑移与出弯姿态。",
			SummaryEN:     "Changes AWD front/rear torque split, affecting driven-tire slip and exit attitude.",
		},
	}
	for gear := 1; gear <= 10; gear++ {
		items = append(items, TuneFieldInfluence{
			FieldKey:      fmt.Sprintf("gear%d", gear),
			Category:      "gearing",
			LabelZH:       fmt.Sprintf("%d 挡齿比", gear),
			LabelEN:       fmt.Sprintf("Gear %d ratio", gear),
			InfluenceType: "indirect",
			Scope:         []string{"driven_wheels"},
			Phases:        []string{"corner_exit", "straight_power"},
			TireMetrics:   []string{"slip_ratio", "speed_rpm", "wheel_torque"},
			EvidenceKeys:  []string{fmt.Sprintf("gear_%d_rpm_band", gear), fmt.Sprintf("gear_%d_speed_range", gear), "driven_slip_ratio_p90"},
			SideEffects:   []string{"can_affect_acceleration", "can_affect_top_speed"},
			Conditions:    []string{"throttle_sensitive", "drivetrain_sensitive", "unlocked_only"},
			SummaryZH:     fmt.Sprintf("通过 %d 挡轮上扭矩和换挡后转速影响驱动轮牵引与加速。", gear),
			SummaryEN:     fmt.Sprintf("Affects driven-tire traction and acceleration through wheel torque and post-shift RPM in gear %d.", gear),
		})
	}
	return items
}
