// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeRoadStrategySessions(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeRoadStrategySessions'](arg1, arg2);
}

export function AnalyzeSessionBenchmarkRuns(arg1) {
  return window['go']['main']['App']['AnalyzeSessionBenchmarkRuns'](arg1);
}

export function ApplyRoadStaticTuneBaseline(arg1) {
  return window['go']['main']['App']['ApplyRoadStaticTuneBaseline'](arg1);
}

export function ApplyTunePlanDraft(arg1) {
  return window['go']['main']['App']['ApplyTunePlanDraft'](arg1);
}

export function BindTelemetrySessionTuneProfile(arg1, arg2) {
  return window['go']['main']['App']['BindTelemetrySessionTuneProfile'](arg1, arg2);
}

export function CleanupLegacySessions() {
  return window['go']['main']['App']['CleanupLegacySessions']();
}

export function ClearTuneHarvestCandidates() {
  return window['go']['main']['App']['ClearTuneHarvestCandidates']();
}

export function CompareRoadEvaluations(arg1, arg2) {
  return window['go']['main']['App']['CompareRoadEvaluations'](arg1, arg2);
}

export function CompareTelemetrySessions(arg1, arg2) {
  return window['go']['main']['App']['CompareTelemetrySessions'](arg1, arg2);
}

export function CreateBenchmarkTrack(arg1) {
  return window['go']['main']['App']['CreateBenchmarkTrack'](arg1);
}

export function CreateBenchmarkTrackFromSession(arg1, arg2) {
  return window['go']['main']['App']['CreateBenchmarkTrackFromSession'](arg1, arg2);
}

export function CreateRuleThresholdProfile(arg1) {
  return window['go']['main']['App']['CreateRuleThresholdProfile'](arg1);
}

export function CreateTuneProfile(arg1) {
  return window['go']['main']['App']['CreateTuneProfile'](arg1);
}

export function DeleteAllRecommendedCars() {
  return window['go']['main']['App']['DeleteAllRecommendedCars']();
}

export function DeleteBenchmarkTrack(arg1) {
  return window['go']['main']['App']['DeleteBenchmarkTrack'](arg1);
}

export function DeleteRecommendedCar(arg1) {
  return window['go']['main']['App']['DeleteRecommendedCar'](arg1);
}

export function DeleteRuleThresholdProfile(arg1) {
  return window['go']['main']['App']['DeleteRuleThresholdProfile'](arg1);
}

export function DeleteTelemetrySession(arg1) {
  return window['go']['main']['App']['DeleteTelemetrySession'](arg1);
}

export function DeleteTireRegressionSample(arg1) {
  return window['go']['main']['App']['DeleteTireRegressionSample'](arg1);
}

export function DeleteTrackBaselineRun(arg1) {
  return window['go']['main']['App']['DeleteTrackBaselineRun'](arg1);
}

export function DeleteTuneProfile(arg1) {
  return window['go']['main']['App']['DeleteTuneProfile'](arg1);
}

export function DuplicateTuneProfile(arg1, arg2) {
  return window['go']['main']['App']['DuplicateTuneProfile'](arg1, arg2);
}

export function EvaluateRoadSession(arg1) {
  return window['go']['main']['App']['EvaluateRoadSession'](arg1);
}

export function ExplainTuneFieldInfluence(arg1) {
  return window['go']['main']['App']['ExplainTuneFieldInfluence'](arg1);
}

export function ExportRecommendedCarsFile(arg1) {
  return window['go']['main']['App']['ExportRecommendedCarsFile'](arg1);
}

export function ExtractBenchmarkTrackFromSession(arg1) {
  return window['go']['main']['App']['ExtractBenchmarkTrackFromSession'](arg1);
}

export function FindSimilarBenchmarkTracks(arg1) {
  return window['go']['main']['App']['FindSimilarBenchmarkTracks'](arg1);
}

export function GenerateRoadStaticTuneBaseline(arg1) {
  return window['go']['main']['App']['GenerateRoadStaticTuneBaseline'](arg1);
}

export function GenerateTuningReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateTuningReport'](arg1, arg2);
}

export function GetActiveTuneProfile() {
  return window['go']['main']['App']['GetActiveTuneProfile']();
}

export function GetBenchmarkTrack(arg1) {
  return window['go']['main']['App']['GetBenchmarkTrack'](arg1);
}

export function GetCurrentTelemetry() {
  return window['go']['main']['App']['GetCurrentTelemetry']();
}

export function GetDetectedEvents() {
  return window['go']['main']['App']['GetDetectedEvents']();
}

export function GetNetworkInterfaces() {
  return window['go']['main']['App']['GetNetworkInterfaces']();
}

export function GetProfessionalPipelineConfig() {
  return window['go']['main']['App']['GetProfessionalPipelineConfig']();
}

export function GetProfessionalTuningDiagnostic() {
  return window['go']['main']['App']['GetProfessionalTuningDiagnostic']();
}

export function GetQuickDiagnostic() {
  return window['go']['main']['App']['GetQuickDiagnostic']();
}

export function GetRecentTelemetry(arg1) {
  return window['go']['main']['App']['GetRecentTelemetry'](arg1);
}

export function GetRetestEvaluation(arg1) {
  return window['go']['main']['App']['GetRetestEvaluation'](arg1);
}

export function GetRoadTuningDecision(arg1) {
  return window['go']['main']['App']['GetRoadTuningDecision'](arg1);
}

export function GetRoadTuningKnowledgeStatus() {
  return window['go']['main']['App']['GetRoadTuningKnowledgeStatus']();
}

export function GetSessionEvents(arg1) {
  return window['go']['main']['App']['GetSessionEvents'](arg1);
}

export function GetSessionIssueSummary(arg1) {
  return window['go']['main']['App']['GetSessionIssueSummary'](arg1);
}

export function GetSessionTelemetrySamples(arg1, arg2) {
  return window['go']['main']['App']['GetSessionTelemetrySamples'](arg1, arg2);
}

export function GetTelemetryReplayStatus() {
  return window['go']['main']['App']['GetTelemetryReplayStatus']();
}

export function GetTelemetrySession(arg1) {
  return window['go']['main']['App']['GetTelemetrySession'](arg1);
}

export function GetTelemetryStatus() {
  return window['go']['main']['App']['GetTelemetryStatus']();
}

export function GetTestConditionDefaults() {
  return window['go']['main']['App']['GetTestConditionDefaults']();
}

export function GetTireDiagnosticSnapshot() {
  return window['go']['main']['App']['GetTireDiagnosticSnapshot']();
}

export function GetTireIssueAdvice() {
  return window['go']['main']['App']['GetTireIssueAdvice']();
}

export function GetTireIssueAnalysis() {
  return window['go']['main']['App']['GetTireIssueAnalysis']();
}

export function GetTireModelDiagnostic() {
  return window['go']['main']['App']['GetTireModelDiagnostic']();
}

export function GetTireRegressionSample(arg1) {
  return window['go']['main']['App']['GetTireRegressionSample'](arg1);
}

export function GetTrackProfile(arg1) {
  return window['go']['main']['App']['GetTrackProfile'](arg1);
}

export function GetTunePlanDraft(arg1) {
  return window['go']['main']['App']['GetTunePlanDraft'](arg1);
}

export function GetTuneProfile(arg1) {
  return window['go']['main']['App']['GetTuneProfile'](arg1);
}

export function GetTuneToTireInfluenceMap() {
  return window['go']['main']['App']['GetTuneToTireInfluenceMap']();
}

export function GetTuneWebServerStatus() {
  return window['go']['main']['App']['GetTuneWebServerStatus']();
}

export function ListBenchmarkRuns(arg1, arg2) {
  return window['go']['main']['App']['ListBenchmarkRuns'](arg1, arg2);
}

export function ListBenchmarkTracks() {
  return window['go']['main']['App']['ListBenchmarkTracks']();
}

export function ListFH6Cars() {
  return window['go']['main']['App']['ListFH6Cars']();
}

export function ListRecommendedCars() {
  return window['go']['main']['App']['ListRecommendedCars']();
}

export function ListRuleThresholdProfiles() {
  return window['go']['main']['App']['ListRuleThresholdProfiles']();
}

export function ListStrategyTemplates() {
  return window['go']['main']['App']['ListStrategyTemplates']();
}

export function ListTelemetrySessions(arg1) {
  return window['go']['main']['App']['ListTelemetrySessions'](arg1);
}

export function ListTireRegressionSamples() {
  return window['go']['main']['App']['ListTireRegressionSamples']();
}

export function ListTrackProfiles() {
  return window['go']['main']['App']['ListTrackProfiles']();
}

export function ListTuneAdjustmentExplanations() {
  return window['go']['main']['App']['ListTuneAdjustmentExplanations']();
}

export function ListTuneHarvestCandidates(arg1, arg2) {
  return window['go']['main']['App']['ListTuneHarvestCandidates'](arg1, arg2);
}

export function ListTuneProfileSessionStats() {
  return window['go']['main']['App']['ListTuneProfileSessionStats']();
}

export function ListTuneProfileSnapshots(arg1) {
  return window['go']['main']['App']['ListTuneProfileSnapshots'](arg1);
}

export function ListTuneProfiles() {
  return window['go']['main']['App']['ListTuneProfiles']();
}

export function ListTuneProfilesForVehicle(arg1, arg2) {
  return window['go']['main']['App']['ListTuneProfilesForVehicle'](arg1, arg2);
}

export function ListTuningModelPipelines() {
  return window['go']['main']['App']['ListTuningModelPipelines']();
}

export function ListUpgradeUnlockRules() {
  return window['go']['main']['App']['ListUpgradeUnlockRules']();
}

export function LoadRecommendedCarsFileSelection() {
  return window['go']['main']['App']['LoadRecommendedCarsFileSelection']();
}

export function MergeBenchmarkTrackInput(arg1, arg2) {
  return window['go']['main']['App']['MergeBenchmarkTrackInput'](arg1, arg2);
}

export function PauseTelemetryReplay() {
  return window['go']['main']['App']['PauseTelemetryReplay']();
}

export function ReextractBenchmarkTrack(arg1, arg2) {
  return window['go']['main']['App']['ReextractBenchmarkTrack'](arg1, arg2);
}

export function ReloadTuningKnowledge() {
  return window['go']['main']['App']['ReloadTuningKnowledge']();
}

export function RenameBenchmarkTrack(arg1, arg2) {
  return window['go']['main']['App']['RenameBenchmarkTrack'](arg1, arg2);
}

export function ReplayTelemetrySession(arg1, arg2) {
  return window['go']['main']['App']['ReplayTelemetrySession'](arg1, arg2);
}

export function ResetRuleThresholdProfile(arg1) {
  return window['go']['main']['App']['ResetRuleThresholdProfile'](arg1);
}

export function ResolveCarNameByOrdinal(arg1) {
  return window['go']['main']['App']['ResolveCarNameByOrdinal'](arg1);
}

export function RestoreTuneProfileSnapshot(arg1) {
  return window['go']['main']['App']['RestoreTuneProfileSnapshot'](arg1);
}

export function ResumeTelemetryReplay() {
  return window['go']['main']['App']['ResumeTelemetryReplay']();
}

export function RunAllTireRegressionSamples() {
  return window['go']['main']['App']['RunAllTireRegressionSamples']();
}

export function RunTireRegressionSample(arg1) {
  return window['go']['main']['App']['RunTireRegressionSample'](arg1);
}

export function RunTuneHarvest(arg1) {
  return window['go']['main']['App']['RunTuneHarvest'](arg1);
}

export function RunTuningModelPipeline(arg1) {
  return window['go']['main']['App']['RunTuningModelPipeline'](arg1);
}

export function SaveProfessionalPipelineConfig(arg1) {
  return window['go']['main']['App']['SaveProfessionalPipelineConfig'](arg1);
}

export function SaveRecommendedCar(arg1) {
  return window['go']['main']['App']['SaveRecommendedCar'](arg1);
}

export function SaveRecommendedCarRecord(arg1, arg2) {
  return window['go']['main']['App']['SaveRecommendedCarRecord'](arg1, arg2);
}

export function SaveRecommendedCarsFile(arg1, arg2) {
  return window['go']['main']['App']['SaveRecommendedCarsFile'](arg1, arg2);
}

export function SaveTestConditionDefaults(arg1) {
  return window['go']['main']['App']['SaveTestConditionDefaults'](arg1);
}

export function SaveTireRegressionSample(arg1) {
  return window['go']['main']['App']['SaveTireRegressionSample'](arg1);
}

export function SaveTrackBaselineCapture(arg1) {
  return window['go']['main']['App']['SaveTrackBaselineCapture'](arg1);
}

export function SaveTrackBaselineCaptureAuto(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTrackBaselineCaptureAuto'](arg1, arg2, arg3);
}

export function SearchTuneHarvestCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchTuneHarvestCandidates'](arg1, arg2, arg3);
}

export function SeekTelemetryReplay(arg1) {
  return window['go']['main']['App']['SeekTelemetryReplay'](arg1);
}

export function SetActiveTuneProfile(arg1) {
  return window['go']['main']['App']['SetActiveTuneProfile'](arg1);
}

export function StartProfessionalTelemetry(arg1, arg2) {
  return window['go']['main']['App']['StartProfessionalTelemetry'](arg1, arg2);
}

export function StartQuickTelemetry(arg1, arg2) {
  return window['go']['main']['App']['StartQuickTelemetry'](arg1, arg2);
}

export function StartTelemetry(arg1, arg2) {
  return window['go']['main']['App']['StartTelemetry'](arg1, arg2);
}

export function StartTelemetryWithConditions(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTelemetryWithConditions'](arg1, arg2, arg3);
}

export function StartTireModelTelemetry(arg1, arg2) {
  return window['go']['main']['App']['StartTireModelTelemetry'](arg1, arg2);
}

export function StartTrackBaselineTelemetry(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTrackBaselineTelemetry'](arg1, arg2, arg3);
}

export function StartTrackCaptureTelemetry(arg1, arg2) {
  return window['go']['main']['App']['StartTrackCaptureTelemetry'](arg1, arg2);
}

export function StartTuneWebServer(arg1) {
  return window['go']['main']['App']['StartTuneWebServer'](arg1);
}

export function StopTelemetry() {
  return window['go']['main']['App']['StopTelemetry']();
}

export function StopTelemetryReplay() {
  return window['go']['main']['App']['StopTelemetryReplay']();
}

export function StopTrackBaselineTelemetry() {
  return window['go']['main']['App']['StopTrackBaselineTelemetry']();
}

export function StopTuneHarvest() {
  return window['go']['main']['App']['StopTuneHarvest']();
}

export function StopTuneWebServer() {
  return window['go']['main']['App']['StopTuneWebServer']();
}

export function UpdateBenchmarkTrack(arg1, arg2) {
  return window['go']['main']['App']['UpdateBenchmarkTrack'](arg1, arg2);
}

export function UpdateRuleThresholdProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateRuleThresholdProfile'](arg1, arg2);
}

export function UpdateTireRegressionSampleExpectation(arg1, arg2) {
  return window['go']['main']['App']['UpdateTireRegressionSampleExpectation'](arg1, arg2);
}

export function UpdateTuneHarvestCandidateStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTuneHarvestCandidateStatus'](arg1, arg2, arg3);
}

export function UpdateTuneProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateTuneProfile'](arg1, arg2);
}
