// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {main} from '../models';
import {telemetry} from '../models';

export function AnalyzeRoadStrategySessions(arg1:Array<number>,arg2:number):Promise<storage.RoadStrategyAnalysis>;

export function AnalyzeSessionBenchmarkRuns(arg1:number):Promise<Array<storage.BenchmarkRun>>;

export function ApplyRoadStaticTuneBaseline(arg1:storage.RoadStaticTuneBaselineApplyInput):Promise<storage.RoadStaticTuneBaselineApplyResult>;

export function ApplyTunePlanDraft(arg1:storage.TunePlanApplyInput):Promise<storage.TunePlanApplyResult>;

export function BindTelemetrySessionTuneProfile(arg1:number,arg2:number):Promise<storage.TelemetrySession>;

export function CleanupLegacySessions():Promise<void>;

export function ClearTuneHarvestCandidates():Promise<number>;

export function CompareRoadEvaluations(arg1:number,arg2:number):Promise<storage.RoadEvaluationComparison>;

export function CompareTelemetrySessions(arg1:number,arg2:number):Promise<storage.SessionComparison>;

export function CreateBenchmarkTrack(arg1:storage.BenchmarkTrackInput):Promise<storage.BenchmarkTrack>;

export function CreateBenchmarkTrackFromSession(arg1:number,arg2:string):Promise<storage.BenchmarkTrack>;

export function CreateRuleThresholdProfile(arg1:storage.RuleThresholdProfileInput):Promise<storage.RuleThresholdProfile>;

export function CreateTuneProfile(arg1:storage.TuneProfileInput):Promise<storage.TuneProfile>;

export function DeleteAllRecommendedCars():Promise<number>;

export function DeleteBenchmarkTrack(arg1:number):Promise<void>;

export function DeleteRecommendedCar(arg1:string):Promise<void>;

export function DeleteRuleThresholdProfile(arg1:number):Promise<void>;

export function DeleteTelemetrySession(arg1:number):Promise<void>;

export function DeleteTireRegressionSample(arg1:string):Promise<void>;

export function DeleteTrackBaselineRun(arg1:number):Promise<void>;

export function DeleteTuneProfile(arg1:number):Promise<void>;

export function DuplicateTuneProfile(arg1:number,arg2:string):Promise<storage.TuneProfile>;

export function EvaluateRoadSession(arg1:number):Promise<storage.RoadSessionEvaluation>;

export function ExplainTuneFieldInfluence(arg1:string):Promise<storage.TuneFieldInfluence>;

export function ExportRecommendedCarsFile(arg1:string):Promise<main.RecommendedCarsFileResult>;

export function ExtractBenchmarkTrackFromSession(arg1:storage.BenchmarkTrackExtractionInput):Promise<storage.BenchmarkTrack>;

export function FindSimilarBenchmarkTracks(arg1:storage.BenchmarkTrackInput):Promise<Array<storage.TrackMergeCandidate>>;

export function GenerateRoadStaticTuneBaseline(arg1:storage.RoadStaticTuneBaselineInput):Promise<storage.RoadStaticTuneBaselineResult>;

export function GenerateTuningReport(arg1:number,arg2:string):Promise<string>;

export function GetActiveTuneProfile():Promise<storage.TuneProfile>;

export function GetBenchmarkTrack(arg1:number):Promise<storage.BenchmarkTrack>;

export function GetCurrentTelemetry():Promise<telemetry.NormalizedTelemetry>;

export function GetDetectedEvents():Promise<Array<telemetry.DetectedEvent>>;

export function GetNetworkInterfaces():Promise<Array<telemetry.NetworkInterface>>;

export function GetProfessionalPipelineConfig():Promise<storage.ProfessionalPipelineConfig>;

export function GetProfessionalTuningDiagnostic():Promise<storage.ProfessionalTuningDiagnostic>;

export function GetQuickDiagnostic():Promise<storage.QuickDiagnostic>;

export function GetRecentTelemetry(arg1:number):Promise<Array<telemetry.NormalizedTelemetry>>;

export function GetRetestEvaluation(arg1:number):Promise<storage.RetestEvaluation>;

export function GetRoadTuningDecision(arg1:number):Promise<storage.RoadTuningDecision>;

export function GetRoadTuningKnowledgeStatus():Promise<storage.RoadTuningKnowledgeStatus>;

export function GetSessionEvents(arg1:number):Promise<Array<telemetry.DetectedEvent>>;

export function GetSessionIssueSummary(arg1:number):Promise<storage.SessionIssueSummary>;

export function GetSessionTelemetrySamples(arg1:number,arg2:number):Promise<Array<telemetry.NormalizedTelemetry>>;

export function GetTelemetryReplayStatus():Promise<telemetry.TelemetryReplayStatus>;

export function GetTelemetrySession(arg1:number):Promise<storage.TelemetrySession>;

export function GetTelemetryStatus():Promise<telemetry.TelemetryStatus>;

export function GetTestConditionDefaults():Promise<storage.TestConditions>;

export function GetTireDiagnosticSnapshot():Promise<storage.TireDiagnosticSnapshot>;

export function GetTireIssueAdvice():Promise<storage.TireIssueAdvice>;

export function GetTireIssueAnalysis():Promise<storage.TireIssueAnalysis>;

export function GetTireModelDiagnostic():Promise<storage.TireModelDiagnostic>;

export function GetTireRegressionSample(arg1:string):Promise<storage.TireRegressionSample>;

export function GetTrackProfile(arg1:number):Promise<storage.TrackProfile>;

export function GetTunePlanDraft(arg1:number):Promise<storage.TunePlanDraft>;

export function GetTuneProfile(arg1:number):Promise<storage.TuneProfile>;

export function GetTuneToTireInfluenceMap():Promise<storage.TuneToTireInfluenceMap>;

export function GetTuneWebServerStatus():Promise<main.TuneWebServerStatus>;

export function ListBenchmarkRuns(arg1:number,arg2:number):Promise<Array<storage.BenchmarkRun>>;

export function ListBenchmarkTracks():Promise<Array<storage.BenchmarkTrack>>;

export function ListFH6Cars():Promise<Array<storage.FH6Car>>;

export function ListRecommendedCars():Promise<Array<storage.RecommendedCar>>;

export function ListRuleThresholdProfiles():Promise<Array<storage.RuleThresholdProfile>>;

export function ListStrategyTemplates():Promise<Array<storage.StrategyTemplate>>;

export function ListTelemetrySessions(arg1:number):Promise<Array<storage.TelemetrySession>>;

export function ListTireRegressionSamples():Promise<Array<storage.TireRegressionSampleSummary>>;

export function ListTrackProfiles():Promise<Array<storage.TrackProfile>>;

export function ListTuneAdjustmentExplanations():Promise<Array<storage.TuneAdjustmentExplanation>>;

export function ListTuneHarvestCandidates(arg1:string,arg2:number):Promise<Array<storage.TuneHarvestCandidate>>;

export function ListTuneProfileSessionStats():Promise<Array<storage.TuneProfileSessionStat>>;

export function ListTuneProfileSnapshots(arg1:number):Promise<Array<storage.TuneProfileSnapshot>>;

export function ListTuneProfiles():Promise<Array<storage.TuneProfile>>;

export function ListTuneProfilesForVehicle(arg1:number,arg2:string):Promise<Array<storage.TuneProfile>>;

export function ListTuningModelPipelines():Promise<storage.TuningPipelineCatalog>;

export function ListUpgradeUnlockRules():Promise<Array<storage.UpgradeUnlockRule>>;

export function LoadRecommendedCarsFileSelection():Promise<main.RecommendedCarsFileSelection>;

export function MergeBenchmarkTrackInput(arg1:number,arg2:storage.BenchmarkTrackInput):Promise<storage.BenchmarkTrack>;

export function PauseTelemetryReplay():Promise<void>;

export function ReextractBenchmarkTrack(arg1:number,arg2:storage.BenchmarkTrackExtractionInput):Promise<storage.BenchmarkTrack>;

export function ReloadTuningKnowledge():Promise<void>;

export function RenameBenchmarkTrack(arg1:number,arg2:string):Promise<storage.BenchmarkTrack>;

export function ReplayTelemetrySession(arg1:number,arg2:number):Promise<void>;

export function ResetRuleThresholdProfile(arg1:number):Promise<storage.RuleThresholdProfile>;

export function ResolveCarNameByOrdinal(arg1:number):Promise<string>;

export function RestoreTuneProfileSnapshot(arg1:number):Promise<storage.TuneProfile>;

export function ResumeTelemetryReplay():Promise<void>;

export function RunAllTireRegressionSamples():Promise<Array<storage.TireRegressionResult>>;

export function RunTireRegressionSample(arg1:string):Promise<storage.TireRegressionResult>;

export function RunTuneHarvest(arg1:storage.TuneHarvestOptions):Promise<storage.TuneHarvestRunResult>;

export function RunTuningModelPipeline(arg1:storage.TuningPipelineRunInput):Promise<storage.TuningPipelineRunResult>;

export function SaveProfessionalPipelineConfig(arg1:storage.ProfessionalPipelineConfig):Promise<storage.ProfessionalPipelineConfig>;

export function SaveRecommendedCar(arg1:storage.RecommendedCarInput):Promise<storage.RecommendedCar>;

export function SaveRecommendedCarRecord(arg1:storage.RecommendedCarInput,arg2:string):Promise<storage.RecommendedCar>;

export function SaveRecommendedCarsFile(arg1:Array<storage.RecommendedCarInput>,arg2:string):Promise<main.RecommendedCarsFileResult>;

export function SaveTestConditionDefaults(arg1:storage.TestConditions):Promise<storage.TestConditions>;

export function SaveTireRegressionSample(arg1:storage.TireRegressionSampleInput):Promise<storage.TireRegressionSample>;

export function SaveTrackBaselineCapture(arg1:number):Promise<storage.TrackBaselineRun>;

export function SaveTrackBaselineCaptureAuto(arg1:number,arg2:string,arg3:string):Promise<storage.TrackBaselineSaveResult>;

export function SearchTuneHarvestCandidates(arg1:string,arg2:string,arg3:number):Promise<Array<storage.TuneHarvestCandidate>>;

export function SeekTelemetryReplay(arg1:number):Promise<void>;

export function SetActiveTuneProfile(arg1:number):Promise<void>;

export function StartProfessionalTelemetry(arg1:string,arg2:number):Promise<void>;

export function StartQuickTelemetry(arg1:string,arg2:number):Promise<void>;

export function StartTelemetry(arg1:string,arg2:number):Promise<void>;

export function StartTelemetryWithConditions(arg1:string,arg2:number,arg3:storage.TestConditions):Promise<void>;

export function StartTireModelTelemetry(arg1:string,arg2:number):Promise<void>;

export function StartTrackBaselineTelemetry(arg1:number,arg2:string,arg3:number):Promise<void>;

export function StartTrackCaptureTelemetry(arg1:string,arg2:number):Promise<void>;

export function StartTuneWebServer(arg1:number):Promise<void>;

export function StopTelemetry():Promise<void>;

export function StopTelemetryReplay():Promise<void>;

export function StopTrackBaselineTelemetry():Promise<void>;

export function StopTuneHarvest():Promise<void>;

export function StopTuneWebServer():Promise<void>;

export function UpdateBenchmarkTrack(arg1:number,arg2:storage.BenchmarkTrackInput):Promise<storage.BenchmarkTrack>;

export function UpdateRuleThresholdProfile(arg1:number,arg2:storage.RuleThresholdProfileInput):Promise<storage.RuleThresholdProfile>;

export function UpdateTireRegressionSampleExpectation(arg1:string,arg2:storage.TireRegressionExpectation):Promise<void>;

export function UpdateTuneHarvestCandidateStatus(arg1:number,arg2:string,arg3:string):Promise<storage.TuneHarvestCandidate>;

export function UpdateTuneProfile(arg1:number,arg2:storage.TuneProfileInput):Promise<storage.TuneProfile>;
